//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_803BA770.hpp"



void fn_803BA9EC(PPC::Runtime::GCContext* context)
{
/*803BA9EC 003B77EC*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x20, context->r1));
/*803BA9F0 003B77F0*/ PPC::Runtime::ASM::mflr(context->r0);
/*803BA9F4 003B77F4*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803BA9F8 003B77F8*/ PPC::Runtime::ASM::stfd(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803BA9FC 003B77FC*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803BAA00 003B7800*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*803BAA04 003B7804*/ PPC::Runtime::ASM::lis(context->r0, 0x10);
/*803BAA08 003B7808*/ PPC::Runtime::ASM::cmpw(context->r5, context->r0);
/*803BAA0C 003B780C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*803BAA10 003B7810*/ PPC::Runtime::ASM::stfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803BAA14 003B7814*/ PPC::Runtime::ASM::bge(.L_803BAA70);
/*803BAA18 003B7818*/ PPC::Runtime::ASM::clrlwi(context->r0, context->r5, 1);
/*803BAA1C 003B781C*/ PPC::Runtime::ASM::or.(context->r0, context->r0, context->r3);
/*803BAA20 003B7820*/ PPC::Runtime::ASM::bne(.L_803BAA3C);
/*803BAA24 003B7824*/ PPC::Runtime::ASM::lfd(context->f1, STRUCT_DOUBLE_COUNT_1805E5438 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAA28 003B7828*/ PPC::Runtime::ASM::li(context->r0, 0x21);
/*803BAA2C 003B782C*/ PPC::Runtime::ASM::lfd(context->f0, STRUCT_DOUBLE_COUNT_1805DDCF8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAA30 003B7830*/ PPC::Runtime::ASM::stw(context->r0, STRUCT_BYTE4_COUNT_1805DDCE0 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAA34 003B7834*/ PPC::Runtime::ASM::fdiv(context->f1, context->f1, context->f0);
/*803BAA38 003B7838*/ PPC::Runtime::ASM::b(.L_803BAAE8);
RUNTIME_PPC_JUMP_LABEL(.L_803BAA3C, 0x803BAA3C) //this is a jump label
/*803BAA3C 003B783C*/ PPC::Runtime::ASM::cmpwi(context->r5, 0x0);
/*803BAA40 003B7840*/ PPC::Runtime::ASM::bge(.L_803BAA5C);
/*803BAA44 003B7844*/ PPC::Runtime::ASM::fsub(context->f1, context->f1, context->f1);
/*803BAA48 003B7848*/ PPC::Runtime::ASM::lfd(context->f0, STRUCT_DOUBLE_COUNT_1805DDCF8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAA4C 003B784C*/ PPC::Runtime::ASM::li(context->r0, 0x21);
/*803BAA50 003B7850*/ PPC::Runtime::ASM::stw(context->r0, STRUCT_BYTE4_COUNT_1805DDCE0 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAA54 003B7854*/ PPC::Runtime::ASM::fdiv(context->f1, context->f1, context->f0);
/*803BAA58 003B7858*/ PPC::Runtime::ASM::b(.L_803BAAE8);
RUNTIME_PPC_JUMP_LABEL(.L_803BAA5C, 0x803BAA5C) //this is a jump label
/*803BAA5C 003B785C*/ PPC::Runtime::ASM::lfd(context->f0, STRUCT_DOUBLE_COUNT_1805E5440 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAA60 003B7860*/ PPC::Runtime::ASM::li(context->r4, -0x36);
/*803BAA64 003B7864*/ PPC::Runtime::ASM::fmul(context->f0, context->f1, context->f0);
/*803BAA68 003B7868*/ PPC::Runtime::ASM::stfd(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803BAA6C 003B786C*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_803BAA70, 0x803BAA70) //this is a jump label
/*803BAA70 003B7870*/ PPC::Runtime::ASM::lis(context->r0, 0x7ff0);
/*803BAA74 003B7874*/ PPC::Runtime::ASM::cmpw(context->r5, context->r0);
/*803BAA78 003B7878*/ PPC::Runtime::ASM::blt(.L_803BAA88);
/*803BAA7C 003B787C*/ PPC::Runtime::ASM::lfd(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803BAA80 003B7880*/ PPC::Runtime::ASM::fadd(context->f1, context->f0, context->f0);
/*803BAA84 003B7884*/ PPC::Runtime::ASM::b(.L_803BAAE8);
RUNTIME_PPC_JUMP_LABEL(.L_803BAA88, 0x803BAA88) //this is a jump label
/*803BAA88 003B7888*/ PPC::Runtime::ASM::srawi(context->r3, context->r5, 20);
/*803BAA8C 003B788C*/ PPC::Runtime::ASM::lis(context->r0, 0x4330);
/*803BAA90 003B7890*/ PPC::Runtime::ASM::add(context->r4, context->r3, context->r4);
/*803BAA94 003B7894*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803BAA98 003B7898*/ PPC::Runtime::ASM::subi(context->r4, context->r4, 0x3ff);
/*803BAA9C 003B789C*/ PPC::Runtime::ASM::lfd(context->f1, STRUCT_DOUBLE_COUNT_1805E5460 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAAA0 003B78A0*/ PPC::Runtime::ASM::srwi(context->r3, context->r4, 31);
/*803BAAA4 003B78A4*/ PPC::Runtime::ASM::add(context->r0, context->r4, context->r3);
/*803BAAA8 003B78A8*/ PPC::Runtime::ASM::xoris(context->r0, context->r0, 0x8000);
/*803BAAAC 003B78AC*/ PPC::Runtime::ASM::subfic(context->r3, context->r3, 0x3ff);
/*803BAAB0 003B78B0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*803BAAB4 003B78B4*/ PPC::Runtime::ASM::slwi(context->r0, context->r3, 20);
/*803BAAB8 003B78B8*/ PPC::Runtime::ASM::rlwimi(context->r0, context->r5, 0, 12, 31);
/*803BAABC 003B78BC*/ PPC::Runtime::ASM::lfd(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803BAAC0 003B78C0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803BAAC4 003B78C4*/ PPC::Runtime::ASM::fsub(context->f31, context->f0, context->f1);
/*803BAAC8 003B78C8*/ PPC::Runtime::ASM::lfd(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803BAACC 003B78CC*/ PPC::Runtime::ASM::bl(fn_803BA770);
/*803BAAD0 003B78D0*/ PPC::Runtime::ASM::lfd(context->f0, AT_71 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAAD4 003B78D4*/ PPC::Runtime::ASM::lfd(context->f2, AT_70 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAAD8 003B78D8*/ PPC::Runtime::ASM::fmul(context->f1, context->f0, context->f1);
/*803BAADC 003B78DC*/ PPC::Runtime::ASM::lfd(context->f0, AT_72 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803BAAE0 003B78E0*/ PPC::Runtime::ASM::fmadd(context->f1, context->f2, context->f31, context->f1);
/*803BAAE4 003B78E4*/ PPC::Runtime::ASM::fmadd(context->f1, context->f0, context->f31, context->f1);
RUNTIME_PPC_JUMP_LABEL(.L_803BAAE8, 0x803BAAE8) //this is a jump label
/*803BAAE8 003B78E8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*803BAAEC 003B78EC*/ PPC::Runtime::ASM::lfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803BAAF0 003B78F0*/ PPC::Runtime::ASM::mtlr(context->r0);
/*803BAAF4 003B78F4*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x20);
/*803BAAF8 003B78F8*/ PPC::Runtime::ASM::blr();
}