//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn___assert.hpp"
#include "fn___assert.hpp"



void fn_804424B4(PPC::Runtime::GCContext* context)
{
/*804424B4 0043F2B4*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x20, context->r1));
/*804424B8 0043F2B8*/ PPC::Runtime::ASM::mflr(context->r0);
/*804424BC 0043F2BC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*804424C0 0043F2C0*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*804424C4 0043F2C4*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*804424C8 0043F2C8*/ PPC::Runtime::ASM::clrlwi(context->r30, context->r3, 26);
/*804424CC 0043F2CC*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*804424D0 0043F2D0*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/* 804424D4 0043F2D4  7C 7C 1B 79 */ mr. context->r28 , context->r3
/*804424D8 0043F2D8*/ PPC::Runtime::ASM::bgt(.L_804424F0);
/*804424DC 0043F2DC*/ PPC::Runtime::ASM::lis(context->r3, lbl_805089E8 @ Get_MemoryOffset_HighBit);
/*804424E0 0043F2E0*/ PPC::Runtime::ASM::li(context->r4, 0x38b);
/*804424E4 0043F2E4*/ PPC::Runtime::ASM::addi(context->r3, context->r3, lbl_805089E8 @ Get_MemoryOffset_LowBit);
/*804424E8 0043F2E8*/ PPC::Runtime::ASM::li(context->r5, String_ "pid_GreaterThen_" Get_MemoryOffset_SDA21);
/*804424EC 0043F2EC*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_804424F0, 0x804424F0) //this is a jump label
/*804424F0 0043F2F0*/ PPC::Runtime::ASM::lis(context->r3, lbl_8058E298 @ Get_MemoryOffset_HighBit);
/*804424F4 0043F2F4*/ PPC::Runtime::ASM::slwi(context->r30, context->r30, 2);
/*804424F8 0043F2F8*/ PPC::Runtime::ASM::addi(context->r31, context->r3, lbl_8058E298 @ Get_MemoryOffset_LowBit);
/*804424FC 0043F2FC*/ PPC::Runtime::ASM::li(context->r3, 0x0);
/*80442500 0043F300*/ PPC::Runtime::ASM::lwzx(context->r29, context->r31, context->r30);
/*80442504 0043F304*/ PPC::Runtime::ASM::cmplwi(context->r29, 0x0);
/*80442508 0043F308*/ PPC::Runtime::ASM::beq(.L_8044251C);
/*8044250C 0043F30C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r29));
/*80442510 0043F310*/ PPC::Runtime::ASM::cmpw(context->r0, context->r28);
/*80442514 0043F314*/ PPC::Runtime::ASM::bne(.L_8044251C);
/*80442518 0043F318*/ PPC::Runtime::ASM::li(context->r3, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_8044251C, 0x8044251C) //this is a jump label
/*8044251C 0043F31C*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*80442520 0043F320*/ PPC::Runtime::ASM::bne(.L_8044253C);
/*80442524 0043F324*/ PPC::Runtime::ASM::lis(context->r3, lbl_805089E8 @ Get_MemoryOffset_HighBit);
/*80442528 0043F328*/ PPC::Runtime::ASM::lis(context->r5, lbl_80508B14 @ Get_MemoryOffset_HighBit);
/*8044252C 0043F32C*/ PPC::Runtime::ASM::addi(context->r3, context->r3, lbl_805089E8 @ Get_MemoryOffset_LowBit);
/*80442530 0043F330*/ PPC::Runtime::ASM::li(context->r4, 0x38d);
/*80442534 0043F334*/ PPC::Runtime::ASM::addi(context->r5, context->r5, lbl_80508B14 @ Get_MemoryOffset_LowBit);
/*80442538 0043F338*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_8044253C, 0x8044253C) //this is a jump label
/*8044253C 0043F33C*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*80442540 0043F340*/ PPC::Runtime::ASM::stwx(context->r0, context->r31, context->r30);
/*80442544 0043F344*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r29));
/*80442548 0043F348*/ PPC::Runtime::ASM::rlwinm(context->r0, context->r0, 0, 3, 1);
/*8044254C 0043F34C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r29));
/*80442550 0043F350*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r29));
/*80442554 0043F354*/ PPC::Runtime::ASM::clrlwi(context->r0, context->r0, 2);
/*80442558 0043F358*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r29));
/*8044255C 0043F35C*/ PPC::Runtime::ASM::lwz(context->r3, STRUCT_BYTE4_COUNT_1805DE454 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80442560 0043F360*/ PPC::Runtime::ASM::subi(context->r0, context->r3, 0x1);
/*80442564 0043F364*/ PPC::Runtime::ASM::stw(context->r0, STRUCT_BYTE4_COUNT_1805DE454 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80442568 0043F368*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*8044256C 0043F36C*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*80442570 0043F370*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80442574 0043F374*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*80442578 0043F378*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*8044257C 0043F37C*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80442580 0043F380*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x20);
/*80442584 0043F384*/ PPC::Runtime::ASM::blr();
}