//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_803792B8.hpp"
#include "fn_8037B33C.hpp"



void fn_80296D3C(PPC::Runtime::GCContext* context)
{
/*80296D3C 00293B3C*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x20, context->r1));
/*80296D40 00293B40*/ PPC::Runtime::ASM::mflr(context->r0);
/*80296D44 00293B44*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*80296D48 00293B48*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*80296D4C 00293B4C*/ PPC::Runtime::ASM::mr(context->r31, context->r4);
/*80296D50 00293B50*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/* 80296D54 00293B54  7C 7E 1B 79 */ mr. context->r30 , context->r3
/*80296D58 00293B58*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80296D5C 00293B5C*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*80296D60 00293B60*/ PPC::Runtime::ASM::beq(.L_8029701C);
/*80296D64 00293B64*/ PPC::Runtime::ASM::lis(context->r3, lbl_804EFD7C @ Get_MemoryOffset_HighBit);
/*80296D68 00293B68*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*80296D6C 00293B6C*/ PPC::Runtime::ASM::addi(context->r6, context->r3, lbl_804EFD7C @ Get_MemoryOffset_LowBit);
/*80296D70 00293B70*/ PPC::Runtime::ASM::li(context->r5, lbl_805D7778 @ Get_MemoryOffset_SDA21);
/*80296D74 00293B74*/ PPC::Runtime::ASM::stw(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*80296D78 00293B78*/ PPC::Runtime::ASM::addi(context->r3, context->r6, 0x28);
/*80296D7C 00293B7C*/ PPC::Runtime::ASM::addi(context->r0, context->r6, 0x68);
/*80296D80 00293B80*/ PPC::Runtime::ASM::li(context->r6, lbl_805D7770 @ Get_MemoryOffset_SDA21);
/*80296D84 00293B84*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*80296D88 00293B88*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*80296D8C 00293B8C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r30));
/*80296D90 00293B90*/ PPC::Runtime::ASM::lwz(context->r3, STRUCT_BYTE4_COUNT_1805DDAB8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80296D94 00293B94*/ PPC::Runtime::ASM::bl(fn_803AD760);
/*80296D98 00293B98*/ PPC::Runtime::ASM::mr(context->r28, context->r3);
/*80296D9C 00293B9C*/ PPC::Runtime::ASM::b(.L_80296E20);
RUNTIME_PPC_JUMP_LABEL(.L_80296DA0, 0x80296DA0) //this is a jump label
/*80296DA0 00293BA0*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*80296DA4 00293BA4*/ PPC::Runtime::ASM::lhz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xd0, context->r30));
/*80296DA8 00293BA8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*80296DAC 00293BAC*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r12));
/*80296DB0 00293BB0*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296DB4 00293BB4*/ PPC::Runtime::ASM::bctrl();
/*80296DB8 00293BB8*/ PPC::Runtime::ASM::cmplw(context->r3, context->r29);
/*80296DBC 00293BBC*/ PPC::Runtime::ASM::bne(.L_80296E08);
/*80296DC0 00293BC0*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*80296DC4 00293BC4*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*80296DC8 00293BC8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r12));
/*80296DCC 00293BCC*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296DD0 00293BD0*/ PPC::Runtime::ASM::bctrl();
/* 80296DD4 00293BD4  54 60 06 3F */ clrlwi. context->r0 , context->r3 , 24
/*80296DD8 00293BD8*/ PPC::Runtime::ASM::beq(.L_80296E08);
/*80296DDC 00293BDC*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb0, context->r30));
/*80296DE0 00293BE0*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*80296DE4 00293BE4*/ PPC::Runtime::ASM::lwz(context->r3, STRUCT_BYTE4_COUNT_1805DDB64 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80296DE8 00293BE8*/ PPC::Runtime::ASM::li(context->r5, lbl_805D7788 @ Get_MemoryOffset_SDA21);
/*80296DEC 00293BEC*/ PPC::Runtime::ASM::li(context->r6, lbl_805D7780 @ Get_MemoryOffset_SDA21);
/*80296DF0 00293BF0*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*80296DF4 00293BF4*/ PPC::Runtime::ASM::bl(fn_803AD760);
/*80296DF8 00293BF8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r3));
/*80296DFC 00293BFC*/ PPC::Runtime::ASM::add(context->r0, context->r0, context->r29);
/*80296E00 00293C00*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r3));
/*80296E04 00293C04*/ PPC::Runtime::ASM::b(.L_80296E28);
RUNTIME_PPC_JUMP_LABEL(.L_80296E08, 0x80296E08) //this is a jump label
/*80296E08 00293C08*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*80296E0C 00293C0C*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*80296E10 00293C10*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r12));
/*80296E14 00293C14*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296E18 00293C18*/ PPC::Runtime::ASM::bctrl();
/*80296E1C 00293C1C*/ PPC::Runtime::ASM::mr(context->r28, context->r3);
RUNTIME_PPC_JUMP_LABEL(.L_80296E20, 0x80296E20) //this is a jump label
/*80296E20 00293C20*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*80296E24 00293C24*/ PPC::Runtime::ASM::bne(.L_80296DA0);
RUNTIME_PPC_JUMP_LABEL(.L_80296E28, 0x80296E28) //this is a jump label
/*80296E28 00293C28*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x160);
/*80296E2C 00293C2C*/ PPC::Runtime::ASM::beq(.L_80296E64);
/*80296E30 00293C30*/ PPC::Runtime::ASM::lis(context->r3, lbl_804BDD08 @ Get_MemoryOffset_HighBit);
/*80296E34 00293C34*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x160);
/*80296E38 00293C38*/ PPC::Runtime::ASM::addi(context->r0, context->r3, lbl_804BDD08 @ Get_MemoryOffset_LowBit);
/*80296E3C 00293C3C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x160, context->r30));
/*80296E40 00293C40*/ PPC::Runtime::ASM::beq(.L_80296E64);
/*80296E44 00293C44*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BDCBC @ Get_MemoryOffset_HighBit);
/*80296E48 00293C48*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x160);
/*80296E4C 00293C4C*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BDCBC @ Get_MemoryOffset_LowBit);
/*80296E50 00293C50*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x160, context->r30));
/*80296E54 00293C54*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x160, context->r30));
/*80296E58 00293C58*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r12));
/*80296E5C 00293C5C*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296E60 00293C60*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_80296E64, 0x80296E64) //this is a jump label
/*80296E64 00293C64*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x124);
/*80296E68 00293C68*/ PPC::Runtime::ASM::beq(.L_80296EB4);
/*80296E6C 00293C6C*/ PPC::Runtime::ASM::lis(context->r3, lbl_804BE104 @ Get_MemoryOffset_HighBit);
/*80296E70 00293C70*/ PPC::Runtime::ASM::addi(context->r0, context->r3, lbl_804BE104 @ Get_MemoryOffset_LowBit);
/*80296E74 00293C74*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*80296E78 00293C78*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x134, context->r30));
/*80296E7C 00293C7C*/ PPC::Runtime::ASM::cmpwi(context->r4, -0x1);
/*80296E80 00293C80*/ PPC::Runtime::ASM::beq(.L_80296E8C);
/*80296E84 00293C84*/ PPC::Runtime::ASM::lwz(context->r3, STRUCT_BYTE4_COUNT_1805DDC70 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80296E88 00293C88*/ PPC::Runtime::ASM::bl(fn_803792B8);
RUNTIME_PPC_JUMP_LABEL(.L_80296E8C, 0x80296E8C) //this is a jump label
/*80296E8C 00293C8C*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x124);
/*80296E90 00293C90*/ PPC::Runtime::ASM::beq(.L_80296EB4);
/*80296E94 00293C94*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BE0C4 @ Get_MemoryOffset_HighBit);
/*80296E98 00293C98*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x124);
/*80296E9C 00293C9C*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BE0C4 @ Get_MemoryOffset_LowBit);
/*80296EA0 00293CA0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*80296EA4 00293CA4*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*80296EA8 00293CA8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r12));
/*80296EAC 00293CAC*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296EB0 00293CB0*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_80296EB4, 0x80296EB4) //this is a jump label
/*80296EB4 00293CB4*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0xd8);
/*80296EB8 00293CB8*/ PPC::Runtime::ASM::beq(.L_80296EFC);
/*80296EBC 00293CBC*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BDF70 @ Get_MemoryOffset_HighBit);
/*80296EC0 00293CC0*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0xd8);
/*80296EC4 00293CC4*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BDF70 @ Get_MemoryOffset_LowBit);
/*80296EC8 00293CC8*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*80296ECC 00293CCC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xd8, context->r30));
/*80296ED0 00293CD0*/ PPC::Runtime::ASM::bl(fn_8037B33C);
/*80296ED4 00293CD4*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0xd8);
/*80296ED8 00293CD8*/ PPC::Runtime::ASM::beq(.L_80296EFC);
/*80296EDC 00293CDC*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BDF2C @ Get_MemoryOffset_HighBit);
/*80296EE0 00293CE0*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0xd8);
/*80296EE4 00293CE4*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BDF2C @ Get_MemoryOffset_LowBit);
/*80296EE8 00293CE8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xd8, context->r30));
/*80296EEC 00293CEC*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xd8, context->r30));
/*80296EF0 00293CF0*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r12));
/*80296EF4 00293CF4*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296EF8 00293CF8*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_80296EFC, 0x80296EFC) //this is a jump label
/*80296EFC 00293CFC*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x90);
/*80296F00 00293D00*/ PPC::Runtime::ASM::beq(.L_80296F68);
/*80296F04 00293D04*/ PPC::Runtime::ASM::lis(context->r3, Struct_FuncPtrs_Offset_2 @ Get_MemoryOffset_HighBit);
/*80296F08 00293D08*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0xb4);
/*80296F0C 00293D0C*/ PPC::Runtime::ASM::addi(context->r3, context->r3, Struct_FuncPtrs_Offset_2 @ Get_MemoryOffset_LowBit);
/*80296F10 00293D10*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x90, context->r30));
/*80296F14 00293D14*/ PPC::Runtime::ASM::addi(context->r0, context->r3, 0x38);
/*80296F18 00293D18*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb4, context->r30));
/*80296F1C 00293D1C*/ PPC::Runtime::ASM::beq(.L_80296F2C);
/*80296F20 00293D20*/ PPC::Runtime::ASM::lis(context->r3, lbl_804BDB74 @ Get_MemoryOffset_HighBit);
/*80296F24 00293D24*/ PPC::Runtime::ASM::addi(context->r0, context->r3, lbl_804BDB74 @ Get_MemoryOffset_LowBit);
/*80296F28 00293D28*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb4, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_80296F2C, 0x80296F2C) //this is a jump label
/*80296F2C 00293D2C*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x90);
/*80296F30 00293D30*/ PPC::Runtime::ASM::beq(.L_80296F68);
/*80296F34 00293D34*/ PPC::Runtime::ASM::lis(context->r3, FuncPtrList_2 @ Get_MemoryOffset_HighBit);
/*80296F38 00293D38*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x90);
/*80296F3C 00293D3C*/ PPC::Runtime::ASM::addi(context->r0, context->r3, FuncPtrList_2 @ Get_MemoryOffset_LowBit);
/*80296F40 00293D40*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x90, context->r30));
/*80296F44 00293D44*/ PPC::Runtime::ASM::beq(.L_80296F68);
/*80296F48 00293D48*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BF4DC @ Get_MemoryOffset_HighBit);
/*80296F4C 00293D4C*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x90);
/*80296F50 00293D50*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BF4DC @ Get_MemoryOffset_LowBit);
/*80296F54 00293D54*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x90, context->r30));
/*80296F58 00293D58*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x90, context->r30));
/*80296F5C 00293D5C*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r12));
/*80296F60 00293D60*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296F64 00293D64*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_80296F68, 0x80296F68) //this is a jump label
/*80296F68 00293D68*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x6c);
/*80296F6C 00293D6C*/ PPC::Runtime::ASM::beq(.L_80296F8C);
/*80296F70 00293D70*/ PPC::Runtime::ASM::lis(context->r3, lbl_804F4E38 @ Get_MemoryOffset_HighBit);
/*80296F74 00293D74*/ PPC::Runtime::ASM::addi(context->r0, context->r3, lbl_804F4E38 @ Get_MemoryOffset_LowBit);
/*80296F78 00293D78*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x6c, context->r30));
/*80296F7C 00293D7C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x70, context->r30));
/*80296F80 00293D80*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*80296F84 00293D84*/ PPC::Runtime::ASM::beq(.L_80296F8C);
/*80296F88 00293D88*/ PPC::Runtime::ASM::bl(fn_HSD_JObjUnref);
RUNTIME_PPC_JUMP_LABEL(.L_80296F8C, 0x80296F8C) //this is a jump label
/*80296F8C 00293D8C*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x54);
/*80296F90 00293D90*/ PPC::Runtime::ASM::beq(.L_80296FB4);
/*80296F94 00293D94*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BF4B4 @ Get_MemoryOffset_HighBit);
/*80296F98 00293D98*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x54);
/*80296F9C 00293D9C*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BF4B4 @ Get_MemoryOffset_LowBit);
/*80296FA0 00293DA0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r30));
/*80296FA4 00293DA4*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r30));
/*80296FA8 00293DA8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r12));
/*80296FAC 00293DAC*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296FB0 00293DB0*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_80296FB4, 0x80296FB4) //this is a jump label
/*80296FB4 00293DB4*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*80296FB8 00293DB8*/ PPC::Runtime::ASM::beq(.L_8029700C);
/*80296FBC 00293DBC*/ PPC::Runtime::ASM::lis(context->r3, lbl_804BDBE8 @ Get_MemoryOffset_HighBit);
/*80296FC0 00293DC0*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0x14);
/*80296FC4 00293DC4*/ PPC::Runtime::ASM::addi(context->r3, context->r3, lbl_804BDBE8 @ Get_MemoryOffset_LowBit);
/*80296FC8 00293DC8*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*80296FCC 00293DCC*/ PPC::Runtime::ASM::addi(context->r0, context->r3, 0x28);
/*80296FD0 00293DD0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*80296FD4 00293DD4*/ PPC::Runtime::ASM::beq(.L_80296FF8);
/*80296FD8 00293DD8*/ PPC::Runtime::ASM::lis(context->r4, lbl_804BDBC0 @ Get_MemoryOffset_HighBit);
/*80296FDC 00293DDC*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x14);
/*80296FE0 00293DE0*/ PPC::Runtime::ASM::addi(context->r0, context->r4, lbl_804BDBC0 @ Get_MemoryOffset_LowBit);
/*80296FE4 00293DE4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*80296FE8 00293DE8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*80296FEC 00293DEC*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r12));
/*80296FF0 00293DF0*/ PPC::Runtime::ASM::mtctr(context->r12);
/*80296FF4 00293DF4*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_80296FF8, 0x80296FF8) //this is a jump label
/*80296FF8 00293DF8*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*80296FFC 00293DFC*/ PPC::Runtime::ASM::beq(.L_8029700C);
/*80297000 00293E00*/ PPC::Runtime::ASM::lis(context->r3, lbl_804BDB74 @ Get_MemoryOffset_HighBit);
/*80297004 00293E04*/ PPC::Runtime::ASM::addi(context->r0, context->r3, lbl_804BDB74 @ Get_MemoryOffset_LowBit);
/*80297008 00293E08*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_8029700C, 0x8029700C) //this is a jump label
/*8029700C 00293E0C*/ PPC::Runtime::ASM::extsh.(context->r0, context->r31);
/*80297010 00293E10*/ PPC::Runtime::ASM::ble(.L_8029701C);
/*80297014 00293E14*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*80297018 00293E18*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_8029701C, 0x8029701C) //this is a jump label
/*8029701C 00293E1C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*80297020 00293E20*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*80297024 00293E24*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*80297028 00293E28*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*8029702C 00293E2C*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80297030 00293E30*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*80297034 00293E34*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80297038 00293E38*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x20);
/*8029703C 00293E3C*/ PPC::Runtime::ASM::blr();
}