//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "OSDisableInterrupts.hpp"
#include "fn_803EC1F4.hpp"
#include "OSRestoreInterrupts.hpp"



void fn_803EC47C(PPC::Runtime::GCContext* context)
{
/*803EC47C 003E927C*/ PPC::Runtime::ASM::mflr(context->r0);
/*803EC480 003E9280*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r1));
/*803EC484 003E9284*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x20, context->r1));
/*803EC488 003E9288*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803EC48C 003E928C*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803EC490 003E9290*/ PPC::Runtime::ASM::addi(context->r30, context->r4, 0x0);
/*803EC494 003E9294*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*803EC498 003E9298*/ PPC::Runtime::ASM::addi(context->r29, context->r3, 0x0);
/*803EC49C 003E929C*/ PPC::Runtime::ASM::bl(OSDisableInterrupts);
/*803EC4A0 003E92A0*/ PPC::Runtime::ASM::addi(context->r31, context->r3, 0x0);
/*803EC4A4 003E92A4*/ PPC::Runtime::ASM::addi(context->r3, context->r29, 0x0);
/*803EC4A8 003E92A8*/ PPC::Runtime::ASM::bl(fn_803EC1F4);
/*803EC4AC 003E92AC*/ PPC::Runtime::ASM::lis(context->r3, STRUCT_BYTE4_COUNT_18056E9E8 @ Get_MemoryOffset_HighBit);
/*803EC4B0 003E92B0*/ PPC::Runtime::ASM::slwi(context->r5, context->r30, 2);
/*803EC4B4 003E92B4*/ PPC::Runtime::ASM::addi(context->r0, context->r3, STRUCT_BYTE4_COUNT_18056E9E8 @ Get_MemoryOffset_LowBit);
/*803EC4B8 003E92B8*/ PPC::Runtime::ASM::add(context->r4, context->r0, context->r5);
/*803EC4BC 003E92BC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803EC4C0 003E92C0*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803EC4C4 003E92C4*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*803EC4C8 003E92C8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r29));
/*803EC4CC 003E92CC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*803EC4D0 003E92D0*/ PPC::Runtime::ASM::cmplwi(context->r0, 0x0);
/*803EC4D4 003E92D4*/ PPC::Runtime::ASM::beq(.L_803EC4E8);
/*803EC4D8 003E92D8*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803EC4DC 003E92DC*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r3));
/*803EC4E0 003E92E0*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803EC4E4 003E92E4*/ PPC::Runtime::ASM::b(.L_803EC4FC);
RUNTIME_PPC_JUMP_LABEL(.L_803EC4E8, 0x803EC4E8) //this is a jump label
/*803EC4E8 003E92E8*/ PPC::Runtime::ASM::lis(context->r3, STRUCT_BYTE4_COUNT_18056EA68 @ Get_MemoryOffset_HighBit);
/*803EC4EC 003E92EC*/ PPC::Runtime::ASM::addi(context->r0, context->r3, STRUCT_BYTE4_COUNT_18056EA68 @ Get_MemoryOffset_LowBit);
/*803EC4F0 003E92F0*/ PPC::Runtime::ASM::add(context->r3, context->r0, context->r5);
/*803EC4F4 003E92F4*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r3));
/*803EC4F8 003E92F8*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
RUNTIME_PPC_JUMP_LABEL(.L_803EC4FC, 0x803EC4FC) //this is a jump label
/*803EC4FC 003E92FC*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r29));
/*803EC500 003E9300*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803EC504 003E9304*/ PPC::Runtime::ASM::bl(OSRestoreInterrupts);
/*803EC508 003E9308*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*803EC50C 003E930C*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803EC510 003E9310*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803EC514 003E9314*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*803EC518 003E9318*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x20);
/*803EC51C 003E931C*/ PPC::Runtime::ASM::mtlr(context->r0);
/*803EC520 003E9320*/ PPC::Runtime::ASM::blr();
}