//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_glxCopyMatrix_TakeParams_Float4By4Ref_NlMaxtrix4Ref.hpp"
#include "fn_80253F0C.hpp"



void fn_80109458(PPC::Runtime::GCContext* context)
{
/*80109458 00106258*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x30, context->r1));
/*8010945C 0010625C*/ PPC::Runtime::ASM::mflr(context->r0);
/*80109460 00106260*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*80109464 00106264*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*80109468 00106268*/ PPC::Runtime::ASM::bl(_savegpr_26);
/*8010946C 0010626C*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r3));
/*80109470 00106270*/ PPC::Runtime::ASM::lwz(context->r5, STRUCT_BYTE4_COUNT_1grGlobalP @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80109474 00106274*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r7));
/*80109478 00106278*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r3));
/*8010947C 0010627C*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r3));
/*80109480 00106280*/ PPC::Runtime::ASM::cmplwi(context->r6, 0x0);
/*80109484 00106284*/ PPC::Runtime::ASM::beq(.L_8010960C);
/*80109488 00106288*/ PPC::Runtime::ASM::cmpwi(context->r4, 0x0);
/*8010948C 0010628C*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x164, context->r7));
/*80109490 00106290*/ PPC::Runtime::ASM::blt(.L_8010960C);
/*80109494 00106294*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r6));
/*80109498 00106298*/ PPC::Runtime::ASM::cmpw(context->r4, context->r0);
/*8010949C 0010629C*/ PPC::Runtime::ASM::bge(.L_8010960C);
/*801094A0 001062A0*/ PPC::Runtime::ASM::cmpwi(context->r4, 0x0);
/*801094A4 001062A4*/ PPC::Runtime::ASM::li(context->r8, 0x0);
/*801094A8 001062A8*/ PPC::Runtime::ASM::ble(.L_801094F0);
/*801094AC 001062AC*/ PPC::Runtime::ASM::cmpwi(context->r4, 0x8);
/*801094B0 001062B0*/ PPC::Runtime::ASM::subi(context->r3, context->r4, 0x8);
/*801094B4 001062B4*/ PPC::Runtime::ASM::ble(.L_801094D8);
/*801094B8 001062B8*/ PPC::Runtime::ASM::addi(context->r0, context->r3, 0x7);
/*801094BC 001062BC*/ PPC::Runtime::ASM::srwi(context->r0, context->r0, 3);
/*801094C0 001062C0*/ PPC::Runtime::ASM::mtctr(context->r0);
/*801094C4 001062C4*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*801094C8 001062C8*/ PPC::Runtime::ASM::ble(.L_801094D8);
RUNTIME_PPC_JUMP_LABEL(.L_801094CC, 0x801094CC) //this is a jump label
/*801094CC 001062CC*/ PPC::Runtime::ASM::srwi(context->r7, context->r7, 8);
/*801094D0 001062D0*/ PPC::Runtime::ASM::addi(context->r8, context->r8, 0x8);
/*801094D4 001062D4*/ PPC::Runtime::ASM::bdnz(.L_801094CC);
RUNTIME_PPC_JUMP_LABEL(.L_801094D8, 0x801094D8) //this is a jump label
/*801094D8 001062D8*/ PPC::Runtime::ASM::subf(context->r0, context->r8, context->r4);
/*801094DC 001062DC*/ PPC::Runtime::ASM::mtctr(context->r0);
/*801094E0 001062E0*/ PPC::Runtime::ASM::cmpw(context->r8, context->r4);
/*801094E4 001062E4*/ PPC::Runtime::ASM::bge(.L_801094F0);
RUNTIME_PPC_JUMP_LABEL(.L_801094E8, 0x801094E8) //this is a jump label
/*801094E8 001062E8*/ PPC::Runtime::ASM::srwi(context->r7, context->r7, 1);
/*801094EC 001062EC*/ PPC::Runtime::ASM::bdnz(.L_801094E8);
RUNTIME_PPC_JUMP_LABEL(.L_801094F0, 0x801094F0) //this is a jump label
/* 801094F0 001062F0  54 E0 07 FF */ clrlwi. context->r0 , context->r7 , 31
/*801094F4 001062F4*/ PPC::Runtime::ASM::bne(.L_8010960C);
/*801094F8 001062F8*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r6));
/*801094FC 001062FC*/ PPC::Runtime::ASM::slwi(context->r0, context->r4, 4);
/*80109500 00106300*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r5));
/*80109504 00106304*/ PPC::Runtime::ASM::add(context->r4, context->r6, context->r0);
/*80109508 00106308*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r4));
/*8010950C 0010630C*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r4));
/*80109510 00106310*/ PPC::Runtime::ASM::slwi(context->r0, context->r0, 3);
/*80109514 00106314*/ PPC::Runtime::ASM::lwzx(context->r30, context->r3, context->r0);
/*80109518 00106318*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*8010951C 0010631C*/ PPC::Runtime::ASM::bne(.L_80109530);
/*80109520 00106320*/ PPC::Runtime::ASM::li(context->r3, lbl_805D62F8 @ Get_MemoryOffset_SDA21);
/*80109524 00106324*/ PPC::Runtime::ASM::li(context->r4, 0x47c);
/*80109528 00106328*/ PPC::Runtime::ASM::li(context->r5, lbl_805D6300 @ Get_MemoryOffset_SDA21);
/*8010952C 0010632C*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_80109530, 0x80109530) //this is a jump label
/*80109530 00106330*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*80109534 00106334*/ PPC::Runtime::ASM::beq(.L_80109578);
/*80109538 00106338*/ PPC::Runtime::ASM::bne(.L_8010954C);
/*8010953C 0010633C*/ PPC::Runtime::ASM::li(context->r3, lbl_805D62F8 @ Get_MemoryOffset_SDA21);
/*80109540 00106340*/ PPC::Runtime::ASM::li(context->r4, 0x25d);
/*80109544 00106344*/ PPC::Runtime::ASM::li(context->r5, lbl_805D6300 @ Get_MemoryOffset_SDA21);
/*80109548 00106348*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_8010954C, 0x8010954C) //this is a jump label
/*8010954C 0010634C*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*80109550 00106350*/ PPC::Runtime::ASM::li(context->r3, 0x0);
/*80109554 00106354*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r4, 0, 8, 8);
/*80109558 00106358*/ PPC::Runtime::ASM::bne(.L_80109568);
/*8010955C 0010635C*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r4, 0, 25, 25);
/*80109560 00106360*/ PPC::Runtime::ASM::beq(.L_80109568);
/*80109564 00106364*/ PPC::Runtime::ASM::li(context->r3, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_80109568, 0x80109568) //this is a jump label
/*80109568 00106368*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*8010956C 0010636C*/ PPC::Runtime::ASM::beq(.L_80109578);
/*80109570 00106370*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*80109574 00106374*/ PPC::Runtime::ASM::bl(fn_HSD_JObjSetupMatrixSub);
RUNTIME_PPC_JUMP_LABEL(.L_80109578, 0x80109578) //this is a jump label
/*80109578 00106378*/ PPC::Runtime::ASM::li(context->r27, 0x0);
/*8010957C 0010637C*/ PPC::Runtime::ASM::lis(context->r3, AllZeros_3 @ Get_MemoryOffset_HighBit);
/*80109580 00106380*/ PPC::Runtime::ASM::mr(context->r28, context->r27);
/*80109584 00106384*/ PPC::Runtime::ASM::addi(context->r29, context->r30, 0x44);
/*80109588 00106388*/ PPC::Runtime::ASM::addi(context->r30, context->r3, AllZeros_3 @ Get_MemoryOffset_LowBit);
/*8010958C 0010638C*/ PPC::Runtime::ASM::b(.L_80109600);
RUNTIME_PPC_JUMP_LABEL(.L_80109590, 0x80109590) //this is a jump label
/*80109590 00106390*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*80109594 00106394*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r30));
/*80109598 00106398*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r30));
/*8010959C 0010639C*/ PPC::Runtime::ASM::stw(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*801095A0 001063A0*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*801095A4 001063A4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*801095A8 001063A8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r31));
/*801095AC 001063AC*/ PPC::Runtime::ASM::add(context->r4, context->r0, context->r28);
/*801095B0 001063B0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r4));
/*801095B4 001063B4*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r4));
/*801095B8 001063B8*/ PPC::Runtime::ASM::bl(fn_glxCopyMatrix_TakeParams_Float4By4Ref_NlMaxtrix4Ref);
/*801095BC 001063BC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r31));
/*801095C0 001063C0*/ PPC::Runtime::ASM::mr(context->r26, context->r3);
/*801095C4 001063C4*/ PPC::Runtime::ASM::mr(context->r3, context->r29);
/*801095C8 001063C8*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0x8);
/*801095CC 001063CC*/ PPC::Runtime::ASM::add(context->r4, context->r0, context->r28);
/*801095D0 001063D0*/ PPC::Runtime::ASM::bl(fn_PSMTXMultVec);
/*801095D4 001063D4*/ PPC::Runtime::ASM::cmpwi(context->r26, -0x1);
/*801095D8 001063D8*/ PPC::Runtime::ASM::beq(.L_801095F8);
/*801095DC 001063DC*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r31));
/*801095E0 001063E0*/ PPC::Runtime::ASM::addi(context->r0, context->r28, 0x14);
/*801095E4 001063E4*/ PPC::Runtime::ASM::mr(context->r3, context->r26);
/*801095E8 001063E8*/ PPC::Runtime::ASM::addi(context->r6, context->r1, 0x8);
/*801095EC 001063EC*/ PPC::Runtime::ASM::lwzx(context->r5, context->r4, context->r0);
/*801095F0 001063F0*/ PPC::Runtime::ASM::li(context->r4, 0xb);
/*801095F4 001063F4*/ PPC::Runtime::ASM::bl(fn_80253F0C);
RUNTIME_PPC_JUMP_LABEL(.L_801095F8, 0x801095F8) //this is a jump label
/*801095F8 001063F8*/ PPC::Runtime::ASM::addi(context->r28, context->r28, 0x18);
/*801095FC 001063FC*/ PPC::Runtime::ASM::addi(context->r27, context->r27, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_80109600, 0x80109600) //this is a jump label
/*80109600 00106400*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r31));
/*80109604 00106404*/ PPC::Runtime::ASM::cmpw(context->r27, context->r0);
/*80109608 00106408*/ PPC::Runtime::ASM::blt(.L_80109590);
RUNTIME_PPC_JUMP_LABEL(.L_8010960C, 0x8010960C) //this is a jump label
/*8010960C 0010640C*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*80109610 00106410*/ PPC::Runtime::ASM::bl(_restgpr_26);
/*80109614 00106414*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*80109618 00106418*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8010961C 0010641C*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x30);
/*80109620 00106420*/ PPC::Runtime::ASM::blr();
}