//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_801A0640(PPC::Runtime::GCContext* context)
{
/*801A0640 0019D440*/ PPC::Runtime::ASM::blr();
}