//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_8022D248.hpp"



void fn_8022EE00(PPC::Runtime::GCContext* context)
{
/*8022EE00 0022BC00*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*8022EE04 0022BC04*/ PPC::Runtime::ASM::mflr(context->r0);
/*8022EE08 0022BC08*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x5);
/*8022EE0C 0022BC0C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8022EE10 0022BC10*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*8022EE14 0022BC14*/ PPC::Runtime::ASM::mr(context->r31, context->r4);
/*8022EE18 0022BC18*/ PPC::Runtime::ASM::beq(.L_8022F13C);
/*8022EE1C 0022BC1C*/ PPC::Runtime::ASM::bl(fn_8022D248);
/*8022EE20 0022BC20*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
/*8022EE24 0022BC24*/ PPC::Runtime::ASM::extrwi(context->r0, context->r0, 5, 24);
/*8022EE28 0022BC28*/ PPC::Runtime::ASM::cmplwi(context->r0, 0x6);
/*8022EE2C 0022BC2C*/ PPC::Runtime::ASM::bne(.L_8022EE70);
/*8022EE30 0022BC30*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*8022EE34 0022BC34*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*8022EE38 0022BC38*/ PPC::Runtime::ASM::b(.L_8022EE4C);
RUNTIME_PPC_JUMP_LABEL(.L_8022EE3C, 0x8022EE3C) //this is a jump label
/*8022EE3C 0022BC3C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x364, context->r4));
/*8022EE40 0022BC40*/ PPC::Runtime::ASM::addi(context->r6, context->r6, 0x1);
/*8022EE44 0022BC44*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x360, context->r4));
/*8022EE48 0022BC48*/ PPC::Runtime::ASM::addi(context->r4, context->r4, 0x4);
RUNTIME_PPC_JUMP_LABEL(.L_8022EE4C, 0x8022EE4C) //this is a jump label
/*8022EE4C 0022BC4C*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
/*8022EE50 0022BC50*/ PPC::Runtime::ASM::extrwi(context->r5, context->r0, 5, 24);
/*8022EE54 0022BC54*/ PPC::Runtime::ASM::subi(context->r0, context->r5, 0x1);
/*8022EE58 0022BC58*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022EE5C 0022BC5C*/ PPC::Runtime::ASM::blt(.L_8022EE3C);
/*8022EE60 0022BC60*/ PPC::Runtime::ASM::slwi(context->r0, context->r5, 2);
/*8022EE64 0022BC64*/ PPC::Runtime::ASM::add(context->r4, context->r3, context->r0);
/*8022EE68 0022BC68*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x35c, context->r4));
/*8022EE6C 0022BC6C*/ PPC::Runtime::ASM::b(.L_8022EE90);
RUNTIME_PPC_JUMP_LABEL(.L_8022EE70, 0x8022EE70) //this is a jump label
/*8022EE70 0022BC70*/ PPC::Runtime::ASM::clrlslwi(context->r0, context->r0, 24, 2);
/*8022EE74 0022BC74*/ PPC::Runtime::ASM::add(context->r4, context->r3, context->r0);
/*8022EE78 0022BC78*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x360, context->r4));
/*8022EE7C 0022BC7C*/ PPC::Runtime::ASM::lbz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
/*8022EE80 0022BC80*/ PPC::Runtime::ASM::extrwi(context->r4, context->r5, 5, 24);
/*8022EE84 0022BC84*/ PPC::Runtime::ASM::addi(context->r0, context->r4, 0x1);
/*8022EE88 0022BC88*/ PPC::Runtime::ASM::rlwimi(context->r5, context->r0, 3, 24, 28);
/*8022EE8C 0022BC8C*/ PPC::Runtime::ASM::stb(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_8022EE90, 0x8022EE90) //this is a jump label
/*8022EE90 0022BC90*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*8022EE94 0022BC94*/ PPC::Runtime::ASM::lis(context->r4, lbl_804B4C20 @ Get_MemoryOffset_HighBit);
/*8022EE98 0022BC98*/ PPC::Runtime::ASM::li(context->r0, 0x2);
/*8022EE9C 0022BC9C*/ PPC::Runtime::ASM::mr(context->r8, context->r3);
/*8022EEA0 0022BCA0*/ PPC::Runtime::ASM::mr(context->r7, context->r6);
/*8022EEA4 0022BCA4*/ PPC::Runtime::ASM::addi(context->r4, context->r4, lbl_804B4C20 @ Get_MemoryOffset_LowBit);
/*8022EEA8 0022BCA8*/ PPC::Runtime::ASM::mtctr(context->r0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EEAC, 0x8022EEAC) //this is a jump label
/*8022EEAC 0022BCAC*/ PPC::Runtime::ASM::slwi(context->r0, context->r6, 2);
/*8022EEB0 0022BCB0*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x360, context->r8));
/*8022EEB4 0022BCB4*/ PPC::Runtime::ASM::lwzx(context->r0, context->r4, context->r0);
/*8022EEB8 0022BCB8*/ PPC::Runtime::ASM::cmpw(context->r5, context->r0);
/*8022EEBC 0022BCBC*/ PPC::Runtime::ASM::bne(.L_8022EEC8);
/*8022EEC0 0022BCC0*/ PPC::Runtime::ASM::addi(context->r6, context->r6, 0x1);
/*8022EEC4 0022BCC4*/ PPC::Runtime::ASM::b(.L_8022EED4);
RUNTIME_PPC_JUMP_LABEL(.L_8022EEC8, 0x8022EEC8) //this is a jump label
/*8022EEC8 0022BCC8*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EECC 0022BCCC*/ PPC::Runtime::ASM::beq(.L_8022EED4);
/*8022EED0 0022BCD0*/ PPC::Runtime::ASM::li(context->r6, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EED4, 0x8022EED4) //this is a jump label
/*8022EED4 0022BCD4*/ PPC::Runtime::ASM::slwi(context->r0, context->r6, 2);
/*8022EED8 0022BCD8*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x364, context->r8));
/*8022EEDC 0022BCDC*/ PPC::Runtime::ASM::lwzx(context->r0, context->r4, context->r0);
/*8022EEE0 0022BCE0*/ PPC::Runtime::ASM::cmpw(context->r5, context->r0);
/*8022EEE4 0022BCE4*/ PPC::Runtime::ASM::bne(.L_8022EEF0);
/*8022EEE8 0022BCE8*/ PPC::Runtime::ASM::addi(context->r6, context->r6, 0x1);
/*8022EEEC 0022BCEC*/ PPC::Runtime::ASM::b(.L_8022EEFC);
RUNTIME_PPC_JUMP_LABEL(.L_8022EEF0, 0x8022EEF0) //this is a jump label
/*8022EEF0 0022BCF0*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EEF4 0022BCF4*/ PPC::Runtime::ASM::beq(.L_8022EEFC);
/*8022EEF8 0022BCF8*/ PPC::Runtime::ASM::li(context->r6, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EEFC, 0x8022EEFC) //this is a jump label
/*8022EEFC 0022BCFC*/ PPC::Runtime::ASM::slwi(context->r0, context->r6, 2);
/*8022EF00 0022BD00*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x368, context->r8));
/*8022EF04 0022BD04*/ PPC::Runtime::ASM::lwzx(context->r0, context->r4, context->r0);
/*8022EF08 0022BD08*/ PPC::Runtime::ASM::cmpw(context->r5, context->r0);
/*8022EF0C 0022BD0C*/ PPC::Runtime::ASM::bne(.L_8022EF18);
/*8022EF10 0022BD10*/ PPC::Runtime::ASM::addi(context->r6, context->r6, 0x1);
/*8022EF14 0022BD14*/ PPC::Runtime::ASM::b(.L_8022EF24);
RUNTIME_PPC_JUMP_LABEL(.L_8022EF18, 0x8022EF18) //this is a jump label
/*8022EF18 0022BD18*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EF1C 0022BD1C*/ PPC::Runtime::ASM::beq(.L_8022EF24);
/*8022EF20 0022BD20*/ PPC::Runtime::ASM::li(context->r6, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EF24, 0x8022EF24) //this is a jump label
/*8022EF24 0022BD24*/ PPC::Runtime::ASM::addi(context->r8, context->r8, 0xc);
/*8022EF28 0022BD28*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x2);
/*8022EF2C 0022BD2C*/ PPC::Runtime::ASM::bdnz(.L_8022EEAC);
/*8022EF30 0022BD30*/ PPC::Runtime::ASM::lis(context->r4, lbl_804B4C20 @ Get_MemoryOffset_HighBit);
/*8022EF34 0022BD34*/ PPC::Runtime::ASM::slwi(context->r0, context->r6, 2);
/*8022EF38 0022BD38*/ PPC::Runtime::ASM::addi(context->r4, context->r4, lbl_804B4C20 @ Get_MemoryOffset_LowBit);
/*8022EF3C 0022BD3C*/ PPC::Runtime::ASM::lwzx(context->r0, context->r4, context->r0);
/*8022EF40 0022BD40*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EF44 0022BD44*/ PPC::Runtime::ASM::bne(.L_8022EF58);
/*8022EF48 0022BD48*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
/*8022EF4C 0022BD4C*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*8022EF50 0022BD50*/ PPC::Runtime::ASM::rlwimi(context->r0, context->r4, 2, 29, 29);
/*8022EF54 0022BD54*/ PPC::Runtime::ASM::stb(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_8022EF58, 0x8022EF58) //this is a jump label
/*8022EF58 0022BD58*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*8022EF5C 0022BD5C*/ PPC::Runtime::ASM::lis(context->r4, lbl_804B4C20 @ Get_MemoryOffset_HighBit);
/*8022EF60 0022BD60*/ PPC::Runtime::ASM::li(context->r0, 0x2);
/*8022EF64 0022BD64*/ PPC::Runtime::ASM::mr(context->r9, context->r3);
/*8022EF68 0022BD68*/ PPC::Runtime::ASM::mr(context->r8, context->r7);
/*8022EF6C 0022BD6C*/ PPC::Runtime::ASM::addi(context->r5, context->r4, lbl_804B4C20 @ Get_MemoryOffset_LowBit);
/*8022EF70 0022BD70*/ PPC::Runtime::ASM::mtctr(context->r0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EF74, 0x8022EF74) //this is a jump label
/*8022EF74 0022BD74*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022EF78 0022BD78*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x360, context->r9));
/*8022EF7C 0022BD7C*/ PPC::Runtime::ASM::add(context->r4, context->r5, context->r0);
/*8022EF80 0022BD80*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r4));
/*8022EF84 0022BD84*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022EF88 0022BD88*/ PPC::Runtime::ASM::bne(.L_8022EF94);
/*8022EF8C 0022BD8C*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x1);
/*8022EF90 0022BD90*/ PPC::Runtime::ASM::b(.L_8022EFA0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EF94, 0x8022EF94) //this is a jump label
/*8022EF94 0022BD94*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EF98 0022BD98*/ PPC::Runtime::ASM::beq(.L_8022EFA0);
/*8022EF9C 0022BD9C*/ PPC::Runtime::ASM::li(context->r7, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EFA0, 0x8022EFA0) //this is a jump label
/*8022EFA0 0022BDA0*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022EFA4 0022BDA4*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x364, context->r9));
/*8022EFA8 0022BDA8*/ PPC::Runtime::ASM::add(context->r4, context->r5, context->r0);
/*8022EFAC 0022BDAC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r4));
/*8022EFB0 0022BDB0*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022EFB4 0022BDB4*/ PPC::Runtime::ASM::bne(.L_8022EFC0);
/*8022EFB8 0022BDB8*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x1);
/*8022EFBC 0022BDBC*/ PPC::Runtime::ASM::b(.L_8022EFCC);
RUNTIME_PPC_JUMP_LABEL(.L_8022EFC0, 0x8022EFC0) //this is a jump label
/*8022EFC0 0022BDC0*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EFC4 0022BDC4*/ PPC::Runtime::ASM::beq(.L_8022EFCC);
/*8022EFC8 0022BDC8*/ PPC::Runtime::ASM::li(context->r7, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EFCC, 0x8022EFCC) //this is a jump label
/*8022EFCC 0022BDCC*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022EFD0 0022BDD0*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x368, context->r9));
/*8022EFD4 0022BDD4*/ PPC::Runtime::ASM::add(context->r4, context->r5, context->r0);
/*8022EFD8 0022BDD8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r4));
/*8022EFDC 0022BDDC*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022EFE0 0022BDE0*/ PPC::Runtime::ASM::bne(.L_8022EFEC);
/*8022EFE4 0022BDE4*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x1);
/*8022EFE8 0022BDE8*/ PPC::Runtime::ASM::b(.L_8022EFF8);
RUNTIME_PPC_JUMP_LABEL(.L_8022EFEC, 0x8022EFEC) //this is a jump label
/*8022EFEC 0022BDEC*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022EFF0 0022BDF0*/ PPC::Runtime::ASM::beq(.L_8022EFF8);
/*8022EFF4 0022BDF4*/ PPC::Runtime::ASM::li(context->r7, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022EFF8, 0x8022EFF8) //this is a jump label
/*8022EFF8 0022BDF8*/ PPC::Runtime::ASM::addi(context->r9, context->r9, 0xc);
/*8022EFFC 0022BDFC*/ PPC::Runtime::ASM::addi(context->r8, context->r8, 0x2);
/*8022F000 0022BE00*/ PPC::Runtime::ASM::bdnz(.L_8022EF74);
/*8022F004 0022BE04*/ PPC::Runtime::ASM::lis(context->r4, lbl_804B4C20 @ Get_MemoryOffset_HighBit);
/*8022F008 0022BE08*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022F00C 0022BE0C*/ PPC::Runtime::ASM::addi(context->r4, context->r4, lbl_804B4C20 @ Get_MemoryOffset_LowBit);
/*8022F010 0022BE10*/ PPC::Runtime::ASM::add(context->r4, context->r4, context->r0);
/*8022F014 0022BE14*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r4));
/*8022F018 0022BE18*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022F01C 0022BE1C*/ PPC::Runtime::ASM::bne(.L_8022F030);
/*8022F020 0022BE20*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
/*8022F024 0022BE24*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*8022F028 0022BE28*/ PPC::Runtime::ASM::rlwimi(context->r0, context->r4, 1, 30, 30);
/*8022F02C 0022BE2C*/ PPC::Runtime::ASM::stb(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_8022F030, 0x8022F030) //this is a jump label
/*8022F030 0022BE30*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*8022F034 0022BE34*/ PPC::Runtime::ASM::lis(context->r4, lbl_804B4C20 @ Get_MemoryOffset_HighBit);
/*8022F038 0022BE38*/ PPC::Runtime::ASM::li(context->r0, 0x2);
/*8022F03C 0022BE3C*/ PPC::Runtime::ASM::mr(context->r9, context->r3);
/*8022F040 0022BE40*/ PPC::Runtime::ASM::mr(context->r8, context->r7);
/*8022F044 0022BE44*/ PPC::Runtime::ASM::addi(context->r5, context->r4, lbl_804B4C20 @ Get_MemoryOffset_LowBit);
/*8022F048 0022BE48*/ PPC::Runtime::ASM::mtctr(context->r0);
RUNTIME_PPC_JUMP_LABEL(.L_8022F04C, 0x8022F04C) //this is a jump label
/*8022F04C 0022BE4C*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022F050 0022BE50*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x360, context->r9));
/*8022F054 0022BE54*/ PPC::Runtime::ASM::add(context->r4, context->r5, context->r0);
/*8022F058 0022BE58*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r4));
/*8022F05C 0022BE5C*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022F060 0022BE60*/ PPC::Runtime::ASM::bne(.L_8022F06C);
/*8022F064 0022BE64*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x1);
/*8022F068 0022BE68*/ PPC::Runtime::ASM::b(.L_8022F078);
RUNTIME_PPC_JUMP_LABEL(.L_8022F06C, 0x8022F06C) //this is a jump label
/*8022F06C 0022BE6C*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022F070 0022BE70*/ PPC::Runtime::ASM::beq(.L_8022F078);
/*8022F074 0022BE74*/ PPC::Runtime::ASM::li(context->r7, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022F078, 0x8022F078) //this is a jump label
/*8022F078 0022BE78*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022F07C 0022BE7C*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x364, context->r9));
/*8022F080 0022BE80*/ PPC::Runtime::ASM::add(context->r4, context->r5, context->r0);
/*8022F084 0022BE84*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r4));
/*8022F088 0022BE88*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022F08C 0022BE8C*/ PPC::Runtime::ASM::bne(.L_8022F098);
/*8022F090 0022BE90*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x1);
/*8022F094 0022BE94*/ PPC::Runtime::ASM::b(.L_8022F0A4);
RUNTIME_PPC_JUMP_LABEL(.L_8022F098, 0x8022F098) //this is a jump label
/*8022F098 0022BE98*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022F09C 0022BE9C*/ PPC::Runtime::ASM::beq(.L_8022F0A4);
/*8022F0A0 0022BEA0*/ PPC::Runtime::ASM::li(context->r7, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022F0A4, 0x8022F0A4) //this is a jump label
/*8022F0A4 0022BEA4*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022F0A8 0022BEA8*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x368, context->r9));
/*8022F0AC 0022BEAC*/ PPC::Runtime::ASM::add(context->r4, context->r5, context->r0);
/*8022F0B0 0022BEB0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r4));
/*8022F0B4 0022BEB4*/ PPC::Runtime::ASM::cmpw(context->r6, context->r0);
/*8022F0B8 0022BEB8*/ PPC::Runtime::ASM::bne(.L_8022F0C4);
/*8022F0BC 0022BEBC*/ PPC::Runtime::ASM::addi(context->r7, context->r7, 0x1);
/*8022F0C0 0022BEC0*/ PPC::Runtime::ASM::b(.L_8022F0D0);
RUNTIME_PPC_JUMP_LABEL(.L_8022F0C4, 0x8022F0C4) //this is a jump label
/*8022F0C4 0022BEC4*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022F0C8 0022BEC8*/ PPC::Runtime::ASM::beq(.L_8022F0D0);
/*8022F0CC 0022BECC*/ PPC::Runtime::ASM::li(context->r7, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022F0D0, 0x8022F0D0) //this is a jump label
/*8022F0D0 0022BED0*/ PPC::Runtime::ASM::addi(context->r9, context->r9, 0xc);
/*8022F0D4 0022BED4*/ PPC::Runtime::ASM::addi(context->r8, context->r8, 0x2);
/*8022F0D8 0022BED8*/ PPC::Runtime::ASM::bdnz(.L_8022F04C);
/*8022F0DC 0022BEDC*/ PPC::Runtime::ASM::lis(context->r4, lbl_804B4C20 @ Get_MemoryOffset_HighBit);
/*8022F0E0 0022BEE0*/ PPC::Runtime::ASM::slwi(context->r0, context->r7, 2);
/*8022F0E4 0022BEE4*/ PPC::Runtime::ASM::addi(context->r4, context->r4, lbl_804B4C20 @ Get_MemoryOffset_LowBit);
/*8022F0E8 0022BEE8*/ PPC::Runtime::ASM::add(context->r4, context->r4, context->r0);
/*8022F0EC 0022BEEC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r4));
/*8022F0F0 0022BEF0*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xb);
/*8022F0F4 0022BEF4*/ PPC::Runtime::ASM::bne(.L_8022F108);
/*8022F0F8 0022BEF8*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
/*8022F0FC 0022BEFC*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*8022F100 0022BF00*/ PPC::Runtime::ASM::rlwimi(context->r0, context->r4, 0, 31, 31);
/*8022F104 0022BF04*/ PPC::Runtime::ASM::stb(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x378, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_8022F108, 0x8022F108) //this is a jump label
/*8022F108 0022BF08*/ PPC::Runtime::ASM::slwi(context->r0, context->r31, 2);
/*8022F10C 0022BF0C*/ PPC::Runtime::ASM::add(context->r5, context->r3, context->r0);
/*8022F110 0022BF10*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x334, context->r5));
/*8022F114 0022BF14*/ PPC::Runtime::ASM::addi(context->r0, context->r4, 0x1);
/*8022F118 0022BF18*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x334, context->r5));
/*8022F11C 0022BF1C*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x855, context->r3));
/* 8022F120 0022BF20  54 00 D7 FF */ extrwi. context->r0 , context->r0 , 1 , 25
/*8022F124 0022BF24*/ PPC::Runtime::ASM::bne(.L_8022F13C);
/*8022F128 0022BF28*/ PPC::Runtime::ASM::cmpwi(context->r31, 0x2);
/*8022F12C 0022BF2C*/ PPC::Runtime::ASM::bne(.L_8022F13C);
/*8022F130 0022BF30*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x7dc, context->r3));
/*8022F134 0022BF34*/ PPC::Runtime::ASM::addi(context->r0, context->r4, 0x1);
/*8022F138 0022BF38*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x7dc, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_8022F13C, 0x8022F13C) //this is a jump label
/*8022F13C 0022BF3C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8022F140 0022BF40*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*8022F144 0022BF44*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8022F148 0022BF48*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*8022F14C 0022BF4C*/ PPC::Runtime::ASM::blr();
}