//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_8027EF64(PPC::Runtime::GCContext* context)
{
/*8027EF64 0027BD64*/ PPC::Runtime::ASM::lwz(context->r3, STRUCT_BYTE4_COUNT_1805DD910 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*8027EF68 0027BD68*/ PPC::Runtime::ASM::blr();
}