//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_8019411C(PPC::Runtime::GCContext* context)
{
/*8019411C 00190F1C*/ PPC::Runtime::ASM::blr();
}