//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_802AA930.hpp"



void fn_802B4054(PPC::Runtime::GCContext* context)
{
/*802B4054 002B0E54*/ PPC::Runtime::ASM::subi(context->r3, context->r3, 0x38);
/*802B4058 002B0E58*/ PPC::Runtime::ASM::b(fn_802AA930);
}