//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_801D96AC.hpp"
#include "fn_801F620C.hpp"



void fn_801F6F18(PPC::Runtime::GCContext* context)
{
/*801F6F18 001F3D18*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*801F6F1C 001F3D1C*/ PPC::Runtime::ASM::mflr(context->r0);
/*801F6F20 001F3D20*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801F6F24 001F3D24*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*801F6F28 001F3D28*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*801F6F2C 001F3D2C*/ PPC::Runtime::ASM::bl(fn_801D96AC);
/*801F6F30 001F3D30*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801F6F34 001F3D34*/ PPC::Runtime::ASM::bl(fn_801F620C);
/*801F6F38 001F3D38*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801F6F3C 001F3D3C*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*801F6F40 001F3D40*/ PPC::Runtime::ASM::mtlr(context->r0);
/*801F6F44 001F3D44*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*801F6F48 001F3D48*/ PPC::Runtime::ASM::blr();
}