//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80178250.hpp"
#include "fn_JObj_GetWorldPosition.hpp"



void fn_801794B0(PPC::Runtime::GCContext* context)
{
/*801794B0 001762B0*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x30, context->r1));
/*801794B4 001762B4*/ PPC::Runtime::ASM::mflr(context->r0);
/*801794B8 001762B8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*801794BC 001762BC*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r1));
/*801794C0 001762C0*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*801794C4 001762C4*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*801794C8 001762C8*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*801794CC 001762CC*/ PPC::Runtime::ASM::mr(context->r28, context->r3);
/*801794D0 001762D0*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r3));
/*801794D4 001762D4*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r3));
/*801794D8 001762D8*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*801794DC 001762DC*/ PPC::Runtime::ASM::bl(fn_HSD_JObjAnimAll?);
/*801794E0 001762E0*/ PPC::Runtime::ASM::lbz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r29));
/*801794E4 001762E4*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0x8);
/*801794E8 001762E8*/ PPC::Runtime::ASM::lbz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xd, context->r29));
/*801794EC 001762EC*/ PPC::Runtime::ASM::bl(fn_80178250);
/*801794F0 001762F0*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*801794F4 001762F4*/ PPC::Runtime::ASM::bne(.L_80179508);
/*801794F8 001762F8*/ PPC::Runtime::ASM::li(context->r3, lbl_805D6D78 @ Get_MemoryOffset_SDA21);
/*801794FC 001762FC*/ PPC::Runtime::ASM::li(context->r4, 0x3a9);
/*80179500 00176300*/ PPC::Runtime::ASM::li(context->r5, lbl_805D6D80 @ Get_MemoryOffset_SDA21);
/*80179504 00176304*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_80179508, 0x80179508) //this is a jump label
/*80179508 00176308*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*8017950C 0017630C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*80179510 00176310*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r30));
/*80179514 00176314*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r30));
/*80179518 00176318*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*8017951C 0017631C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r30));
/*80179520 00176320*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*80179524 00176324*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 6, 6);
/*80179528 00176328*/ PPC::Runtime::ASM::bne(.L_80179574);
/*8017952C 0017632C*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*80179530 00176330*/ PPC::Runtime::ASM::beq(.L_80179574);
/*80179534 00176334*/ PPC::Runtime::ASM::bne(.L_80179548);
/*80179538 00176338*/ PPC::Runtime::ASM::li(context->r3, lbl_805D6D78 @ Get_MemoryOffset_SDA21);
/*8017953C 0017633C*/ PPC::Runtime::ASM::li(context->r4, 0x25d);
/*80179540 00176340*/ PPC::Runtime::ASM::li(context->r5, lbl_805D6D80 @ Get_MemoryOffset_SDA21);
/*80179544 00176344*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_80179548, 0x80179548) //this is a jump label
/*80179548 00176348*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r30));
/*8017954C 0017634C*/ PPC::Runtime::ASM::li(context->r3, 0x0);
/*80179550 00176350*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r4, 0, 8, 8);
/*80179554 00176354*/ PPC::Runtime::ASM::bne(.L_80179564);
/*80179558 00176358*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r4, 0, 25, 25);
/*8017955C 0017635C*/ PPC::Runtime::ASM::beq(.L_80179564);
/*80179560 00176360*/ PPC::Runtime::ASM::li(context->r3, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_80179564, 0x80179564) //this is a jump label
/*80179564 00176364*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*80179568 00176368*/ PPC::Runtime::ASM::bne(.L_80179574);
/*8017956C 0017636C*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*80179570 00176370*/ PPC::Runtime::ASM::bl(fn_HSD_JOBJ_SetMtxDirtySub);
RUNTIME_PPC_JUMP_LABEL(.L_80179574, 0x80179574) //this is a jump label
/*80179574 00176374*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r28));
/*80179578 00176378*/ PPC::Runtime::ASM::li(context->r31, 0x0);
/*8017957C 0017637C*/ PPC::Runtime::ASM::mr(context->r29, context->r30);
RUNTIME_PPC_JUMP_LABEL(.L_80179580, 0x80179580) //this is a jump label
/*80179580 00176380*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r29));
/*80179584 00176384*/ PPC::Runtime::ASM::addi(context->r5, context->r30, 0x34);
/*80179588 00176388*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*8017958C 0017638C*/ PPC::Runtime::ASM::bl(fn_JObj_GetWorldPosition);
/*80179590 00176390*/ PPC::Runtime::ASM::addi(context->r31, context->r31, 0x1);
/*80179594 00176394*/ PPC::Runtime::ASM::addi(context->r29, context->r29, 0x4);
/*80179598 00176398*/ PPC::Runtime::ASM::cmpwi(context->r31, 0x5);
/*8017959C 0017639C*/ PPC::Runtime::ASM::addi(context->r30, context->r30, 0xc);
/*801795A0 001763A0*/ PPC::Runtime::ASM::blt(.L_80179580);
/*801795A4 001763A4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r28));
/*801795A8 001763A8*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r3));
/*801795AC 001763AC*/ PPC::Runtime::ASM::addi(context->r30, context->r3, 0x28);
/*801795B0 001763B0*/ PPC::Runtime::ASM::cmplwi(context->r31, 0x0);
/*801795B4 001763B4*/ PPC::Runtime::ASM::bne(.L_801795C8);
/*801795B8 001763B8*/ PPC::Runtime::ASM::li(context->r3, lbl_805D6D78 @ Get_MemoryOffset_SDA21);
/*801795BC 001763BC*/ PPC::Runtime::ASM::li(context->r4, 0x351);
/*801795C0 001763C0*/ PPC::Runtime::ASM::li(context->r5, lbl_805D6D80 @ Get_MemoryOffset_SDA21);
/*801795C4 001763C4*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_801795C8, 0x801795C8) //this is a jump label
/*801795C8 001763C8*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*801795CC 001763CC*/ PPC::Runtime::ASM::bne(.L_801795E0);
/*801795D0 001763D0*/ PPC::Runtime::ASM::li(context->r3, lbl_805D6D78 @ Get_MemoryOffset_SDA21);
/*801795D4 001763D4*/ PPC::Runtime::ASM::li(context->r4, 0x352);
/*801795D8 001763D8*/ PPC::Runtime::ASM::li(context->r5, lbl_805D6D88 @ Get_MemoryOffset_SDA21);
/*801795DC 001763DC*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_801795E0, 0x801795E0) //this is a jump label
/*801795E0 001763E0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r31));
/*801795E4 001763E4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r31));
/*801795E8 001763E8*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*801795EC 001763EC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r30));
/*801795F0 001763F0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r31));
/*801795F4 001763F4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r30));
/*801795F8 001763F8*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r1));
/*801795FC 001763FC*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*80179600 00176400*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*80179604 00176404*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*80179608 00176408*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*8017960C 0017640C*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80179610 00176410*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x30);
/*80179614 00176414*/ PPC::Runtime::ASM::blr();
}