//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802AFECC.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802AFECC.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A1C.hpp"
#include "fn_802AFF5C.hpp"
#include "fn_802B0A18.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802AFECC.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0598.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802B0A4C.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A20.hpp"
#include "fn_802B0AB4.hpp"
#include "fn_802AFECC.hpp"
#include "fn_802B0A44.hpp"
#include "fn_802B0A1C.hpp"
#include "fn_802AFF5C.hpp"
#include "fn_802B0A18.hpp"
#include "fn_802B0A14.hpp"
#include "fn_802B0A14.hpp"
#include "fn_802B3B74.hpp"



void fn_802B0598(PPC::Runtime::GCContext* context)
{
/*802B0598 002AD398*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x30, context->r1));
/*802B059C 002AD39C*/ PPC::Runtime::ASM::mflr(context->r0);
/*802B05A0 002AD3A0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*802B05A4 002AD3A4*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*802B05A8 002AD3A8*/ PPC::Runtime::ASM::bl(_savegpr_27);
/*802B05AC 002AD3AC*/ PPC::Runtime::ASM::mr(context->r30, context->r4);
/*802B05B0 002AD3B0*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*802B05B4 002AD3B4*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*802B05B8 002AD3B8*/ PPC::Runtime::ASM::cmplwi(context->r29, 0x0);
/*802B05BC 002AD3BC*/ PPC::Runtime::ASM::beq(.L_802B07A8);
/*802B05C0 002AD3C0*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*802B05C4 002AD3C4*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B05C8 002AD3C8*/ PPC::Runtime::ASM::beq(.L_802B069C);
/*802B05CC 002AD3CC*/ PPC::Runtime::ASM::lwz(context->r27, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B05D0 002AD3D0*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*802B05D4 002AD3D4*/ PPC::Runtime::ASM::beq(.L_802B0620);
/*802B05D8 002AD3D8*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*802B05DC 002AD3DC*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B05E0 002AD3E0*/ PPC::Runtime::ASM::beq(.L_802B05E8);
/*802B05E4 002AD3E4*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B05E8, 0x802B05E8) //this is a jump label
/*802B05E8 002AD3E8*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r27));
/*802B05EC 002AD3EC*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B05F0 002AD3F0*/ PPC::Runtime::ASM::beq(.L_802B05FC);
/*802B05F4 002AD3F4*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B05F8 002AD3F8*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B05FC, 0x802B05FC) //this is a jump label
/*802B05FC 002AD3FC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0600 002AD400*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0604 002AD404*/ PPC::Runtime::ASM::addi(context->r4, context->r27, 0xc);
/*802B0608 002AD408*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B060C 002AD40C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0610 002AD410*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B0614 002AD414*/ PPC::Runtime::ASM::mr(context->r4, context->r27);
/*802B0618 002AD418*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B061C 002AD41C*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0620, 0x802B0620) //this is a jump label
/*802B0620 002AD420*/ PPC::Runtime::ASM::lwz(context->r27, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B0624 002AD424*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*802B0628 002AD428*/ PPC::Runtime::ASM::beq(.L_802B0678);
/*802B062C 002AD42C*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*802B0630 002AD430*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B0634 002AD434*/ PPC::Runtime::ASM::beq(.L_802B0640);
/*802B0638 002AD438*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B063C 002AD43C*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B0640, 0x802B0640) //this is a jump label
/*802B0640 002AD440*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r27));
/*802B0644 002AD444*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B0648 002AD448*/ PPC::Runtime::ASM::beq(.L_802B0654);
/*802B064C 002AD44C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0650 002AD450*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B0654, 0x802B0654) //this is a jump label
/*802B0654 002AD454*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0658 002AD458*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B065C 002AD45C*/ PPC::Runtime::ASM::addi(context->r4, context->r27, 0xc);
/*802B0660 002AD460*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B0664 002AD464*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0668 002AD468*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B066C 002AD46C*/ PPC::Runtime::ASM::mr(context->r4, context->r27);
/*802B0670 002AD470*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B0674 002AD474*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0678, 0x802B0678) //this is a jump label
/*802B0678 002AD478*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B067C 002AD47C*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0680 002AD480*/ PPC::Runtime::ASM::addi(context->r3, context->r28, 0xc);
/*802B0684 002AD484*/ PPC::Runtime::ASM::li(context->r4, -0x1);
/*802B0688 002AD488*/ PPC::Runtime::ASM::bl(fn_802AFECC);
/*802B068C 002AD48C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0690 002AD490*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B0694 002AD494*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*802B0698 002AD498*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_802B069C, 0x802B069C) //this is a jump label
/*802B069C 002AD49C*/ PPC::Runtime::ASM::lwz(context->r27, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r29));
/*802B06A0 002AD4A0*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*802B06A4 002AD4A4*/ PPC::Runtime::ASM::beq(.L_802B077C);
/*802B06A8 002AD4A8*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*802B06AC 002AD4AC*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B06B0 002AD4B0*/ PPC::Runtime::ASM::beq(.L_802B0700);
/*802B06B4 002AD4B4*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B06B8 002AD4B8*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B06BC 002AD4BC*/ PPC::Runtime::ASM::beq(.L_802B06C8);
/*802B06C0 002AD4C0*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B06C4 002AD4C4*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B06C8, 0x802B06C8) //this is a jump label
/*802B06C8 002AD4C8*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B06CC 002AD4CC*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B06D0 002AD4D0*/ PPC::Runtime::ASM::beq(.L_802B06DC);
/*802B06D4 002AD4D4*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B06D8 002AD4D8*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B06DC, 0x802B06DC) //this is a jump label
/*802B06DC 002AD4DC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B06E0 002AD4E0*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B06E4 002AD4E4*/ PPC::Runtime::ASM::addi(context->r4, context->r28, 0xc);
/*802B06E8 002AD4E8*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B06EC 002AD4EC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B06F0 002AD4F0*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B06F4 002AD4F4*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*802B06F8 002AD4F8*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B06FC 002AD4FC*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0700, 0x802B0700) //this is a jump label
/*802B0700 002AD500*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r27));
/*802B0704 002AD504*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B0708 002AD508*/ PPC::Runtime::ASM::beq(.L_802B0758);
/*802B070C 002AD50C*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B0710 002AD510*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B0714 002AD514*/ PPC::Runtime::ASM::beq(.L_802B0720);
/*802B0718 002AD518*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B071C 002AD51C*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B0720, 0x802B0720) //this is a jump label
/*802B0720 002AD520*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B0724 002AD524*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B0728 002AD528*/ PPC::Runtime::ASM::beq(.L_802B0734);
/*802B072C 002AD52C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0730 002AD530*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B0734, 0x802B0734) //this is a jump label
/*802B0734 002AD534*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0738 002AD538*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B073C 002AD53C*/ PPC::Runtime::ASM::addi(context->r4, context->r28, 0xc);
/*802B0740 002AD540*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B0744 002AD544*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0748 002AD548*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B074C 002AD54C*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*802B0750 002AD550*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B0754 002AD554*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0758, 0x802B0758) //this is a jump label
/*802B0758 002AD558*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B075C 002AD55C*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0760 002AD560*/ PPC::Runtime::ASM::addi(context->r3, context->r27, 0xc);
/*802B0764 002AD564*/ PPC::Runtime::ASM::li(context->r4, -0x1);
/*802B0768 002AD568*/ PPC::Runtime::ASM::bl(fn_802AFECC);
/*802B076C 002AD56C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0770 002AD570*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B0774 002AD574*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*802B0778 002AD578*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_802B077C, 0x802B077C) //this is a jump label
/*802B077C 002AD57C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0780 002AD580*/ PPC::Runtime::ASM::bl(fn_802B0A1C);
/*802B0784 002AD584*/ PPC::Runtime::ASM::addic.(context->r0, context->r29, 0xc);
/*802B0788 002AD588*/ PPC::Runtime::ASM::beq(.L_802B0798);
/*802B078C 002AD58C*/ PPC::Runtime::ASM::addi(context->r3, context->r29, 0x10);
/*802B0790 002AD590*/ PPC::Runtime::ASM::li(context->r4, -0x1);
/*802B0794 002AD594*/ PPC::Runtime::ASM::bl(fn_802AFF5C);
RUNTIME_PPC_JUMP_LABEL(.L_802B0798, 0x802B0798) //this is a jump label
/*802B0798 002AD598*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x4);
/*802B079C 002AD59C*/ PPC::Runtime::ASM::bl(fn_802B0A18);
/*802B07A0 002AD5A0*/ PPC::Runtime::ASM::mr(context->r3, context->r29);
/*802B07A4 002AD5A4*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_802B07A8, 0x802B07A8) //this is a jump label
/*802B07A8 002AD5A8*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r30));
/*802B07AC 002AD5AC*/ PPC::Runtime::ASM::cmplwi(context->r29, 0x0);
/*802B07B0 002AD5B0*/ PPC::Runtime::ASM::beq(.L_802B09A0);
/*802B07B4 002AD5B4*/ PPC::Runtime::ASM::lwz(context->r27, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*802B07B8 002AD5B8*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*802B07BC 002AD5BC*/ PPC::Runtime::ASM::beq(.L_802B0894);
/*802B07C0 002AD5C0*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*802B07C4 002AD5C4*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B07C8 002AD5C8*/ PPC::Runtime::ASM::beq(.L_802B0818);
/*802B07CC 002AD5CC*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B07D0 002AD5D0*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B07D4 002AD5D4*/ PPC::Runtime::ASM::beq(.L_802B07E0);
/*802B07D8 002AD5D8*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B07DC 002AD5DC*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B07E0, 0x802B07E0) //this is a jump label
/*802B07E0 002AD5E0*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B07E4 002AD5E4*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B07E8 002AD5E8*/ PPC::Runtime::ASM::beq(.L_802B07F4);
/*802B07EC 002AD5EC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B07F0 002AD5F0*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B07F4, 0x802B07F4) //this is a jump label
/*802B07F4 002AD5F4*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B07F8 002AD5F8*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B07FC 002AD5FC*/ PPC::Runtime::ASM::addi(context->r4, context->r28, 0xc);
/*802B0800 002AD600*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B0804 002AD604*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0808 002AD608*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B080C 002AD60C*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*802B0810 002AD610*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B0814 002AD614*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0818, 0x802B0818) //this is a jump label
/*802B0818 002AD618*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r27));
/*802B081C 002AD61C*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B0820 002AD620*/ PPC::Runtime::ASM::beq(.L_802B0870);
/*802B0824 002AD624*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B0828 002AD628*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B082C 002AD62C*/ PPC::Runtime::ASM::beq(.L_802B0838);
/*802B0830 002AD630*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0834 002AD634*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B0838, 0x802B0838) //this is a jump label
/*802B0838 002AD638*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B083C 002AD63C*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B0840 002AD640*/ PPC::Runtime::ASM::beq(.L_802B084C);
/*802B0844 002AD644*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0848 002AD648*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B084C, 0x802B084C) //this is a jump label
/*802B084C 002AD64C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0850 002AD650*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0854 002AD654*/ PPC::Runtime::ASM::addi(context->r4, context->r28, 0xc);
/*802B0858 002AD658*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B085C 002AD65C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0860 002AD660*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B0864 002AD664*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*802B0868 002AD668*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B086C 002AD66C*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0870, 0x802B0870) //this is a jump label
/*802B0870 002AD670*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0874 002AD674*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0878 002AD678*/ PPC::Runtime::ASM::addi(context->r3, context->r27, 0xc);
/*802B087C 002AD67C*/ PPC::Runtime::ASM::li(context->r4, -0x1);
/*802B0880 002AD680*/ PPC::Runtime::ASM::bl(fn_802AFECC);
/*802B0884 002AD684*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0888 002AD688*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B088C 002AD68C*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*802B0890 002AD690*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_802B0894, 0x802B0894) //this is a jump label
/*802B0894 002AD694*/ PPC::Runtime::ASM::lwz(context->r27, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r29));
/*802B0898 002AD698*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*802B089C 002AD69C*/ PPC::Runtime::ASM::beq(.L_802B0974);
/*802B08A0 002AD6A0*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*802B08A4 002AD6A4*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B08A8 002AD6A8*/ PPC::Runtime::ASM::beq(.L_802B08F8);
/*802B08AC 002AD6AC*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B08B0 002AD6B0*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B08B4 002AD6B4*/ PPC::Runtime::ASM::beq(.L_802B08C0);
/*802B08B8 002AD6B8*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B08BC 002AD6BC*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B08C0, 0x802B08C0) //this is a jump label
/*802B08C0 002AD6C0*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B08C4 002AD6C4*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B08C8 002AD6C8*/ PPC::Runtime::ASM::beq(.L_802B08D4);
/*802B08CC 002AD6CC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B08D0 002AD6D0*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B08D4, 0x802B08D4) //this is a jump label
/*802B08D4 002AD6D4*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B08D8 002AD6D8*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B08DC 002AD6DC*/ PPC::Runtime::ASM::addi(context->r4, context->r28, 0xc);
/*802B08E0 002AD6E0*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B08E4 002AD6E4*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B08E8 002AD6E8*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B08EC 002AD6EC*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*802B08F0 002AD6F0*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B08F4 002AD6F4*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B08F8, 0x802B08F8) //this is a jump label
/*802B08F8 002AD6F8*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r27));
/*802B08FC 002AD6FC*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*802B0900 002AD700*/ PPC::Runtime::ASM::beq(.L_802B0950);
/*802B0904 002AD704*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*802B0908 002AD708*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B090C 002AD70C*/ PPC::Runtime::ASM::beq(.L_802B0918);
/*802B0910 002AD710*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0914 002AD714*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B0918, 0x802B0918) //this is a jump label
/*802B0918 002AD718*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r28));
/*802B091C 002AD71C*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*802B0920 002AD720*/ PPC::Runtime::ASM::beq(.L_802B092C);
/*802B0924 002AD724*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0928 002AD728*/ PPC::Runtime::ASM::bl(fn_802B0598);
RUNTIME_PPC_JUMP_LABEL(.L_802B092C, 0x802B092C) //this is a jump label
/*802B092C 002AD72C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0930 002AD730*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0934 002AD734*/ PPC::Runtime::ASM::addi(context->r4, context->r28, 0xc);
/*802B0938 002AD738*/ PPC::Runtime::ASM::bl(fn_802B0A4C);
/*802B093C 002AD73C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0940 002AD740*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B0944 002AD744*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*802B0948 002AD748*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*802B094C 002AD74C*/ PPC::Runtime::ASM::bl(fn_802B0A20);
RUNTIME_PPC_JUMP_LABEL(.L_802B0950, 0x802B0950) //this is a jump label
/*802B0950 002AD750*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0954 002AD754*/ PPC::Runtime::ASM::bl(fn_802B0AB4);
/*802B0958 002AD758*/ PPC::Runtime::ASM::addi(context->r3, context->r27, 0xc);
/*802B095C 002AD75C*/ PPC::Runtime::ASM::li(context->r4, -0x1);
/*802B0960 002AD760*/ PPC::Runtime::ASM::bl(fn_802AFECC);
/*802B0964 002AD764*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0968 002AD768*/ PPC::Runtime::ASM::bl(fn_802B0A44);
/*802B096C 002AD76C*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*802B0970 002AD770*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_802B0974, 0x802B0974) //this is a jump label
/*802B0974 002AD774*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*802B0978 002AD778*/ PPC::Runtime::ASM::bl(fn_802B0A1C);
/*802B097C 002AD77C*/ PPC::Runtime::ASM::addic.(context->r0, context->r29, 0xc);
/*802B0980 002AD780*/ PPC::Runtime::ASM::beq(.L_802B0990);
/*802B0984 002AD784*/ PPC::Runtime::ASM::addi(context->r3, context->r29, 0x10);
/*802B0988 002AD788*/ PPC::Runtime::ASM::li(context->r4, -0x1);
/*802B098C 002AD78C*/ PPC::Runtime::ASM::bl(fn_802AFF5C);
RUNTIME_PPC_JUMP_LABEL(.L_802B0990, 0x802B0990) //this is a jump label
/*802B0990 002AD790*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x4);
/*802B0994 002AD794*/ PPC::Runtime::ASM::bl(fn_802B0A18);
/*802B0998 002AD798*/ PPC::Runtime::ASM::mr(context->r3, context->r29);
/*802B099C 002AD79C*/ PPC::Runtime::ASM::bl(fn_8038CB78);
RUNTIME_PPC_JUMP_LABEL(.L_802B09A0, 0x802B09A0) //this is a jump label
/*802B09A0 002AD7A0*/ PPC::Runtime::ASM::addic.(context->r0, context->r30, 0xc);
/*802B09A4 002AD7A4*/ PPC::Runtime::ASM::beq(.L_802B09F4);
/*802B09A8 002AD7A8*/ PPC::Runtime::ASM::addic.(context->r27, context->r30, 0x10);
/*802B09AC 002AD7AC*/ PPC::Runtime::ASM::beq(.L_802B09F4);
/*802B09B0 002AD7B0*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*802B09B4 002AD7B4*/ PPC::Runtime::ASM::beq(.L_802B09F4);
/*802B09B8 002AD7B8*/ PPC::Runtime::ASM::beq(.L_802B09F4);
/*802B09BC 002AD7BC*/ PPC::Runtime::ASM::beq(.L_802B09F4);
/*802B09C0 002AD7C0*/ PPC::Runtime::ASM::addi(context->r28, context->r27, 0x4);
/*802B09C4 002AD7C4*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*802B09C8 002AD7C8*/ PPC::Runtime::ASM::bl(fn_802B0A14);
/*802B09CC 002AD7CC*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*802B09D0 002AD7D0*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*802B09D4 002AD7D4*/ PPC::Runtime::ASM::bl(fn_802B0A14);
/*802B09D8 002AD7D8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r3));
/*802B09DC 002AD7DC*/ PPC::Runtime::ASM::mr(context->r4, context->r27);
/*802B09E0 002AD7E0*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x8);
/*802B09E4 002AD7E4*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0xc);
/*802B09E8 002AD7E8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*802B09EC 002AD7EC*/ PPC::Runtime::ASM::addi(context->r6, context->r1, 0x10);
/*802B09F0 002AD7F0*/ PPC::Runtime::ASM::bl(fn_802B3B74);
RUNTIME_PPC_JUMP_LABEL(.L_802B09F4, 0x802B09F4) //this is a jump label
/*802B09F4 002AD7F4*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*802B09F8 002AD7F8*/ PPC::Runtime::ASM::bl(fn_8038CB78);
/*802B09FC 002AD7FC*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*802B0A00 002AD800*/ PPC::Runtime::ASM::bl(_restgpr_27);
/*802B0A04 002AD804*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*802B0A08 002AD808*/ PPC::Runtime::ASM::mtlr(context->r0);
/*802B0A0C 002AD80C*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x30);
/*802B0A10 002AD810*/ PPC::Runtime::ASM::blr();
}