//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80190760.hpp"
#include "fn_801907BC.hpp"
#include "fn_8019079C.hpp"



void fn_80190708(PPC::Runtime::GCContext* context)
{
/*80190708 0018D508*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*8019070C 0018D50C*/ PPC::Runtime::ASM::mflr(context->r0);
/*80190710 0018D510*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1088 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80190714 0018D514*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80190718 0018D518*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*8019071C 0018D51C*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*80190720 0018D520*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2e4, context->r3));
/*80190724 0018D524*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2e0, context->r3));
/*80190728 0018D528*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2dc, context->r3));
/*8019072C 0018D52C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5d8, context->r3));
/*80190730 0018D530*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5d4, context->r3));
/*80190734 0018D534*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5d0, context->r3));
/*80190738 0018D538*/ PPC::Runtime::ASM::bl(fn_80190760);
/*8019073C 0018D53C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*80190740 0018D540*/ PPC::Runtime::ASM::bl(fn_801907BC);
/*80190744 0018D544*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*80190748 0018D548*/ PPC::Runtime::ASM::bl(fn_8019079C);
/*8019074C 0018D54C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80190750 0018D550*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*80190754 0018D554*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80190758 0018D558*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*8019075C 0018D55C*/ PPC::Runtime::ASM::blr();
}