//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_801C7EF4.hpp"



void fn_8022C70C(PPC::Runtime::GCContext* context)
{
/*8022C70C 0022950C*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*8022C710 00229510*/ PPC::Runtime::ASM::mflr(context->r0);
/*8022C714 00229514*/ PPC::Runtime::ASM::mulli(context->r4, context->r3, 0x90c);
/*8022C718 00229518*/ PPC::Runtime::ASM::lis(context->r3, STRUCT_BYTE4_COUNT_18055A9F0 @ Get_MemoryOffset_HighBit);
/*8022C71C 0022951C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8022C720 00229520*/ PPC::Runtime::ASM::addi(context->r0, context->r3, STRUCT_BYTE4_COUNT_18055A9F0 @ Get_MemoryOffset_LowBit);
/*8022C724 00229524*/ PPC::Runtime::ASM::add(context->r3, context->r0, context->r4);
/*8022C728 00229528*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r3));
/*8022C72C 0022952C*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*8022C730 00229530*/ PPC::Runtime::ASM::beq(.L_8022C73C);
/*8022C734 00229534*/ PPC::Runtime::ASM::bl(fn_801C7EF4);
/*8022C738 00229538*/ PPC::Runtime::ASM::b(.L_8022C740);
RUNTIME_PPC_JUMP_LABEL(.L_8022C73C, 0x8022C73C) //this is a jump label
/*8022C73C 0022953C*/ PPC::Runtime::ASM::li(context->r3, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8022C740, 0x8022C740) //this is a jump label
/*8022C740 00229540*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8022C744 00229544*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8022C748 00229548*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*8022C74C 0022954C*/ PPC::Runtime::ASM::blr();
}