//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_801FFD78.hpp"



void fn_802111B8(PPC::Runtime::GCContext* context)
{
/*802111B8 0020DFB8*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*802111BC 0020DFBC*/ PPC::Runtime::ASM::mflr(context->r0);
/*802111C0 0020DFC0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*802111C4 0020DFC4*/ PPC::Runtime::ASM::bl(fn_801FFD78);
/*802111C8 0020DFC8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*802111CC 0020DFCC*/ PPC::Runtime::ASM::mtlr(context->r0);
/*802111D0 0020DFD0*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*802111D4 0020DFD4*/ PPC::Runtime::ASM::blr();
}