//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80138AB0.hpp"
#include "fn_8014676C.hpp"
#include "fn_80146704.hpp"
#include "fn_80146738.hpp"
#include "fn_80162F08.hpp"
#include "fn_80163630.hpp"
#include "fn_80163B30.hpp"
#include "fn_80163E74.hpp"
#include "fn_801640D8.hpp"



void fn_80162D84(PPC::Runtime::GCContext* context)
{
/*80162D84 0015FB84*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*80162D88 0015FB88*/ PPC::Runtime::ASM::mflr(context->r0);
/*80162D8C 0015FB8C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80162D90 0015FB90*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r3));
/*80162D94 0015FB94*/ PPC::Runtime::ASM::lbz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r5));
/*80162D98 0015FB98*/ PPC::Runtime::ASM::extsb.(context->r0, context->r4);
/*80162D9C 0015FB9C*/ PPC::Runtime::ASM::ble(.L_80162DD4);
/*80162DA0 0015FBA0*/ PPC::Runtime::ASM::subi(context->r4, context->r4, 0x1);
/*80162DA4 0015FBA4*/ PPC::Runtime::ASM::extsb.(context->r0, context->r4);
/*80162DA8 0015FBA8*/ PPC::Runtime::ASM::stb(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r5));
/*80162DAC 0015FBAC*/ PPC::Runtime::ASM::bgt(.L_80162DD4);
/*80162DB0 0015FBB0*/ PPC::Runtime::ASM::bl(fn_80138AB0);
/*80162DB4 0015FBB4*/ PPC::Runtime::ASM::bl(fn_8014676C);
/*80162DB8 0015FBB8*/ PPC::Runtime::ASM::bl(fn_80146704);
/*80162DBC 0015FBBC*/ PPC::Runtime::ASM::bl(fn_80146738);
/*80162DC0 0015FBC0*/ PPC::Runtime::ASM::bl(fn_80162F08);
/*80162DC4 0015FBC4*/ PPC::Runtime::ASM::bl(fn_80163630);
/*80162DC8 0015FBC8*/ PPC::Runtime::ASM::bl(fn_80163B30);
/*80162DCC 0015FBCC*/ PPC::Runtime::ASM::bl(fn_80163E74);
/*80162DD0 0015FBD0*/ PPC::Runtime::ASM::bl(fn_801640D8);
RUNTIME_PPC_JUMP_LABEL(.L_80162DD4, 0x80162DD4) //this is a jump label
/*80162DD4 0015FBD4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80162DD8 0015FBD8*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80162DDC 0015FBDC*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*80162DE0 0015FBE0*/ PPC::Runtime::ASM::blr();
}