//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_8043F0A4.hpp"



void fn_8043F0A4(PPC::Runtime::GCContext* context)
{
/*8043F0A4 0043BEA4*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x30, context->r1));
/*8043F0A8 0043BEA8*/ PPC::Runtime::ASM::mflr(context->r0);
/*8043F0AC 0043BEAC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*8043F0B0 0043BEB0*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*8043F0B4 0043BEB4*/ PPC::Runtime::ASM::bl(_savegpr_23);
/* 8043F0B8 0043BEB8  7C 7F 1B 79 */ mr. context->r31 , context->r3
/*8043F0BC 0043BEBC*/ PPC::Runtime::ASM::beq(.L_8043F228);
/*8043F0C0 0043BEC0*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r31));
/*8043F0C4 0043BEC4*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*8043F0C8 0043BEC8*/ PPC::Runtime::ASM::beq(.L_8043F210);
/*8043F0CC 0043BECC*/ PPC::Runtime::ASM::beq(.L_8043F210);
/*8043F0D0 0043BED0*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*8043F0D4 0043BED4*/ PPC::Runtime::ASM::cmplwi(context->r29, 0x0);
/*8043F0D8 0043BED8*/ PPC::Runtime::ASM::beq(.L_8043F1F8);
/*8043F0DC 0043BEDC*/ PPC::Runtime::ASM::beq(.L_8043F1F8);
/*8043F0E0 0043BEE0*/ PPC::Runtime::ASM::lwz(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*8043F0E4 0043BEE4*/ PPC::Runtime::ASM::cmplwi(context->r28, 0x0);
/*8043F0E8 0043BEE8*/ PPC::Runtime::ASM::beq(.L_8043F1E0);
/*8043F0EC 0043BEEC*/ PPC::Runtime::ASM::beq(.L_8043F1E0);
/*8043F0F0 0043BEF0*/ PPC::Runtime::ASM::lwz(context->r27, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*8043F0F4 0043BEF4*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x0);
/*8043F0F8 0043BEF8*/ PPC::Runtime::ASM::beq(.L_8043F1C8);
/*8043F0FC 0043BEFC*/ PPC::Runtime::ASM::beq(.L_8043F1C8);
/*8043F100 0043BF00*/ PPC::Runtime::ASM::lwz(context->r26, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*8043F104 0043BF04*/ PPC::Runtime::ASM::cmplwi(context->r26, 0x0);
/*8043F108 0043BF08*/ PPC::Runtime::ASM::beq(.L_8043F1B0);
/*8043F10C 0043BF0C*/ PPC::Runtime::ASM::beq(.L_8043F1B0);
/*8043F110 0043BF10*/ PPC::Runtime::ASM::lwz(context->r25, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r26));
/*8043F114 0043BF14*/ PPC::Runtime::ASM::cmplwi(context->r25, 0x0);
/*8043F118 0043BF18*/ PPC::Runtime::ASM::beq(.L_8043F198);
/*8043F11C 0043BF1C*/ PPC::Runtime::ASM::beq(.L_8043F198);
/*8043F120 0043BF20*/ PPC::Runtime::ASM::lwz(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r25));
/*8043F124 0043BF24*/ PPC::Runtime::ASM::cmplwi(context->r24, 0x0);
/*8043F128 0043BF28*/ PPC::Runtime::ASM::beq(.L_8043F180);
/*8043F12C 0043BF2C*/ PPC::Runtime::ASM::beq(.L_8043F180);
/*8043F130 0043BF30*/ PPC::Runtime::ASM::lwz(context->r23, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r24));
/*8043F134 0043BF34*/ PPC::Runtime::ASM::cmplwi(context->r23, 0x0);
/*8043F138 0043BF38*/ PPC::Runtime::ASM::beq(.L_8043F168);
/*8043F13C 0043BF3C*/ PPC::Runtime::ASM::beq(.L_8043F168);
/*8043F140 0043BF40*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r23));
/*8043F144 0043BF44*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*8043F148 0043BF48*/ PPC::Runtime::ASM::beq(.L_8043F150);
/*8043F14C 0043BF4C*/ PPC::Runtime::ASM::bl(fn_8043F0A4);
RUNTIME_PPC_JUMP_LABEL(.L_8043F150, 0x8043F150) //this is a jump label
/*8043F150 0043BF50*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r23));
/*8043F154 0043BF54*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F158 0043BF58*/ PPC::Runtime::ASM::beq(.L_8043F168);
/*8043F15C 0043BF5C*/ PPC::Runtime::ASM::mr(context->r3, context->r23);
/*8043F160 0043BF60*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F164 0043BF64*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F168, 0x8043F168) //this is a jump label
/*8043F168 0043BF68*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r24));
/*8043F16C 0043BF6C*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F170 0043BF70*/ PPC::Runtime::ASM::beq(.L_8043F180);
/*8043F174 0043BF74*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*8043F178 0043BF78*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F17C 0043BF7C*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F180, 0x8043F180) //this is a jump label
/*8043F180 0043BF80*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r25));
/*8043F184 0043BF84*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F188 0043BF88*/ PPC::Runtime::ASM::beq(.L_8043F198);
/*8043F18C 0043BF8C*/ PPC::Runtime::ASM::mr(context->r3, context->r25);
/*8043F190 0043BF90*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F194 0043BF94*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F198, 0x8043F198) //this is a jump label
/*8043F198 0043BF98*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r26));
/*8043F19C 0043BF9C*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F1A0 0043BFA0*/ PPC::Runtime::ASM::beq(.L_8043F1B0);
/*8043F1A4 0043BFA4*/ PPC::Runtime::ASM::mr(context->r3, context->r26);
/*8043F1A8 0043BFA8*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F1AC 0043BFAC*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F1B0, 0x8043F1B0) //this is a jump label
/*8043F1B0 0043BFB0*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r27));
/*8043F1B4 0043BFB4*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F1B8 0043BFB8*/ PPC::Runtime::ASM::beq(.L_8043F1C8);
/*8043F1BC 0043BFBC*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*8043F1C0 0043BFC0*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F1C4 0043BFC4*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F1C8, 0x8043F1C8) //this is a jump label
/*8043F1C8 0043BFC8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r28));
/*8043F1CC 0043BFCC*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F1D0 0043BFD0*/ PPC::Runtime::ASM::beq(.L_8043F1E0);
/*8043F1D4 0043BFD4*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*8043F1D8 0043BFD8*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F1DC 0043BFDC*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F1E0, 0x8043F1E0) //this is a jump label
/*8043F1E0 0043BFE0*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r29));
/*8043F1E4 0043BFE4*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F1E8 0043BFE8*/ PPC::Runtime::ASM::beq(.L_8043F1F8);
/*8043F1EC 0043BFEC*/ PPC::Runtime::ASM::mr(context->r3, context->r29);
/*8043F1F0 0043BFF0*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F1F4 0043BFF4*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F1F8, 0x8043F1F8) //this is a jump label
/*8043F1F8 0043BFF8*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r30));
/*8043F1FC 0043BFFC*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F200 0043C000*/ PPC::Runtime::ASM::beq(.L_8043F210);
/*8043F204 0043C004*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*8043F208 0043C008*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F20C 0043C00C*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F210, 0x8043F210) //this is a jump label
/*8043F210 0043C010*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r31));
/*8043F214 0043C014*/ PPC::Runtime::ASM::cmplwi(context->r12, 0x0);
/*8043F218 0043C018*/ PPC::Runtime::ASM::beq(.L_8043F228);
/*8043F21C 0043C01C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*8043F220 0043C020*/ PPC::Runtime::ASM::mtctr(context->r12);
/*8043F224 0043C024*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_8043F228, 0x8043F228) //this is a jump label
/*8043F228 0043C028*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*8043F22C 0043C02C*/ PPC::Runtime::ASM::bl(_restgpr_23);
/*8043F230 0043C030*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*8043F234 0043C034*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8043F238 0043C038*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x30);
/*8043F23C 0043C03C*/ PPC::Runtime::ASM::blr();
}