//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_8019A588.hpp"
#include "fn_80064C18.hpp"
#include "fn_80062CA4.hpp"
#include "fn_801B90CC.hpp"
#include "fn_801A29F8.hpp"



void fn_801B9368(PPC::Runtime::GCContext* context)
{
/*801B9368 001B6168*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x60, context->r1));
/*801B936C 001B616C*/ PPC::Runtime::ASM::mflr(context->r0);
/*801B9370 001B6170*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x64, context->r1));
/*801B9374 001B6174*/ PPC::Runtime::ASM::stfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*801B9378 001B6178*/ PPC::Runtime::ASM::psq_st(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1)0, context->qr0);
/*801B937C 001B617C*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*801B9380 001B6180*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*801B9384 001B6184*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xa60);
/*801B9388 001B6188*/ PPC::Runtime::ASM::bl(fn_803D2158);
/*801B938C 001B618C*/ PPC::Runtime::ASM::lfs(context->f2, STRUCT_FLOAT_COUNT_1805E1710 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B9390 001B6190*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f2);
/*801B9394 001B6194*/ PPC::Runtime::ASM::beq(.L_801B9530);
/*801B9398 001B6198*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa54, context->r31));
/*801B939C 001B619C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa58, context->r31));
/*801B93A0 001B61A0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1));
/*801B93A4 001B61A4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa5c, context->r31));
/*801B93A8 001B61A8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1));
/*801B93AC 001B61AC*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*801B93B0 001B61B0*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f2);
/*801B93B4 001B61B4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*801B93B8 001B61B8*/ PPC::Runtime::ASM::beq(.L_801B93C8);
/*801B93BC 001B61BC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38c, context->r31));
/*801B93C0 001B61C0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r3));
/*801B93C4 001B61C4*/ PPC::Runtime::ASM::fmuls(context->f2, context->f1, context->f0);
RUNTIME_PPC_JUMP_LABEL(.L_801B93C8, 0x801B93C8) //this is a jump label
/*801B93C8 001B61C8*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*801B93CC 001B61CC*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1710 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B93D0 001B61D0*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*801B93D4 001B61D4*/ PPC::Runtime::ASM::fcmpu(cr0, context->f3, context->f0);
/*801B93D8 001B61D8*/ PPC::Runtime::ASM::beq(.L_801B93F0);
/*801B93DC 001B61DC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38c, context->r31));
/*801B93E0 001B61E0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r3));
/*801B93E4 001B61E4*/ PPC::Runtime::ASM::fmuls(context->f0, context->f3, context->f0);
/*801B93E8 001B61E8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*801B93EC 001B61EC*/ PPC::Runtime::ASM::b(.L_801B93F4);
RUNTIME_PPC_JUMP_LABEL(.L_801B93F0, 0x801B93F0) //this is a jump label
/*801B93F0 001B61F0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_801B93F4, 0x801B93F4) //this is a jump label
/*801B93F4 001B61F4*/ PPC::Runtime::ASM::lfs(context->f2, STRUCT_FLOAT_COUNT_1805E1710 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B93F8 001B61F8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1));
/*801B93FC 001B61FC*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*801B9400 001B6200*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38c, context->r31));
/*801B9404 001B6204*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x12c, context->r3));
/*801B9408 001B6208*/ PPC::Runtime::ASM::fmuls(context->f1, context->f1, context->f0);
/*801B940C 001B620C*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r1));
/*801B9410 001B6210*/ PPC::Runtime::ASM::fmuls(context->f0, context->f3, context->f0);
/*801B9414 001B6214*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f2);
/*801B9418 001B6218*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r1));
/*801B941C 001B621C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*801B9420 001B6220*/ PPC::Runtime::ASM::beq(.L_801B9458);
/*801B9424 001B6224*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2dc, context->r31));
/*801B9428 001B6228*/ PPC::Runtime::ASM::fdivs(context->f1, context->f0, context->f1);
/*801B942C 001B622C*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f2);
/*801B9430 001B6230*/ PPC::Runtime::ASM::ble(.L_801B9458);
/*801B9434 001B6234*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1714 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B9438 001B6238*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*801B943C 001B623C*/ PPC::Runtime::ASM::bge(.L_801B9458);
/*801B9440 001B6240*/ PPC::Runtime::ASM::fsubs(context->f2, context->f0, context->f1);
/*801B9444 001B6244*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x128, context->r3));
/*801B9448 001B6248*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*801B944C 001B624C*/ PPC::Runtime::ASM::fmuls(context->f0, context->f2, context->f0);
/*801B9450 001B6250*/ PPC::Runtime::ASM::fmuls(context->f0, context->f1, context->f0);
/*801B9454 001B6254*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_801B9458, 0x801B9458) //this is a jump label
/*801B9458 001B6258*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*801B945C 001B625C*/ PPC::Runtime::ASM::lfs(context->f1, STRUCT_FLOAT_COUNT_1805E1710 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B9460 001B6260*/ PPC::Runtime::ASM::fcmpu(cr0, context->f2, context->f1);
/*801B9464 001B6264*/ PPC::Runtime::ASM::beq(.L_801B94A0);
/*801B9468 001B6268*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2e4, context->r31));
/*801B946C 001B626C*/ PPC::Runtime::ASM::fdivs(context->f2, context->f0, context->f2);
/*801B9470 001B6270*/ PPC::Runtime::ASM::fcmpo(cr0, context->f2, context->f1);
/*801B9474 001B6274*/ PPC::Runtime::ASM::ble(.L_801B94A0);
/*801B9478 001B6278*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1714 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B947C 001B627C*/ PPC::Runtime::ASM::fcmpo(cr0, context->f2, context->f0);
/*801B9480 001B6280*/ PPC::Runtime::ASM::bge(.L_801B94A0);
/*801B9484 001B6284*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38c, context->r31));
/*801B9488 001B6288*/ PPC::Runtime::ASM::fsubs(context->f2, context->f0, context->f2);
/*801B948C 001B628C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*801B9490 001B6290*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x128, context->r3));
/*801B9494 001B6294*/ PPC::Runtime::ASM::fmuls(context->f0, context->f2, context->f0);
/*801B9498 001B6298*/ PPC::Runtime::ASM::fmuls(context->f0, context->f1, context->f0);
/*801B949C 001B629C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_801B94A0, 0x801B94A0) //this is a jump label
/*801B94A0 001B62A0*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801B94A4 001B62A4*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x8);
/*801B94A8 001B62A8*/ PPC::Runtime::ASM::bl(fn_8019A588);
/*801B94AC 001B62AC*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x20);
/*801B94B0 001B62B0*/ PPC::Runtime::ASM::bl(fn_803D2158);
/*801B94B4 001B62B4*/ PPC::Runtime::ASM::fmr(context->f31, context->f1);
/*801B94B8 001B62B8*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x8);
/*801B94BC 001B62BC*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x20);
/*801B94C0 001B62C0*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0x14);
/*801B94C4 001B62C4*/ PPC::Runtime::ASM::bl(fn_80064C18);
/*801B94C8 001B62C8*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x14);
/*801B94CC 001B62CC*/ PPC::Runtime::ASM::bl(fn_803D2158);
/*801B94D0 001B62D0*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1710 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B94D4 001B62D4*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f0);
/*801B94D8 001B62D8*/ PPC::Runtime::ASM::beq(.L_801B9518);
/*801B94DC 001B62DC*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x14);
/*801B94E0 001B62E0*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*801B94E4 001B62E4*/ PPC::Runtime::ASM::bl(fn_80062CA4);
/*801B94E8 001B62E8*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801B94EC 001B62EC*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x2c);
/*801B94F0 001B62F0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*801B94F4 001B62F4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*801B94F8 001B62F8*/ PPC::Runtime::ASM::fmuls(context->f2, context->f2, context->f31);
/*801B94FC 001B62FC*/ PPC::Runtime::ASM::fmuls(context->f1, context->f1, context->f31);
/*801B9500 001B6300*/ PPC::Runtime::ASM::fmuls(context->f0, context->f0, context->f31);
/*801B9504 001B6304*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*801B9508 001B6308*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*801B950C 001B630C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*801B9510 001B6310*/ PPC::Runtime::ASM::bl(fn_803D2158);
/*801B9514 001B6314*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5ac, context->r31));
RUNTIME_PPC_JUMP_LABEL(.L_801B9518, 0x801B9518) //this is a jump label
/*801B9518 001B6318*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*801B951C 001B631C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*801B9520 001B6320*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2d0, context->r31));
/*801B9524 001B6324*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2d4, context->r31));
/*801B9528 001B6328*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*801B952C 001B632C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2d8, context->r31));
RUNTIME_PPC_JUMP_LABEL(.L_801B9530, 0x801B9530) //this is a jump label
/*801B9530 001B6330*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x2dc);
/*801B9534 001B6334*/ PPC::Runtime::ASM::bl(fn_803D2158);
/*801B9538 001B6338*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1710 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801B953C 001B633C*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f0);
/*801B9540 001B6340*/ PPC::Runtime::ASM::beq(.L_801B954C);
/*801B9544 001B6344*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801B9548 001B6348*/ PPC::Runtime::ASM::bl(fn_801B90CC);
RUNTIME_PPC_JUMP_LABEL(.L_801B954C, 0x801B954C) //this is a jump label
/*801B954C 001B634C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801B9550 001B6350*/ PPC::Runtime::ASM::bl(fn_801A29F8);
/*801B9554 001B6354*/ PPC::Runtime::ASM::psq_l(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1)0, context->qr0);
/*801B9558 001B6358*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x64, context->r1));
/*801B955C 001B635C*/ PPC::Runtime::ASM::lfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*801B9560 001B6360*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*801B9564 001B6364*/ PPC::Runtime::ASM::mtlr(context->r0);
/*801B9568 001B6368*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x60);
/*801B956C 001B636C*/ PPC::Runtime::ASM::blr();
}