//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_801A04D8.hpp"



void fn_801C2904(PPC::Runtime::GCContext* context)
{
/*801C2904 001BF704*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*801C2908 001BF708*/ PPC::Runtime::ASM::mflr(context->r0);
/*801C290C 001BF70C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801C2910 001BF710*/ PPC::Runtime::ASM::bl(fn_801A04D8);
/*801C2914 001BF714*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801C2918 001BF718*/ PPC::Runtime::ASM::mtlr(context->r0);
/*801C291C 001BF71C*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*801C2920 001BF720*/ PPC::Runtime::ASM::blr();
}