//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_801B67F0.hpp"
#include "fn_Rider_CheckAnimationEnd.hpp"
#include "fn_801A8454.hpp"
#include "fn_sndAuxCallbackPrepareDelay.hpp"



void fn_801B6D6C(PPC::Runtime::GCContext* context)
{
/*801B6D6C 001B3B6C*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*801B6D70 001B3B70*/ PPC::Runtime::ASM::mflr(context->r0);
/*801B6D74 001B3B74*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801B6D78 001B3B78*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*801B6D7C 001B3B7C*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*801B6D80 001B3B80*/ PPC::Runtime::ASM::bl(fn_801B67F0);
/*801B6D84 001B3B84*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*801B6D88 001B3B88*/ PPC::Runtime::ASM::bne(.L_801B6DAC);
/*801B6D8C 001B3B8C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801B6D90 001B3B90*/ PPC::Runtime::ASM::bl(fn_Rider_CheckAnimationEnd);
/*801B6D94 001B3B94*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*801B6D98 001B3B98*/ PPC::Runtime::ASM::beq(.L_801B6DAC);
/*801B6D9C 001B3B9C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801B6DA0 001B3BA0*/ PPC::Runtime::ASM::bl(fn_801A8454);
/*801B6DA4 001B3BA4*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*801B6DA8 001B3BA8*/ PPC::Runtime::ASM::bl(fn_sndAuxCallbackPrepareDelay);
RUNTIME_PPC_JUMP_LABEL(.L_801B6DAC, 0x801B6DAC) //this is a jump label
/*801B6DAC 001B3BAC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*801B6DB0 001B3BB0*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*801B6DB4 001B3BB4*/ PPC::Runtime::ASM::mtlr(context->r0);
/*801B6DB8 001B3BB8*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*801B6DBC 001B3BBC*/ PPC::Runtime::ASM::blr();
}