//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_802231E8.hpp"
#include "fn_80223298.hpp"



void fn_80226C90(PPC::Runtime::GCContext* context)
{
/*80226C90 00223A90*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*80226C94 00223A94*/ PPC::Runtime::ASM::mflr(context->r0);
/*80226C98 00223A98*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80226C9C 00223A9C*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*80226CA0 00223AA0*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*80226CA4 00223AA4*/ PPC::Runtime::ASM::bl(fn_802231E8);
/*80226CA8 00223AA8*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r31));
/*80226CAC 00223AAC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*80226CB0 00223AB0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r4));
/*80226CB4 00223AB4*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*80226CB8 00223AB8*/ PPC::Runtime::ASM::bl(fn_80223298);
/*80226CBC 00223ABC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80226CC0 00223AC0*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*80226CC4 00223AC4*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80226CC8 00223AC8*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*80226CCC 00223ACC*/ PPC::Runtime::ASM::blr();
}