//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_800B61F4.hpp"
#include "fn_800B2540.hpp"
#include "fn_800B0CDC.hpp"
#include "fn_800B0A6C.hpp"
#include "fn_800B5690.hpp"



void fn_800B2A1C(PPC::Runtime::GCContext* context)
{
/*800B2A1C 000AF81C*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x40, context->r1));
/*800B2A20 000AF820*/ PPC::Runtime::ASM::mflr(context->r0);
/*800B2A24 000AF824*/ PPC::Runtime::ASM::lis(context->r4, StructWithFuncPtrs_40_DoesCameraStuffAndLoadingImages @ Get_MemoryOffset_HighBit);
/*800B2A28 000AF828*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B2A2C 000AF82C*/ PPC::Runtime::ASM::addi(context->r5, context->r4, StructWithFuncPtrs_40_DoesCameraStuffAndLoadingImages @ Get_MemoryOffset_LowBit);
/*800B2A30 000AF830*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*800B2A34 000AF834*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*800B2A38 000AF838*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r3));
/*800B2A3C 000AF83C*/ PPC::Runtime::ASM::lbz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x9c, context->r3));
/*800B2A40 000AF840*/ PPC::Runtime::ASM::mulli(context->r0, context->r0, 0x18);
/*800B2A44 000AF844*/ PPC::Runtime::ASM::extrwi(context->r4, context->r4, 1, 27);
/*800B2A48 000AF848*/ PPC::Runtime::ASM::add(context->r5, context->r5, context->r0);
/*800B2A4C 000AF84C*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r5));
/*800B2A50 000AF850*/ PPC::Runtime::ASM::mtctr(context->r12);
/*800B2A54 000AF854*/ PPC::Runtime::ASM::bctrl();
/*800B2A58 000AF858*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r31));
/*800B2A5C 000AF85C*/ PPC::Runtime::ASM::lis(context->r3, StructWithFuncPtrs_40_DoesCameraStuffAndLoadingImages @ Get_MemoryOffset_HighBit);
/*800B2A60 000AF860*/ PPC::Runtime::ASM::addi(context->r4, context->r3, StructWithFuncPtrs_40_DoesCameraStuffAndLoadingImages @ Get_MemoryOffset_LowBit);
/*800B2A64 000AF864*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*800B2A68 000AF868*/ PPC::Runtime::ASM::mulli(context->r0, context->r0, 0x18);
/*800B2A6C 000AF86C*/ PPC::Runtime::ASM::add(context->r4, context->r4, context->r0);
/*800B2A70 000AF870*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r4));
/*800B2A74 000AF874*/ PPC::Runtime::ASM::mtctr(context->r12);
/*800B2A78 000AF878*/ PPC::Runtime::ASM::bctrl();
/*800B2A7C 000AF87C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*800B2A80 000AF880*/ PPC::Runtime::ASM::bl(fn_800B61F4);
/*800B2A84 000AF884*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*800B2A88 000AF888*/ PPC::Runtime::ASM::bl(fn_800B2540);
/*800B2A8C 000AF88C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*800B2A90 000AF890*/ PPC::Runtime::ASM::bl(fn_800B0CDC);
/*800B2A94 000AF894*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r31));
/*800B2A98 000AF898*/ PPC::Runtime::ASM::li(context->r3, 0x0);
/*800B2A9C 000AF89C*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x9c, context->r31));
/*800B2AA0 000AF8A0*/ PPC::Runtime::ASM::rlwimi(context->r0, context->r3, 4, 27, 27);
/*800B2AA4 000AF8A4*/ PPC::Runtime::ASM::stb(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x9c, context->r31));
/*800B2AA8 000AF8A8*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x94, context->r31));
/*800B2AAC 000AF8AC*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*800B2AB0 000AF8B0*/ PPC::Runtime::ASM::beq(.L_800B2BE0);
/*800B2AB4 000AF8B4*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x20);
/*800B2AB8 000AF8B8*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0x14);
/*800B2ABC 000AF8BC*/ PPC::Runtime::ASM::addi(context->r6, context->r1, 0x8);
/*800B2AC0 000AF8C0*/ PPC::Runtime::ASM::bl(fn_800B0A6C);
/*800B2AC4 000AF8C4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x94, context->r31));
/*800B2AC8 000AF8C8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r31));
/*800B2ACC 000AF8CC*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r3));
/*800B2AD0 000AF8D0*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r31));
/*800B2AD4 000AF8D4*/ PPC::Runtime::ASM::fsubs(context->f5, context->f1, context->f0);
/*800B2AD8 000AF8D8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r3));
/*800B2ADC 000AF8DC*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*800B2AE0 000AF8E0*/ PPC::Runtime::ASM::fsubs(context->f4, context->f2, context->f1);
/*800B2AE4 000AF8E4*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r31));
/*800B2AE8 000AF8E8*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f0);
/*800B2AEC 000AF8EC*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r3));
/*800B2AF0 000AF8F0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*800B2AF4 000AF8F4*/ PPC::Runtime::ASM::fsubs(context->f3, context->f3, context->f2);
/*800B2AF8 000AF8F8*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*800B2AFC 000AF8FC*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f1, context->f0);
/*800B2B00 000AF900*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f2, context->f0);
/*800B2B04 000AF904*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x6c, context->r31));
/*800B2B08 000AF908*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*800B2B0C 000AF90C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*800B2B10 000AF910*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f0);
/*800B2B14 000AF914*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*800B2B18 000AF918*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f1, context->f0);
/*800B2B1C 000AF91C*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f2, context->f0);
/*800B2B20 000AF920*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x70, context->r31));
/*800B2B24 000AF924*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*800B2B28 000AF928*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*800B2B2C 000AF92C*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f0);
/*800B2B30 000AF930*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*800B2B34 000AF934*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f1, context->f0);
/*800B2B38 000AF938*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f2, context->f0);
/*800B2B3C 000AF93C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x74, context->r31));
/*800B2B40 000AF940*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x94, context->r31));
/*800B2B44 000AF944*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B2B48 000AF948*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r3));
/*800B2B4C 000AF94C*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B2B50 000AF950*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r3));
/*800B2B54 000AF954*/ PPC::Runtime::ASM::fsubs(context->f5, context->f1, context->f0);
/*800B2B58 000AF958*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*800B2B5C 000AF95C*/ PPC::Runtime::ASM::fsubs(context->f4, context->f3, context->f2);
/*800B2B60 000AF960*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B2B64 000AF964*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r3));
/*800B2B68 000AF968*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f0);
/*800B2B6C 000AF96C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*800B2B70 000AF970*/ PPC::Runtime::ASM::fsubs(context->f3, context->f3, context->f2);
/*800B2B74 000AF974*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f1, context->f0);
/*800B2B78 000AF978*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*800B2B7C 000AF97C*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f1, context->f0);
/*800B2B80 000AF980*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x78, context->r31));
/*800B2B84 000AF984*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*800B2B88 000AF988*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*800B2B8C 000AF98C*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f0);
/*800B2B90 000AF990*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*800B2B94 000AF994*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f1, context->f0);
/*800B2B98 000AF998*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f2, context->f0);
/*800B2B9C 000AF99C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x7c, context->r31));
/*800B2BA0 000AF9A0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*800B2BA4 000AF9A4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*800B2BA8 000AF9A8*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f0);
/*800B2BAC 000AF9AC*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*800B2BB0 000AF9B0*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f1, context->f0);
/*800B2BB4 000AF9B4*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f2, context->f0);
/*800B2BB8 000AF9B8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x80, context->r31));
/*800B2BBC 000AF9BC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r31));
/*800B2BC0 000AF9C0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r31));
/*800B2BC4 000AF9C4*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r31));
/*800B2BC8 000AF9C8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x60, context->r31));
/*800B2BCC 000AF9CC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r31));
/*800B2BD0 000AF9D0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x64, context->r31));
/*800B2BD4 000AF9D4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r31));
/*800B2BD8 000AF9D8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x68, context->r31));
/*800B2BDC 000AF9DC*/ PPC::Runtime::ASM::b(.L_800B2C30);
RUNTIME_PPC_JUMP_LABEL(.L_800B2BE0, 0x800B2BE0) //this is a jump label
/*800B2BE0 000AF9E0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B2BE4 000AF9E4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B2BE8 000AF9E8*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r31));
/*800B2BEC 000AF9EC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r31));
/*800B2BF0 000AF9F0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B2BF4 000AF9F4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r31));
/*800B2BF8 000AF9F8*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r31));
/*800B2BFC 000AF9FC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r31));
/*800B2C00 000AFA00*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r31));
/*800B2C04 000AFA04*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r31));
/*800B2C08 000AFA08*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r31));
/*800B2C0C 000AFA0C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r31));
/*800B2C10 000AFA10*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r31));
/*800B2C14 000AFA14*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r31));
/*800B2C18 000AFA18*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r31));
/*800B2C1C 000AFA1C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x60, context->r31));
/*800B2C20 000AFA20*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r31));
/*800B2C24 000AFA24*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r31));
/*800B2C28 000AFA28*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x64, context->r31));
/*800B2C2C 000AFA2C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x68, context->r31));
RUNTIME_PPC_JUMP_LABEL(.L_800B2C30, 0x800B2C30) //this is a jump label
/*800B2C30 000AFA30*/ PPC::Runtime::ASM::li(context->r3, 0x7);
/*800B2C34 000AFA34*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*800B2C38 000AFA38*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r31));
/*800B2C3C 000AFA3C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r31));
/*800B2C40 000AFA40*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r31));
/*800B2C44 000AFA44*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*800B2C48 000AFA48*/ PPC::Runtime::ASM::beq(.L_800B2C58);
/*800B2C4C 000AFA4C*/ PPC::Runtime::ASM::bl(fn_800B5690);
/*800B2C50 000AFA50*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*800B2C54 000AFA54*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r31));
RUNTIME_PPC_JUMP_LABEL(.L_800B2C58, 0x800B2C58) //this is a jump label
/*800B2C58 000AFA58*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B2C5C 000AFA5C*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*800B2C60 000AFA60*/ PPC::Runtime::ASM::mtlr(context->r0);
/*800B2C64 000AFA64*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x40);
/*800B2C68 000AFA68*/ PPC::Runtime::ASM::blr();
}