//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_8007B990(PPC::Runtime::GCContext* context)
{
/*8007B990 00078790*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*8007B994 00078794*/ PPC::Runtime::ASM::mflr(context->r0);
/*8007B998 00078798*/ PPC::Runtime::ASM::lis(context->r3, lbl_80552A30 @ Get_MemoryOffset_HighBit);
/*8007B99C 0007879C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8007B9A0 000787A0*/ PPC::Runtime::ASM::addi(context->r3, context->r3, lbl_80552A30 @ Get_MemoryOffset_LowBit);
/*8007B9A4 000787A4*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r3));
/*8007B9A8 000787A8*/ PPC::Runtime::ASM::cmplwi(context->r0, 0x0);
/*8007B9AC 000787AC*/ PPC::Runtime::ASM::beq(.L_8007B9B8);
/*8007B9B0 000787B0*/ PPC::Runtime::ASM::lbz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x26, context->r3));
/*8007B9B4 000787B4*/ PPC::Runtime::ASM::b(.L_8007B9BC);
RUNTIME_PPC_JUMP_LABEL(.L_8007B9B8, 0x8007B9B8) //this is a jump label
/*8007B9B8 000787B8*/ PPC::Runtime::ASM::bl(fn_80487C84);
RUNTIME_PPC_JUMP_LABEL(.L_8007B9BC, 0x8007B9BC) //this is a jump label
/*8007B9BC 000787BC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8007B9C0 000787C0*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8007B9C4 000787C4*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*8007B9C8 000787C8*/ PPC::Runtime::ASM::blr();
}