//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_800B7E90.hpp"
#include "fn_800638F8.hpp"
#include "fn_800638F8.hpp"
#include "fn_800B7E90.hpp"
#include "fn_80062ECC.hpp"
#include "fn_800B7E90.hpp"
#include "fn_80062ECC.hpp"
#include "fn_800638F8.hpp"
#include "fn_8022CB8C.hpp"
#include "fn_GetBombCharge.hpp"
#include "fn_800B7E90.hpp"



void fn_800B61F4(PPC::Runtime::GCContext* context)
{
/*800B61F4 000B2FF4*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x70, context->r1));
/*800B61F8 000B2FF8*/ PPC::Runtime::ASM::mflr(context->r0);
/*800B61FC 000B2FFC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x74, context->r1));
/*800B6200 000B3000*/ PPC::Runtime::ASM::stfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x60, context->r1));
/*800B6204 000B3004*/ PPC::Runtime::ASM::psq_st(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x68, context->r1)0, context->qr0);
/*800B6208 000B3008*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r1));
/*800B620C 000B300C*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*800B6210 000B3010*/ PPC::Runtime::ASM::mr(context->r30, context->r3);
/*800B6214 000B3014*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x94, context->r3));
/*800B6218 000B3018*/ PPC::Runtime::ASM::cmplwi(context->r31, 0x0);
/*800B621C 000B301C*/ PPC::Runtime::ASM::beq(.L_800B67AC);
/*800B6220 000B3020*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x84, context->r30));
/* 800B6224 000B3024  54 00 CF FF */ extrwi. context->r0 , context->r0 , 1 , 24
/*800B6228 000B3028*/ PPC::Runtime::ASM::beq(.L_800B6658);
/*800B622C 000B302C*/ PPC::Runtime::ASM::cmplwi(context->r31, 0x0);
/*800B6230 000B3030*/ PPC::Runtime::ASM::beq(.L_800B6658);
/*800B6234 000B3034*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8c, context->r30));
/*800B6238 000B3038*/ PPC::Runtime::ASM::beq(.L_800B6290);
/*800B623C 000B303C*/ PPC::Runtime::ASM::lha(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa6, context->r31));
/*800B6240 000B3040*/ PPC::Runtime::ASM::cmpwi(context->r4, 0x5);
/*800B6244 000B3044*/ PPC::Runtime::ASM::beq(.L_800B6290);
/*800B6248 000B3048*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*800B624C 000B304C*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x9);
/*800B6250 000B3050*/ PPC::Runtime::ASM::beq(.L_800B627C);
/*800B6254 000B3054*/ PPC::Runtime::ASM::bge(.L_800B6290);
/*800B6258 000B3058*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x1);
/*800B625C 000B305C*/ PPC::Runtime::ASM::beq(.L_800B6264);
/*800B6260 000B3060*/ PPC::Runtime::ASM::b(.L_800B6290);
RUNTIME_PPC_JUMP_LABEL(.L_800B6264, 0x800B6264) //this is a jump label
/*800B6264 000B3064*/ PPC::Runtime::ASM::lis(context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_HighBit);
/*800B6268 000B3068*/ PPC::Runtime::ASM::slwi(context->r0, context->r4, 3);
/*800B626C 000B306C*/ PPC::Runtime::ASM::addi(context->r3, context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_LowBit);
/*800B6270 000B3070*/ PPC::Runtime::ASM::add(context->r3, context->r3, context->r0);
/*800B6274 000B3074*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x240, context->r3));
/*800B6278 000B3078*/ PPC::Runtime::ASM::b(.L_800B6290);
RUNTIME_PPC_JUMP_LABEL(.L_800B627C, 0x800B627C) //this is a jump label
/*800B627C 000B307C*/ PPC::Runtime::ASM::lis(context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_HighBit);
/*800B6280 000B3080*/ PPC::Runtime::ASM::slwi(context->r0, context->r4, 3);
/*800B6284 000B3084*/ PPC::Runtime::ASM::addi(context->r3, context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_LowBit);
/*800B6288 000B3088*/ PPC::Runtime::ASM::add(context->r3, context->r3, context->r0);
/*800B628C 000B308C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x244, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_800B6290, 0x800B6290) //this is a jump label
/*800B6290 000B3090*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf4, context->r30));
/*800B6294 000B3094*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x44);
/*800B6298 000B3098*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B629C 000B309C*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B62A0 000B30A0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B62A4 000B30A4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf8, context->r30));
/*800B62A8 000B30A8*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B62AC 000B30AC*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B62B0 000B30B0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B62B4 000B30B4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xfc, context->r30));
/*800B62B8 000B30B8*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B62BC 000B30BC*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B62C0 000B30C0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B62C4 000B30C4*/ PPC::Runtime::ASM::bl(fn_803D2158);
/*800B62C8 000B30C8*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805DF1F4 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B62CC 000B30CC*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*800B62D0 000B30D0*/ PPC::Runtime::ASM::bge(.L_800B6328);
/*800B62D4 000B30D4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xe8, context->r30));
/*800B62D8 000B30D8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xec, context->r30));
/*800B62DC 000B30DC*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x110, context->r30));
/*800B62E0 000B30E0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x114, context->r30));
/*800B62E4 000B30E4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf0, context->r30));
/*800B62E8 000B30E8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf4, context->r30));
/*800B62EC 000B30EC*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x118, context->r30));
/*800B62F0 000B30F0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B62F4 000B30F4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf8, context->r30));
/*800B62F8 000B30F8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xfc, context->r30));
/*800B62FC 000B30FC*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B6300 000B3100*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*800B6304 000B3104*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x100, context->r30));
/*800B6308 000B3108*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r30));
/*800B630C 000B310C*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x128, context->r30));
/*800B6310 000B3110*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x12c, context->r30));
/*800B6314 000B3114*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x108, context->r30));
/*800B6318 000B3118*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10c, context->r30));
/*800B631C 000B311C*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x130, context->r30));
/*800B6320 000B3120*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x134, context->r30));
/*800B6324 000B3124*/ PPC::Runtime::ASM::b(.L_800B67AC);
RUNTIME_PPC_JUMP_LABEL(.L_800B6328, 0x800B6328) //this is a jump label
/*800B6328 000B3128*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8c, context->r30));
/*800B632C 000B312C*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805DF254 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6330 000B3130*/ PPC::Runtime::ASM::fadds(context->f2, context->f1, context->f2);
/*800B6334 000B3134*/ PPC::Runtime::ASM::fcmpo(cr0, context->f2, context->f0);
/*800B6338 000B3138*/ PPC::Runtime::ASM::bge(.L_800B6340);
/*800B633C 000B313C*/ PPC::Runtime::ASM::fmr(context->f2, context->f0);
RUNTIME_PPC_JUMP_LABEL(.L_800B6340, 0x800B6340) //this is a jump label
/*800B6340 000B3140*/ PPC::Runtime::ASM::fdivs(context->f3, context->f2, context->f1);
/*800B6344 000B3144*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B6348 000B3148*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B634C 000B314C*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x2c);
/*800B6350 000B3150*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B6354 000B3154*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*800B6358 000B3158*/ PPC::Runtime::ASM::fmuls(context->f8, context->f2, context->f3);
/*800B635C 000B315C*/ PPC::Runtime::ASM::fmuls(context->f7, context->f1, context->f3);
/*800B6360 000B3160*/ PPC::Runtime::ASM::fmuls(context->f6, context->f0, context->f3);
/*800B6364 000B3164*/ PPC::Runtime::ASM::stfs(context->f8, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B6368 000B3168*/ PPC::Runtime::ASM::stfs(context->f7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B636C 000B316C*/ PPC::Runtime::ASM::stfs(context->f6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B6370 000B3170*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xe8, context->r30));
/*800B6374 000B3174*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B6378 000B3178*/ PPC::Runtime::ASM::lfs(context->f9, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x90, context->r30));
/*800B637C 000B317C*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B6380 000B3180*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x100, context->r30));
/*800B6384 000B3184*/ PPC::Runtime::ASM::lfs(context->f5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xec, context->r30));
/*800B6388 000B3188*/ PPC::Runtime::ASM::lfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B638C 000B318C*/ PPC::Runtime::ASM::fmadds(context->f0, context->f2, context->f9, context->f0);
/*800B6390 000B3190*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf0, context->r30));
/*800B6394 000B3194*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B6398 000B3198*/ PPC::Runtime::ASM::fsubs(context->f5, context->f5, context->f4);
/*800B639C 000B319C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1));
/*800B63A0 000B31A0*/ PPC::Runtime::ASM::fsubs(context->f10, context->f3, context->f1);
/*800B63A4 000B31A4*/ PPC::Runtime::ASM::lfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r30));
/*800B63A8 000B31A8*/ PPC::Runtime::ASM::fmadds(context->f1, context->f4, context->f9, context->f5);
/*800B63AC 000B31AC*/ PPC::Runtime::ASM::fmuls(context->f0, context->f7, context->f4);
/*800B63B0 000B31B0*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*800B63B4 000B31B4*/ PPC::Runtime::ASM::fmadds(context->f0, context->f8, context->f2, context->f0);
/*800B63B8 000B31B8*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x108, context->r30));
/*800B63BC 000B31BC*/ PPC::Runtime::ASM::fmadds(context->f0, context->f6, context->f3, context->f0);
/*800B63C0 000B31C0*/ PPC::Runtime::ASM::fmadds(context->f1, context->f3, context->f9, context->f10);
/*800B63C4 000B31C4*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*800B63C8 000B31C8*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*800B63CC 000B31CC*/ PPC::Runtime::ASM::fmadds(context->f2, context->f2, context->f0, context->f8);
/*800B63D0 000B31D0*/ PPC::Runtime::ASM::fmadds(context->f1, context->f4, context->f0, context->f7);
/*800B63D4 000B31D4*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f0, context->f6);
/*800B63D8 000B31D8*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r1));
/*800B63DC 000B31DC*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r1));
/*800B63E0 000B31E0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*800B63E4 000B31E4*/ PPC::Runtime::ASM::bl(fn_800B7E90);
/*800B63E8 000B31E8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x88, context->r30));
/*800B63EC 000B31EC*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x44);
/*800B63F0 000B31F0*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x100);
/*800B63F4 000B31F4*/ PPC::Runtime::ASM::bl(fn_800638F8);
/*800B63F8 000B31F8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x88, context->r30));
/*800B63FC 000B31FC*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x38);
/*800B6400 000B3200*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x100);
/*800B6404 000B3204*/ PPC::Runtime::ASM::bl(fn_800638F8);
/*800B6408 000B3208*/ PPC::Runtime::ASM::lfs(context->f5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B640C 000B320C*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x20);
/*800B6410 000B3210*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r30));
/*800B6414 000B3214*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*800B6418 000B3218*/ PPC::Runtime::ASM::lfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B641C 000B321C*/ PPC::Runtime::ASM::fmuls(context->f0, context->f5, context->f1);
/*800B6420 000B3220*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x100, context->r30));
/*800B6424 000B3224*/ PPC::Runtime::ASM::lfs(context->f6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B6428 000B3228*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x108, context->r30));
/*800B642C 000B322C*/ PPC::Runtime::ASM::fmadds(context->f0, context->f4, context->f2, context->f0);
/*800B6430 000B3230*/ PPC::Runtime::ASM::fmadds(context->f0, context->f6, context->f3, context->f0);
/*800B6434 000B3234*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*800B6438 000B3238*/ PPC::Runtime::ASM::fmadds(context->f2, context->f2, context->f0, context->f4);
/*800B643C 000B323C*/ PPC::Runtime::ASM::fmadds(context->f1, context->f1, context->f0, context->f5);
/*800B6440 000B3240*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f0, context->f6);
/*800B6444 000B3244*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*800B6448 000B3248*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*800B644C 000B324C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*800B6450 000B3250*/ PPC::Runtime::ASM::bl(fn_800B7E90);
/*800B6454 000B3254*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x2c);
/*800B6458 000B3258*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x20);
/*800B645C 000B325C*/ PPC::Runtime::ASM::bl(fn_80062ECC);
/*800B6460 000B3260*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805DF1F4 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6464 000B3264*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*800B6468 000B3268*/ PPC::Runtime::ASM::ble(.L_800B6580);
/*800B646C 000B326C*/ PPC::Runtime::ASM::lfd(context->f0, STRUCT_DOUBLE_COUNT_1805DF248 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6470 000B3270*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*800B6474 000B3274*/ PPC::Runtime::ASM::ble(.L_800B6484);
/*800B6478 000B3278*/ PPC::Runtime::ASM::lfd(context->f0, STRUCT_DOUBLE_COUNT_1805DF258 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B647C 000B327C*/ PPC::Runtime::ASM::fsub(context->f1, context->f0, context->f1);
/*800B6480 000B3280*/ PPC::Runtime::ASM::frsp(context->f1, context->f1);
RUNTIME_PPC_JUMP_LABEL(.L_800B6484, 0x800B6484) //this is a jump label
/*800B6484 000B3284*/ PPC::Runtime::ASM::lfd(context->f0, STRUCT_DOUBLE_COUNT_1805DF248 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6488 000B3288*/ PPC::Runtime::ASM::lfs(context->f31, STRUCT_FLOAT_COUNT_1805DF1E8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B648C 000B328C*/ PPC::Runtime::ASM::fdiv(context->f0, context->f1, context->f0);
/*800B6490 000B3290*/ PPC::Runtime::ASM::frsp(context->f0, context->f0);
/*800B6494 000B3294*/ PPC::Runtime::ASM::fcmpo(cr0, context->f0, context->f31);
/*800B6498 000B3298*/ PPC::Runtime::ASM::bge(.L_800B64A0);
/*800B649C 000B329C*/ PPC::Runtime::ASM::b(.L_800B64B4);
RUNTIME_PPC_JUMP_LABEL(.L_800B64A0, 0x800B64A0) //this is a jump label
/*800B64A0 000B32A0*/ PPC::Runtime::ASM::lfs(context->f31, STRUCT_FLOAT_COUNT_1805DF1F0 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B64A4 000B32A4*/ PPC::Runtime::ASM::fcmpo(cr0, context->f0, context->f31);
/*800B64A8 000B32A8*/ PPC::Runtime::ASM::ble(.L_800B64B0);
/*800B64AC 000B32AC*/ PPC::Runtime::ASM::b(.L_800B64B4);
RUNTIME_PPC_JUMP_LABEL(.L_800B64B0, 0x800B64B0) //this is a jump label
/*800B64B0 000B32B0*/ PPC::Runtime::ASM::fmr(context->f31, context->f0);
RUNTIME_PPC_JUMP_LABEL(.L_800B64B4, 0x800B64B4) //this is a jump label
/*800B64B4 000B32B4*/ PPC::Runtime::ASM::lfs(context->f6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B64B8 000B32B8*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x14);
/*800B64BC 000B32BC*/ PPC::Runtime::ASM::lfs(context->f5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*800B64C0 000B32C0*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*800B64C4 000B32C4*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*800B64C8 000B32C8*/ PPC::Runtime::ASM::lfs(context->f7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B64CC 000B32CC*/ PPC::Runtime::ASM::fmuls(context->f0, context->f6, context->f5);
/*800B64D0 000B32D0*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*800B64D4 000B32D4*/ PPC::Runtime::ASM::lfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B64D8 000B32D8*/ PPC::Runtime::ASM::fmuls(context->f1, context->f7, context->f3);
/*800B64DC 000B32DC*/ PPC::Runtime::ASM::fmsubs(context->f0, context->f7, context->f2, context->f0);
/*800B64E0 000B32E0*/ PPC::Runtime::ASM::fmuls(context->f2, context->f4, context->f2);
/*800B64E4 000B32E4*/ PPC::Runtime::ASM::fmsubs(context->f1, context->f4, context->f5, context->f1);
/*800B64E8 000B32E8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*800B64EC 000B32EC*/ PPC::Runtime::ASM::fmsubs(context->f0, context->f6, context->f3, context->f2);
/*800B64F0 000B32F0*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*800B64F4 000B32F4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*800B64F8 000B32F8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*800B64FC 000B32FC*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*800B6500 000B3300*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*800B6504 000B3304*/ PPC::Runtime::ASM::stw(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*800B6508 000B3308*/ PPC::Runtime::ASM::stw(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*800B650C 000B330C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*800B6510 000B3310*/ PPC::Runtime::ASM::bl(fn_800B7E90);
/*800B6514 000B3314*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805DF1F4 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6518 000B3318*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*800B651C 000B331C*/ PPC::Runtime::ASM::ble(.L_800B6550);
/*800B6520 000B3320*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x44);
/*800B6524 000B3324*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x20);
/*800B6528 000B3328*/ PPC::Runtime::ASM::bl(fn_80062ECC);
/*800B652C 000B332C*/ PPC::Runtime::ASM::lis(context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_HighBit);
/*800B6530 000B3330*/ PPC::Runtime::ASM::fmuls(context->f1, context->f31, context->f1);
/*800B6534 000B3334*/ PPC::Runtime::ASM::addi(context->r4, context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_LowBit);
/*800B6538 000B3338*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x234, context->r4));
/*800B653C 000B333C*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x44);
/*800B6540 000B3340*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x14);
/*800B6544 000B3344*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x338, context->r5));
/*800B6548 000B3348*/ PPC::Runtime::ASM::fmuls(context->f1, context->f0, context->f1);
/*800B654C 000B334C*/ PPC::Runtime::ASM::bl(fn_800638F8);
RUNTIME_PPC_JUMP_LABEL(.L_800B6550, 0x800B6550) //this is a jump label
/*800B6550 000B3350*/ PPC::Runtime::ASM::lis(context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_HighBit);
/*800B6554 000B3354*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x100, context->r30));
/*800B6558 000B3358*/ PPC::Runtime::ASM::addi(context->r3, context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_LowBit);
/*800B655C 000B335C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r30));
/*800B6560 000B3360*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x234, context->r3));
/*800B6564 000B3364*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x108, context->r30));
/*800B6568 000B3368*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x33c, context->r3));
/*800B656C 000B336C*/ PPC::Runtime::ASM::fmuls(context->f3, context->f31, context->f3);
/*800B6570 000B3370*/ PPC::Runtime::ASM::fmuls(context->f2, context->f2, context->f3);
/*800B6574 000B3374*/ PPC::Runtime::ASM::fmuls(context->f4, context->f1, context->f3);
/*800B6578 000B3378*/ PPC::Runtime::ASM::fmuls(context->f3, context->f0, context->f3);
/*800B657C 000B337C*/ PPC::Runtime::ASM::b(.L_800B658C);
RUNTIME_PPC_JUMP_LABEL(.L_800B6580, 0x800B6580) //this is a jump label
/*800B6580 000B3380*/ PPC::Runtime::ASM::lfs(context->f3, STRUCT_FLOAT_COUNT_1805DF1E8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6584 000B3384*/ PPC::Runtime::ASM::fmr(context->f4, context->f3);
/*800B6588 000B3388*/ PPC::Runtime::ASM::fmr(context->f2, context->f3);
RUNTIME_PPC_JUMP_LABEL(.L_800B658C, 0x800B658C) //this is a jump label
/*800B658C 000B338C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B6590 000B3390*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B6594 000B3394*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*800B6598 000B3398*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B659C 000B339C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B65A0 000B33A0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B65A4 000B33A4*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*800B65A8 000B33A8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B65AC 000B33AC*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B65B0 000B33B0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B65B4 000B33B4*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*800B65B8 000B33B8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*800B65BC 000B33BC*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B65C0 000B33C0*/ PPC::Runtime::ASM::fadds(context->f0, context->f0, context->f2);
/*800B65C4 000B33C4*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B65C8 000B33C8*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B65CC 000B33CC*/ PPC::Runtime::ASM::fadds(context->f0, context->f0, context->f4);
/*800B65D0 000B33D0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B65D4 000B33D4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*800B65D8 000B33D8*/ PPC::Runtime::ASM::fadds(context->f0, context->f0, context->f3);
/*800B65DC 000B33DC*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*800B65E0 000B33E0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B65E4 000B33E4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1));
/*800B65E8 000B33E8*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*800B65EC 000B33EC*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x110, context->r30));
/*800B65F0 000B33F0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B65F4 000B33F4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*800B65F8 000B33F8*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*800B65FC 000B33FC*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x114, context->r30));
/*800B6600 000B3400*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B6604 000B3404*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*800B6608 000B3408*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*800B660C 000B340C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x118, context->r30));
/*800B6610 000B3410*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x110, context->r30));
/*800B6614 000B3414*/ PPC::Runtime::ASM::fadds(context->f0, context->f0, context->f2);
/*800B6618 000B3418*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x110, context->r30));
/*800B661C 000B341C*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x114, context->r30));
/*800B6620 000B3420*/ PPC::Runtime::ASM::fadds(context->f0, context->f0, context->f4);
/*800B6624 000B3424*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x114, context->r30));
/*800B6628 000B3428*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x118, context->r30));
/*800B662C 000B342C*/ PPC::Runtime::ASM::fadds(context->f0, context->f0, context->f3);
/*800B6630 000B3430*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x118, context->r30));
/*800B6634 000B3434*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x100, context->r30));
/*800B6638 000B3438*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r30));
/*800B663C 000B343C*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x128, context->r30));
/*800B6640 000B3440*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x12c, context->r30));
/*800B6644 000B3444*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x108, context->r30));
/*800B6648 000B3448*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x130, context->r30));
/*800B664C 000B344C*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10c, context->r30));
/*800B6650 000B3450*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x134, context->r30));
/*800B6654 000B3454*/ PPC::Runtime::ASM::b(.L_800B66A8);
RUNTIME_PPC_JUMP_LABEL(.L_800B6658, 0x800B6658) //this is a jump label
/*800B6658 000B3458*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xe8, context->r30));
/*800B665C 000B345C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xec, context->r30));
/*800B6660 000B3460*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x110, context->r30));
/*800B6664 000B3464*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x114, context->r30));
/*800B6668 000B3468*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf0, context->r30));
/*800B666C 000B346C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf4, context->r30));
/*800B6670 000B3470*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x118, context->r30));
/*800B6674 000B3474*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B6678 000B3478*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xf8, context->r30));
/*800B667C 000B347C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xfc, context->r30));
/*800B6680 000B3480*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B6684 000B3484*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*800B6688 000B3488*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x100, context->r30));
/*800B668C 000B348C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x104, context->r30));
/*800B6690 000B3490*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x128, context->r30));
/*800B6694 000B3494*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x12c, context->r30));
/*800B6698 000B3498*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x108, context->r30));
/*800B669C 000B349C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10c, context->r30));
/*800B66A0 000B34A0*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x130, context->r30));
/*800B66A4 000B34A4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x134, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_800B66A8, 0x800B66A8) //this is a jump label
/*800B66A8 000B34A8*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x9c, context->r30));
/* 800B66AC 000B34AC  54 00 EF FF */ extrwi. context->r0 , context->r0 , 1 , 28
/*800B66B0 000B34B0*/ PPC::Runtime::ASM::beq(.L_800B67AC);
/*800B66B4 000B34B4*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x94, context->r30));
/*800B66B8 000B34B8*/ PPC::Runtime::ASM::lfs(context->f31, STRUCT_FLOAT_COUNT_1805DF1E8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B66BC 000B34BC*/ PPC::Runtime::ASM::cmplwi(context->r4, 0x0);
/*800B66C0 000B34C0*/ PPC::Runtime::ASM::bne(.L_800B66CC);
/*800B66C4 000B34C4*/ PPC::Runtime::ASM::fmr(context->f1, context->f31);
/*800B66C8 000B34C8*/ PPC::Runtime::ASM::b(.L_800B6710);
RUNTIME_PPC_JUMP_LABEL(.L_800B66CC, 0x800B66CC) //this is a jump label
/*800B66CC 000B34CC*/ PPC::Runtime::ASM::lis(context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_HighBit);
/*800B66D0 000B34D0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x94, context->r4));
/*800B66D4 000B34D4*/ PPC::Runtime::ASM::addi(context->r3, context->r3, Struct_PlayerDataStruct_MayebASkipAddress @ Get_MemoryOffset_LowBit);
/*800B66D8 000B34D8*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805DF250 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B66DC 000B34DC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x234, context->r3));
/*800B66E0 000B34E0*/ PPC::Runtime::ASM::fsubs(context->f1, context->f1, context->f0);
/*800B66E4 000B34E4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r3));
/*800B66E8 000B34E8*/ PPC::Runtime::ASM::fmuls(context->f0, context->f1, context->f0);
/*800B66EC 000B34EC*/ PPC::Runtime::ASM::fcmpo(cr0, context->f0, context->f31);
/*800B66F0 000B34F0*/ PPC::Runtime::ASM::bge(.L_800B66FC);
/*800B66F4 000B34F4*/ PPC::Runtime::ASM::fmr(context->f1, context->f31);
/*800B66F8 000B34F8*/ PPC::Runtime::ASM::b(.L_800B6710);
RUNTIME_PPC_JUMP_LABEL(.L_800B66FC, 0x800B66FC) //this is a jump label
/*800B66FC 000B34FC*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r3));
/*800B6700 000B3500*/ PPC::Runtime::ASM::fcmpo(cr0, context->f0, context->f1);
/*800B6704 000B3504*/ PPC::Runtime::ASM::ble(.L_800B670C);
/*800B6708 000B3508*/ PPC::Runtime::ASM::b(.L_800B6710);
RUNTIME_PPC_JUMP_LABEL(.L_800B670C, 0x800B670C) //this is a jump label
/*800B670C 000B350C*/ PPC::Runtime::ASM::fmr(context->f1, context->f0);
RUNTIME_PPC_JUMP_LABEL(.L_800B6710, 0x800B6710) //this is a jump label
/*800B6710 000B3510*/ PPC::Runtime::ASM::fadds(context->f31, context->f31, context->f1);
/*800B6714 000B3514*/ PPC::Runtime::ASM::lha(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa6, context->r31));
/*800B6718 000B3518*/ PPC::Runtime::ASM::bl(fn_8022CB8C);
/*800B671C 000B351C*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x4);
/*800B6720 000B3520*/ PPC::Runtime::ASM::bne(.L_800B6730);
/*800B6724 000B3524*/ PPC::Runtime::ASM::lha(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa6, context->r31));
/*800B6728 000B3528*/ PPC::Runtime::ASM::bl(fn_GetBombCharge);
/*800B672C 000B352C*/ PPC::Runtime::ASM::fadds(context->f31, context->f31, context->f1);
RUNTIME_PPC_JUMP_LABEL(.L_800B6730, 0x800B6730) //this is a jump label
/*800B6730 000B3530*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805DF200 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*800B6734 000B3534*/ PPC::Runtime::ASM::fcmpo(cr0, context->f31, context->f0);
/*800B6738 000B3538*/ PPC::Runtime::ASM::ble(.L_800B67AC);
/*800B673C 000B353C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B6740 000B3540*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x44);
/*800B6744 000B3544*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B6748 000B3548*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*800B674C 000B354C*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B6750 000B3550*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B6754 000B3554*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B6758 000B3558*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B675C 000B355C*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B6760 000B3560*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B6764 000B3564*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
/*800B6768 000B3568*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B676C 000B356C*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*800B6770 000B3570*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B6774 000B3574*/ PPC::Runtime::ASM::bl(fn_800B7E90);
/*800B6778 000B3578*/ PPC::Runtime::ASM::fadds(context->f2, context->f1, context->f31);
/*800B677C 000B357C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*800B6780 000B3580*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r31));
/*800B6784 000B3584*/ PPC::Runtime::ASM::fmadds(context->f0, context->f1, context->f2, context->f0);
/*800B6788 000B3588*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x11c, context->r30));
/*800B678C 000B358C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*800B6790 000B3590*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r31));
/*800B6794 000B3594*/ PPC::Runtime::ASM::fmadds(context->f0, context->f1, context->f2, context->f0);
/*800B6798 000B3598*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x120, context->r30));
/*800B679C 000B359C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*800B67A0 000B35A0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r31));
/*800B67A4 000B35A4*/ PPC::Runtime::ASM::fmadds(context->f0, context->f1, context->f2, context->f0);
/*800B67A8 000B35A8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x124, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_800B67AC, 0x800B67AC) //this is a jump label
/*800B67AC 000B35AC*/ PPC::Runtime::ASM::psq_l(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x68, context->r1)0, context->qr0);
/*800B67B0 000B35B0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x74, context->r1));
/*800B67B4 000B35B4*/ PPC::Runtime::ASM::lfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x60, context->r1));
/*800B67B8 000B35B8*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r1));
/*800B67BC 000B35BC*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*800B67C0 000B35C0*/ PPC::Runtime::ASM::mtlr(context->r0);
/*800B67C4 000B35C4*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x70);
/*800B67C8 000B35C8*/ PPC::Runtime::ASM::blr();
}