//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80221D78.hpp"



void fn_80224C9C(PPC::Runtime::GCContext* context)
{
/*80224C9C 00221A9C*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*80224CA0 00221AA0*/ PPC::Runtime::ASM::mflr(context->r0);
/*80224CA4 00221AA4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80224CA8 00221AA8*/ PPC::Runtime::ASM::bl(fn_80221D78);
/*80224CAC 00221AAC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80224CB0 00221AB0*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80224CB4 00221AB4*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*80224CB8 00221AB8*/ PPC::Runtime::ASM::blr();
}