//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_801BE3C4(PPC::Runtime::GCContext* context)
{
/*801BE3C4 001BB1C4*/ PPC::Runtime::ASM::blr();
}