//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_gmGetClearcheckerP.hpp"



void fn_8004161C(PPC::Runtime::GCContext* context)
{
/*8004161C 0003E41C*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*80041620 0003E420*/ PPC::Runtime::ASM::mflr(context->r0);
/*80041624 0003E424*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80041628 0003E428*/ PPC::Runtime::ASM::bl(fn_gmGetClearcheckerP);
/*8004162C 0003E42C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80041630 0003E430*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0x4bc);
/*80041634 0003E434*/ PPC::Runtime::ASM::mtlr(context->r0);
/*80041638 0003E438*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*8004163C 0003E43C*/ PPC::Runtime::ASM::blr();
}