//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80062CA4.hpp"
#include "fn_80062CA4.hpp"
#include "fn_80062DD0.hpp"
#include "fn_80062ECC.hpp"
#include "fn_80062ECC.hpp"
#include "fn_8006417C.hpp"
#include "fn_801FD0E0.hpp"
#include "fn_80062CA4.hpp"
#include "fn_800D1AC4.hpp"
#include "fn_800D1838.hpp"
#include "fn_800D1860.hpp"
#include "fn_801FD0E0.hpp"
#include "fn_801FD0E0.hpp"
#include "fn_801FD714.hpp"
#include "fn_801FD714.hpp"
#include "fn_80245F70.hpp"
#include "fn_802461B4.hpp"
#include "fn_8024625C.hpp"



void fn_80205F60(PPC::Runtime::GCContext* context)
{
/*80205F60 00202D60*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x80, context->r1));
/*80205F64 00202D64*/ PPC::Runtime::ASM::mflr(context->r0);
/*80205F68 00202D68*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x84, context->r1));
/*80205F6C 00202D6C*/ PPC::Runtime::ASM::stfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x70, context->r1));
/*80205F70 00202D70*/ PPC::Runtime::ASM::psq_st(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x78, context->r1)0, context->qr0);
/*80205F74 00202D74*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x6c, context->r1));
/*80205F78 00202D78*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x68, context->r1));
/*80205F7C 00202D7C*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x64, context->r1));
/*80205F80 00202D80*/ PPC::Runtime::ASM::mr(context->r30, context->r3);
/*80205F84 00202D84*/ PPC::Runtime::ASM::li(context->r31, 0x0);
/*80205F88 00202D88*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r3));
/*80205F8C 00202D8C*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xe);
/*80205F90 00202D90*/ PPC::Runtime::ASM::blt(.L_80206454);
/*80205F94 00202D94*/ PPC::Runtime::ASM::lfs(context->f1, STRUCT_FLOAT_COUNT_1805E231C @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80205F98 00202D98*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa8c, context->r30));
/*80205F9C 00202D9C*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f0);
/*80205FA0 00202DA0*/ PPC::Runtime::ASM::beq(.L_80206228);
/*80205FA4 00202DA4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*80205FA8 00202DA8*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa80, context->r30));
/*80205FAC 00202DAC*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f0);
/*80205FB0 00202DB0*/ PPC::Runtime::ASM::bne(.L_80205FC4);
/*80205FB4 00202DB4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*80205FB8 00202DB8*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa88, context->r30));
/*80205FBC 00202DBC*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f0);
/*80205FC0 00202DC0*/ PPC::Runtime::ASM::beq(.L_80206228);
RUNTIME_PPC_JUMP_LABEL(.L_80205FC4, 0x80205FC4) //this is a jump label
/*80205FC4 00202DC4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*80205FC8 00202DC8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80205FCC 00202DCC*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E2318 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80205FD0 00202DD0*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r1));
/*80205FD4 00202DD4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*80205FD8 00202DD8*/ PPC::Runtime::ASM::lfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r1));
/*80205FDC 00202DDC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*80205FE0 00202DE0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r1));
/*80205FE4 00202DE4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa84, context->r30));
/*80205FE8 00202DE8*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r1));
/*80205FEC 00202DEC*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*80205FF0 00202DF0*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa80, context->r30));
/*80205FF4 00202DF4*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa88, context->r30));
/*80205FF8 00202DF8*/ PPC::Runtime::ASM::fsubs(context->f3, context->f4, context->f3);
/*80205FFC 00202DFC*/ PPC::Runtime::ASM::fsubs(context->f1, context->f2, context->f1);
/*80206000 00202E00*/ PPC::Runtime::ASM::fmuls(context->f2, context->f3, context->f3);
/*80206004 00202E04*/ PPC::Runtime::ASM::fmuls(context->f1, context->f1, context->f1);
/*80206008 00202E08*/ PPC::Runtime::ASM::fadds(context->f4, context->f2, context->f1);
/*8020600C 00202E0C*/ PPC::Runtime::ASM::fcmpo(cr0, context->f4, context->f0);
/*80206010 00202E10*/ PPC::Runtime::ASM::ble(.L_80206060);
/*80206014 00202E14*/ PPC::Runtime::ASM::frsqrte(context->f1, context->f4);
/*80206018 00202E18*/ PPC::Runtime::ASM::lfd(context->f3, STRUCT_DOUBLE_COUNT_1805E2330 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*8020601C 00202E1C*/ PPC::Runtime::ASM::lfd(context->f2, STRUCT_DOUBLE_COUNT_1805E2338 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80206020 00202E20*/ PPC::Runtime::ASM::fmul(context->f0, context->f1, context->f1);
/*80206024 00202E24*/ PPC::Runtime::ASM::fmul(context->f1, context->f3, context->f1);
/*80206028 00202E28*/ PPC::Runtime::ASM::fnmsub(context->f0, context->f4, context->f0, context->f2);
/*8020602C 00202E2C*/ PPC::Runtime::ASM::fmul(context->f1, context->f1, context->f0);
/*80206030 00202E30*/ PPC::Runtime::ASM::fmul(context->f0, context->f1, context->f1);
/*80206034 00202E34*/ PPC::Runtime::ASM::fmul(context->f1, context->f3, context->f1);
/*80206038 00202E38*/ PPC::Runtime::ASM::fnmsub(context->f0, context->f4, context->f0, context->f2);
/*8020603C 00202E3C*/ PPC::Runtime::ASM::fmul(context->f1, context->f1, context->f0);
/*80206040 00202E40*/ PPC::Runtime::ASM::fmul(context->f0, context->f1, context->f1);
/*80206044 00202E44*/ PPC::Runtime::ASM::fmul(context->f1, context->f3, context->f1);
/*80206048 00202E48*/ PPC::Runtime::ASM::fnmsub(context->f0, context->f4, context->f0, context->f2);
/*8020604C 00202E4C*/ PPC::Runtime::ASM::fmul(context->f0, context->f1, context->f0);
/*80206050 00202E50*/ PPC::Runtime::ASM::fmul(context->f0, context->f4, context->f0);
/*80206054 00202E54*/ PPC::Runtime::ASM::frsp(context->f0, context->f0);
/*80206058 00202E58*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*8020605C 00202E5C*/ PPC::Runtime::ASM::lfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_80206060, 0x80206060) //this is a jump label
/*80206060 00202E60*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa8c, context->r30));
/*80206064 00202E64*/ PPC::Runtime::ASM::fcmpo(cr0, context->f4, context->f0);
/*80206068 00202E68*/ PPC::Runtime::ASM::ble(.L_80206228);
/*8020606C 00202E6C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r1));
/*80206070 00202E70*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x48);
/*80206074 00202E74*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa80, context->r30));
/*80206078 00202E78*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*8020607C 00202E7C*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*80206080 00202E80*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*80206084 00202E84*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r1));
/*80206088 00202E88*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*8020608C 00202E8C*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa84, context->r30));
/*80206090 00202E90*/ PPC::Runtime::ASM::fsubs(context->f0, context->f2, context->f0);
/*80206094 00202E94*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*80206098 00202E98*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa88, context->r30));
/*8020609C 00202E9C*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*802060A0 00202EA0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*802060A4 00202EA4*/ PPC::Runtime::ASM::bl(fn_80062CA4);
/*802060A8 00202EA8*/ PPC::Runtime::ASM::lfs(context->f5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa8c, context->r30));
/*802060AC 00202EAC*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*802060B0 00202EB0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa80, context->r30));
/*802060B4 00202EB4*/ PPC::Runtime::ASM::lfs(context->f3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*802060B8 00202EB8*/ PPC::Runtime::ASM::fmadds(context->f4, context->f1, context->f5, context->f0);
/*802060BC 00202EBC*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*802060C0 00202EC0*/ PPC::Runtime::ASM::lfs(context->f1, STRUCT_FLOAT_COUNT_1805E2318 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*802060C4 00202EC4*/ PPC::Runtime::ASM::stfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*802060C8 00202EC8*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa84, context->r30));
/*802060CC 00202ECC*/ PPC::Runtime::ASM::fmadds(context->f0, context->f3, context->f5, context->f0);
/*802060D0 00202ED0*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*802060D4 00202ED4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa88, context->r30));
/*802060D8 00202ED8*/ PPC::Runtime::ASM::fmadds(context->f0, context->f2, context->f5, context->f0);
/*802060DC 00202EDC*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*802060E0 00202EE0*/ PPC::Runtime::ASM::stfs(context->f4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*802060E4 00202EE4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*802060E8 00202EE8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*802060EC 00202EEC*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb28, context->r30));
/*802060F0 00202EF0*/ PPC::Runtime::ASM::fcmpu(cr0, context->f1, context->f0);
/*802060F4 00202EF4*/ PPC::Runtime::ASM::bne(.L_80206228);
/*802060F8 00202EF8*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E2320 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*802060FC 00202EFC*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x18);
/*80206100 00202F00*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*80206104 00202F04*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb28, context->r30));
/*80206108 00202F08*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x334, context->r30));
/*8020610C 00202F0C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x338, context->r30));
/*80206110 00202F10*/ PPC::Runtime::ASM::stw(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb2c, context->r30));
/*80206114 00202F14*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb30, context->r30));
/*80206118 00202F18*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x33c, context->r30));
/*8020611C 00202F1C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb34, context->r30));
/*80206120 00202F20*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa80, context->r30));
/*80206124 00202F24*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*80206128 00202F28*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*8020612C 00202F2C*/ PPC::Runtime::ASM::fsubs(context->f2, context->f2, context->f0);
/*80206130 00202F30*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*80206134 00202F34*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*80206138 00202F38*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa84, context->r30));
/*8020613C 00202F3C*/ PPC::Runtime::ASM::fsubs(context->f1, context->f2, context->f1);
/*80206140 00202F40*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*80206144 00202F44*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xa88, context->r30));
/*80206148 00202F48*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*8020614C 00202F4C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*80206150 00202F50*/ PPC::Runtime::ASM::bl(fn_80062CA4);
/*80206154 00202F54*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x18);
/*80206158 00202F58*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x340);
/*8020615C 00202F5C*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0x24);
/*80206160 00202F60*/ PPC::Runtime::ASM::bl(fn_80062DD0);
/*80206164 00202F64*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x334, context->r30));
/*80206168 00202F68*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x334);
/*8020616C 00202F6C*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x24);
/*80206170 00202F70*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*80206174 00202F74*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r1));
/*80206178 00202F78*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x338, context->r30));
/*8020617C 00202F7C*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*80206180 00202F80*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x34, context->r1));
/*80206184 00202F84*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x33c, context->r30));
/*80206188 00202F88*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*8020618C 00202F8C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1));
/*80206190 00202F90*/ PPC::Runtime::ASM::bl(fn_80062ECC);
/*80206194 00202F94*/ PPC::Runtime::ASM::fmr(context->f31, context->f1);
/*80206198 00202F98*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x30);
/*8020619C 00202F9C*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x24);
/*802061A0 00202FA0*/ PPC::Runtime::ASM::bl(fn_80062ECC);
/*802061A4 00202FA4*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f31);
/*802061A8 00202FA8*/ PPC::Runtime::ASM::bge(.L_802061D0);
/*802061AC 00202FAC*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*802061B0 00202FB0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*802061B4 00202FB4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r1));
/*802061B8 00202FB8*/ PPC::Runtime::ASM::fneg(context->f2, context->f2);
/*802061BC 00202FBC*/ PPC::Runtime::ASM::fneg(context->f1, context->f1);
/*802061C0 00202FC0*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*802061C4 00202FC4*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*802061C8 00202FC8*/ PPC::Runtime::ASM::stfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x28, context->r1));
/*802061CC 00202FCC*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2c, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_802061D0, 0x802061D0) //this is a jump label
/*802061D0 00202FD0*/ PPC::Runtime::ASM::bl(fn_HSD_Randf);
/*802061D4 00202FD4*/ PPC::Runtime::ASM::lfs(context->f2, STRUCT_FLOAT_COUNT_1805E235C @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*802061D8 00202FD8*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x30);
/*802061DC 00202FDC*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E2348 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*802061E0 00202FE0*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x24);
/*802061E4 00202FE4*/ PPC::Runtime::ASM::addi(context->r5, context->r30, 0xb38);
/*802061E8 00202FE8*/ PPC::Runtime::ASM::fmadds(context->f1, context->f2, context->f1, context->f0);
/*802061EC 00202FEC*/ PPC::Runtime::ASM::bl(fn_8006417C);
/*802061F0 00202FF0*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0xb38);
/*802061F4 00202FF4*/ PPC::Runtime::ASM::bl(fn_801FD0E0);
/*802061F8 00202FF8*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*802061FC 00202FFC*/ PPC::Runtime::ASM::bne(.L_80206210);
/*80206200 00203000*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0xb38);
/*80206204 00203004*/ PPC::Runtime::ASM::mr(context->r4, context->r3);
/*80206208 00203008*/ PPC::Runtime::ASM::bl(fn_80062CA4);
/*8020620C 0020300C*/ PPC::Runtime::ASM::b(.L_80206228);
RUNTIME_PPC_JUMP_LABEL(.L_80206210, 0x80206210) //this is a jump label
/*80206210 00203010*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*80206214 00203014*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*80206218 00203018*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb38, context->r30));
/*8020621C 0020301C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb3c, context->r30));
/*80206220 00203020*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x20, context->r1));
/*80206224 00203024*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb40, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_80206228, 0x80206228) //this is a jump label
/*80206228 00203028*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*8020622C 0020302C*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x54);
/*80206230 00203030*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206234 00203034*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x48);
/*80206238 00203038*/ PPC::Runtime::ASM::lfs(context->f1, STRUCT_FLOAT_COUNT_1805E2360 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*8020623C 0020303C*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0x3c);
/*80206240 00203040*/ PPC::Runtime::ASM::stw(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*80206244 00203044*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E2328 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80206248 00203048*/ PPC::Runtime::ASM::stw(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x54, context->r1));
/*8020624C 0020304C*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*80206250 00203050*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*80206254 00203054*/ PPC::Runtime::ASM::fadds(context->f2, context->f2, context->f1);
/*80206258 00203058*/ PPC::Runtime::ASM::stw(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*8020625C 0020305C*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*80206260 00203060*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x5c, context->r1));
/*80206264 00203064*/ PPC::Runtime::ASM::fsubs(context->f0, context->f1, context->f0);
/*80206268 00203068*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x58, context->r1));
/*8020626C 0020306C*/ PPC::Runtime::ASM::stw(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r1));
/*80206270 00203070*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x50, context->r1));
/*80206274 00203074*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r1));
/*80206278 00203078*/ PPC::Runtime::ASM::bl(fn_800D1AC4);
/*8020627C 0020307C*/ PPC::Runtime::ASM::mr(context->r29, context->r3);
/*80206280 00203080*/ PPC::Runtime::ASM::cmpwi(context->r29, -0x1);
/*80206284 00203084*/ PPC::Runtime::ASM::beq(.L_80206454);
/*80206288 00203088*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x908, context->r30));
/*8020628C 0020308C*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x0);
/*80206290 00203090*/ PPC::Runtime::ASM::bne(.L_8020630C);
/*80206294 00203094*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*80206298 00203098*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*8020629C 0020309C*/ PPC::Runtime::ASM::stw(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*802062A0 002030A0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*802062A4 002030A4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*802062A8 002030A8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*802062AC 002030AC*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*802062B0 002030B0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x95c, context->r30));
/*802062B4 002030B4*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*802062B8 002030B8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*802062BC 002030BC*/ PPC::Runtime::ASM::bl(fn_800D1838);
/*802062C0 002030C0*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*802062C4 002030C4*/ PPC::Runtime::ASM::bne(.L_80206304);
/*802062C8 002030C8*/ PPC::Runtime::ASM::mr(context->r3, context->r29);
/*802062CC 002030CC*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0xc);
/*802062D0 002030D0*/ PPC::Runtime::ASM::bl(fn_800D1860);
/*802062D4 002030D4*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0xc);
/*802062D8 002030D8*/ PPC::Runtime::ASM::bl(fn_801FD0E0);
/*802062DC 002030DC*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*802062E0 002030E0*/ PPC::Runtime::ASM::bne(.L_80206304);
/*802062E4 002030E4*/ PPC::Runtime::ASM::addi(context->r3, context->r30, 0x334);
/*802062E8 002030E8*/ PPC::Runtime::ASM::bl(fn_801FD0E0);
/*802062EC 002030EC*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*802062F0 002030F0*/ PPC::Runtime::ASM::bne(.L_80206304);
/*802062F4 002030F4*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*802062F8 002030F8*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x334);
/*802062FC 002030FC*/ PPC::Runtime::ASM::addi(context->r5, context->r1, 0xc);
/*80206300 00203100*/ PPC::Runtime::ASM::bl(fn_801FD714);
RUNTIME_PPC_JUMP_LABEL(.L_80206304, 0x80206304) //this is a jump label
/*80206304 00203104*/ PPC::Runtime::ASM::li(context->r31, 0x1);
/*80206308 00203108*/ PPC::Runtime::ASM::b(.L_802063A4);
RUNTIME_PPC_JUMP_LABEL(.L_8020630C, 0x8020630C) //this is a jump label
/*8020630C 0020310C*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3c, context->r1));
/*80206310 00203110*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*80206314 00203114*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*80206318 00203118*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*8020631C 0020311C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r30));
/*80206320 00203120*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x1f);
/*80206324 00203124*/ PPC::Runtime::ASM::beq(.L_80206344);
/*80206328 00203128*/ PPC::Runtime::ASM::bge(.L_80206338);
/*8020632C 0020312C*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x7);
/*80206330 00203130*/ PPC::Runtime::ASM::beq(.L_80206344);
/*80206334 00203134*/ PPC::Runtime::ASM::b(.L_8020636C);
RUNTIME_PPC_JUMP_LABEL(.L_80206338, 0x80206338) //this is a jump label
/*80206338 00203138*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x37);
/*8020633C 0020313C*/ PPC::Runtime::ASM::beq(.L_80206344);
/*80206340 00203140*/ PPC::Runtime::ASM::b(.L_8020636C);
RUNTIME_PPC_JUMP_LABEL(.L_80206344, 0x80206344) //this is a jump label
/*80206344 00203144*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206348 00203148*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x95c, context->r30));
/*8020634C 0020314C*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*80206350 00203150*/ PPC::Runtime::ASM::fsubs(context->f0, context->f0, context->f1);
/*80206354 00203154*/ PPC::Runtime::ASM::fcmpo(cr0, context->f0, context->f2);
/*80206358 00203158*/ PPC::Runtime::ASM::bge(.L_80206390);
/*8020635C 0020315C*/ PPC::Runtime::ASM::fadds(context->f0, context->f2, context->f1);
/*80206360 00203160*/ PPC::Runtime::ASM::li(context->r31, 0x1);
/*80206364 00203164*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206368 00203168*/ PPC::Runtime::ASM::b(.L_80206390);
RUNTIME_PPC_JUMP_LABEL(.L_8020636C, 0x8020636C) //this is a jump label
/*8020636C 0020316C*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206370 00203170*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x95c, context->r30));
/*80206374 00203174*/ PPC::Runtime::ASM::lfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x40, context->r1));
/*80206378 00203178*/ PPC::Runtime::ASM::fsubs(context->f0, context->f0, context->f1);
/*8020637C 0020317C*/ PPC::Runtime::ASM::fcmpo(cr0, context->f0, context->f2);
/*80206380 00203180*/ PPC::Runtime::ASM::bge(.L_80206388);
/*80206384 00203184*/ PPC::Runtime::ASM::li(context->r31, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_80206388, 0x80206388) //this is a jump label
/*80206388 00203188*/ PPC::Runtime::ASM::fadds(context->f0, context->f2, context->f1);
/*8020638C 0020318C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_80206390, 0x80206390) //this is a jump label
/*80206390 00203190*/ PPC::Runtime::ASM::lis(context->r4, MemoryOffset_4 @ Get_MemoryOffset_HighBit);
/*80206394 00203194*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*80206398 00203198*/ PPC::Runtime::ASM::addi(context->r5, context->r4, MemoryOffset_4 @ Get_MemoryOffset_LowBit);
/*8020639C 0020319C*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x334);
/*802063A0 002031A0*/ PPC::Runtime::ASM::bl(fn_801FD714);
RUNTIME_PPC_JUMP_LABEL(.L_802063A4, 0x802063A4) //this is a jump label
/*802063A4 002031A4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x48, context->r30));
/*802063A8 002031A8*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*802063AC 002031AC*/ PPC::Runtime::ASM::beq(.L_80206454);
/*802063B0 002031B0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r3));
/*802063B4 002031B4*/ PPC::Runtime::ASM::cmplwi(context->r0, 0x0);
/*802063B8 002031B8*/ PPC::Runtime::ASM::beq(.L_80206454);
/*802063BC 002031BC*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r3));
/* 802063C0 002031C0  54 00 CF FF */ extrwi. context->r0 , context->r0 , 1 , 24
/*802063C4 002031C4*/ PPC::Runtime::ASM::beq(.L_80206454);
/*802063C8 002031C8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r30));
/*802063CC 002031CC*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x1f);
/*802063D0 002031D0*/ PPC::Runtime::ASM::beq(.L_802063F0);
/*802063D4 002031D4*/ PPC::Runtime::ASM::bge(.L_802063E4);
/*802063D8 002031D8*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x7);
/*802063DC 002031DC*/ PPC::Runtime::ASM::beq(.L_802063F0);
/*802063E0 002031E0*/ PPC::Runtime::ASM::b(.L_80206424);
RUNTIME_PPC_JUMP_LABEL(.L_802063E4, 0x802063E4) //this is a jump label
/*802063E4 002031E4*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x37);
/*802063E8 002031E8*/ PPC::Runtime::ASM::beq(.L_802063F0);
/*802063EC 002031EC*/ PPC::Runtime::ASM::b(.L_80206424);
RUNTIME_PPC_JUMP_LABEL(.L_802063F0, 0x802063F0) //this is a jump label
/*802063F0 002031F0*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*802063F4 002031F4*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x550, context->r30));
/*802063F8 002031F8*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*802063FC 002031FC*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*80206400 00203200*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206404 00203204*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x554, context->r30));
/*80206408 00203208*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*8020640C 0020320C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206410 00203210*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*80206414 00203214*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x558, context->r30));
/*80206418 00203218*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*8020641C 0020321C*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*80206420 00203220*/ PPC::Runtime::ASM::b(.L_80206454);
RUNTIME_PPC_JUMP_LABEL(.L_80206424, 0x80206424) //this is a jump label
/*80206424 00203224*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*80206428 00203228*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x538, context->r30));
/*8020642C 0020322C*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*80206430 00203230*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2f8, context->r30));
/*80206434 00203234*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206438 00203238*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x53c, context->r30));
/*8020643C 0020323C*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*80206440 00203240*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2fc, context->r30));
/*80206444 00203244*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
/*80206448 00203248*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x540, context->r30));
/*8020644C 0020324C*/ PPC::Runtime::ASM::fadds(context->f0, context->f1, context->f0);
/*80206450 00203250*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x300, context->r30));
RUNTIME_PPC_JUMP_LABEL(.L_80206454, 0x80206454) //this is a jump label
/*80206454 00203254*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x594, context->r30));
/*80206458 00203258*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x2f8);
/*8020645C 0020325C*/ PPC::Runtime::ASM::lfs(context->f1, STRUCT_FLOAT_COUNT_1805E2318 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80206460 00203260*/ PPC::Runtime::ASM::addi(context->r5, context->r30, 0x334);
/*80206464 00203264*/ PPC::Runtime::ASM::lfs(context->f2, STRUCT_FLOAT_COUNT_1805E231C @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*80206468 00203268*/ PPC::Runtime::ASM::addi(context->r6, context->r30, 0x340);
/*8020646C 0020326C*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*80206470 00203270*/ PPC::Runtime::ASM::bl(fn_80245F70);
/*80206474 00203274*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x594, context->r30));
/*80206478 00203278*/ PPC::Runtime::ASM::bl(fn_802461B4);
/*8020647C 0020327C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x594, context->r30));
/*80206480 00203280*/ PPC::Runtime::ASM::addi(context->r4, context->r30, 0x2f8);
/*80206484 00203284*/ PPC::Runtime::ASM::bl(fn_8024625C);
/*80206488 00203288*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*8020648C 0020328C*/ PPC::Runtime::ASM::psq_l(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x78, context->r1)0, context->qr0);
/*80206490 00203290*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x84, context->r1));
/*80206494 00203294*/ PPC::Runtime::ASM::lfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x70, context->r1));
/*80206498 00203298*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x6c, context->r1));
/*8020649C 0020329C*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x68, context->r1));
/*802064A0 002032A0*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x64, context->r1));
/*802064A4 002032A4*/ PPC::Runtime::ASM::mtlr(context->r0);
/*802064A8 002032A8*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x80);
/*802064AC 002032AC*/ PPC::Runtime::ASM::blr();
}