//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_80395F9C(PPC::Runtime::GCContext* context)
{
/*80395F9C 00392D9C*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r3));
/*80395FA0 00392DA0*/ PPC::Runtime::ASM::addi(context->r0, context->r4, 0x2);
/*80395FA4 00392DA4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r3));
/*80395FA8 00392DA8*/ PPC::Runtime::ASM::blr();
}