//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80112044.hpp"
#include "fn_80114F04.hpp"
#include "fn_80114F04.hpp"



void fn_8012DD14(PPC::Runtime::GCContext* context)
{
/*8012DD14 0012AB14*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*8012DD18 0012AB18*/ PPC::Runtime::ASM::mflr(context->r0);
/*8012DD1C 0012AB1C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8012DD20 0012AB20*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*8012DD24 0012AB24*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*8012DD28 0012AB28*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*8012DD2C 0012AB2C*/ PPC::Runtime::ASM::bl(fn_80112044);
/*8012DD30 0012AB30*/ PPC::Runtime::ASM::addi(context->r30, context->r3, 0xcb8);
/*8012DD34 0012AB34*/ PPC::Runtime::ASM::slwi(context->r31, context->r31, 2);
/*8012DD38 0012AB38*/ PPC::Runtime::ASM::add(context->r3, context->r30, context->r31);
/*8012DD3C 0012AB3C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r3));
/*8012DD40 0012AB40*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*8012DD44 0012AB44*/ PPC::Runtime::ASM::beq(.L_8012DD4C);
/*8012DD48 0012AB48*/ PPC::Runtime::ASM::bl(fn_80114F04);
RUNTIME_PPC_JUMP_LABEL(.L_8012DD4C, 0x8012DD4C) //this is a jump label
/*8012DD4C 0012AB4C*/ PPC::Runtime::ASM::add(context->r3, context->r30, context->r31);
/*8012DD50 0012AB50*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r3));
/*8012DD54 0012AB54*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*8012DD58 0012AB58*/ PPC::Runtime::ASM::beq(.L_8012DD60);
/*8012DD5C 0012AB5C*/ PPC::Runtime::ASM::bl(fn_80114F04);
RUNTIME_PPC_JUMP_LABEL(.L_8012DD60, 0x8012DD60) //this is a jump label
/*8012DD60 0012AB60*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8012DD64 0012AB64*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r1));
/*8012DD68 0012AB68*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*8012DD6C 0012AB6C*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8012DD70 0012AB70*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*8012DD74 0012AB74*/ PPC::Runtime::ASM::blr();
}