//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_802767F8(PPC::Runtime::GCContext* context)
{
/*802767F8 002735F8*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x20, context->r1));
/*802767FC 002735FC*/ PPC::Runtime::ASM::mflr(context->r0);
/*80276800 00273600*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*80276804 00273604*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*80276808 00273608*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*8027680C 0027360C*/ PPC::Runtime::ASM::stw(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*80276810 00273610*/ PPC::Runtime::ASM::stw(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*80276814 00273614*/ PPC::Runtime::ASM::mr(context->r29, context->r3);
/*80276818 00273618*/ PPC::Runtime::ASM::cmpwi(context->r29, -0x1);
/*8027681C 0027361C*/ PPC::Runtime::ASM::lis(context->r3, lbl_804B7F30 @ Get_MemoryOffset_HighBit);
/*80276820 00273620*/ PPC::Runtime::ASM::addi(context->r31, context->r3, lbl_804B7F30 @ Get_MemoryOffset_LowBit);
/*80276824 00273624*/ PPC::Runtime::ASM::ble(.L_80276834);
/*80276828 00273628*/ PPC::Runtime::ASM::cmplwi(context->r29, 0x45);
/*8027682C 0027362C*/ PPC::Runtime::ASM::bge(.L_80276834);
/*80276830 00273630*/ PPC::Runtime::ASM::li(context->r0, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_80276834, 0x80276834) //this is a jump label
/*80276834 00273634*/ PPC::Runtime::ASM::cmpwi(context->r0, 0x0);
/*80276838 00273638*/ PPC::Runtime::ASM::bne(.L_8027684C);
/*8027683C 0027363C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xcbc);
/*80276840 00273640*/ PPC::Runtime::ASM::addi(context->r5, context->r31, 0xd24);
/*80276844 00273644*/ PPC::Runtime::ASM::li(context->r4, 0x2a9);
/*80276848 00273648*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_8027684C, 0x8027684C) //this is a jump label
/*8027684C 0027364C*/ PPC::Runtime::ASM::slwi(context->r0, context->r29, 3);
/*80276850 00273650*/ PPC::Runtime::ASM::addi(context->r30, context->r31, 0x6fc);
/*80276854 00273654*/ PPC::Runtime::ASM::add(context->r30, context->r30, context->r0);
/*80276858 00273658*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r30));
/*8027685C 0027365C*/ PPC::Runtime::ASM::cmpw(context->r0, context->r29);
/*80276860 00273660*/ PPC::Runtime::ASM::beq(.L_80276874);
/*80276864 00273664*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xcbc);
/*80276868 00273668*/ PPC::Runtime::ASM::addi(context->r5, context->r31, 0xd64);
/*8027686C 0027366C*/ PPC::Runtime::ASM::li(context->r4, 0x2ab);
/*80276870 00273670*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_80276874, 0x80276874) //this is a jump label
/*80276874 00273674*/ PPC::Runtime::ASM::lbz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x6, context->r30));
/* 80276878 00273678  54 00 DF FF */ extrwi. context->r0 , context->r0 , 1 , 26
/*8027687C 0027367C*/ PPC::Runtime::ASM::beq(.L_80276888);
/*80276880 00273680*/ PPC::Runtime::ASM::li(context->r3, 0x1);
/*80276884 00273684*/ PPC::Runtime::ASM::b(.L_8027688C);
RUNTIME_PPC_JUMP_LABEL(.L_80276888, 0x80276888) //this is a jump label
/*80276888 00273688*/ PPC::Runtime::ASM::li(context->r3, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_8027688C, 0x8027688C) //this is a jump label
/*8027688C 0027368C*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*80276890 00273690*/ PPC::Runtime::ASM::lwz(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*80276894 00273694*/ PPC::Runtime::ASM::lwz(context->r30, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*80276898 00273698*/ PPC::Runtime::ASM::lwz(context->r29, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*8027689C 0027369C*/ PPC::Runtime::ASM::mtlr(context->r0);
/*802768A0 002736A0*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x20);
/*802768A4 002736A4*/ PPC::Runtime::ASM::blr();
}