//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_800F7A50(PPC::Runtime::GCContext* context)
{
/*800F7A50 000F4850*/ PPC::Runtime::ASM::lhz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r3));
/*800F7A54 000F4854*/ PPC::Runtime::ASM::subfic(context->r0, context->r0, 0xf);
/*800F7A58 000F4858*/ PPC::Runtime::ASM::cntlzw(context->r0, context->r0);
/*800F7A5C 000F485C*/ PPC::Runtime::ASM::srwi(context->r3, context->r0, 5);
/*800F7A60 000F4860*/ PPC::Runtime::ASM::blr();
}