//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "PPCMfmsr.hpp"
#include "fn_803D4BBC.hpp"
#include "fn_8043A850.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "OSReport.hpp"
#include "fn_8043A850.hpp"
#include "OSReport.hpp"



void fn_8043AA00(PPC::Runtime::GCContext* context)
{
/*8043AA00 00437800*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x20, context->r1));
/*8043AA04 00437804*/ PPC::Runtime::ASM::mflr(context->r0);
/*8043AA08 00437808*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*8043AA0C 0043780C*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x20);
/*8043AA10 00437810*/ PPC::Runtime::ASM::bl(_savegpr_27);
/*8043AA14 00437814*/ PPC::Runtime::ASM::lis(context->r7, lbl_80507308 @ Get_MemoryOffset_HighBit);
/*8043AA18 00437818*/ PPC::Runtime::ASM::mr(context->r29, context->r3);
/*8043AA1C 0043781C*/ PPC::Runtime::ASM::addi(context->r31, context->r7, lbl_80507308 @ Get_MemoryOffset_LowBit);
/*8043AA20 00437820*/ PPC::Runtime::ASM::mr(context->r27, context->r4);
/*8043AA24 00437824*/ PPC::Runtime::ASM::mr(context->r28, context->r5);
/*8043AA28 00437828*/ PPC::Runtime::ASM::mr(context->r30, context->r6);
/*8043AA2C 0043782C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x99c);
/*8043AA30 00437830*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AA34 00437834*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AA38 00437838*/ PPC::Runtime::ASM::mr(context->r4, context->r27);
/*8043AA3C 0043783C*/ PPC::Runtime::ASM::mr(context->r5, context->r28);
/*8043AA40 00437840*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x9d4);
/*8043AA44 00437844*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AA48 00437848*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AA4C 0043784C*/ PPC::Runtime::ASM::clrlwi(context->r29, context->r29, 16);
/*8043AA50 00437850*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x9ec);
/*8043AA54 00437854*/ PPC::Runtime::ASM::mr(context->r4, context->r29);
/*8043AA58 00437858*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AA5C 0043785C*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AA60 00437860*/ PPC::Runtime::ASM::cmplwi(context->r29, 0x10);
/*8043AA64 00437864*/ PPC::Runtime::ASM::bgt(.L_8043AD84);
/*8043AA68 00437868*/ PPC::Runtime::ASM::lis(context->r3, jumptable_80508204 @ Get_MemoryOffset_HighBit);
/*8043AA6C 0043786C*/ PPC::Runtime::ASM::slwi(context->r0, context->r29, 2);
/*8043AA70 00437870*/ PPC::Runtime::ASM::addi(context->r3, context->r3, jumptable_80508204 @ Get_MemoryOffset_LowBit);
/*8043AA74 00437874*/ PPC::Runtime::ASM::lwzx(context->r0, context->r3, context->r0);
/*8043AA78 00437878*/ PPC::Runtime::ASM::mtctr(context->r0);
/*8043AA7C 0043787C*/ PPC::Runtime::ASM::bctr();
/*8043AA80 00437880*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0x9f8);
/*8043AA84 00437884*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AA88 00437888*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AA8C 0043788C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AA90 00437890*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xa08);
/*8043AA94 00437894*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AA98 00437898*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AA9C 0043789C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AAA0 004378A0*/ PPC::Runtime::ASM::li(context->r3, MemoryOffset_397 @ Get_MemoryOffset_SDA21);
/*8043AAA4 004378A4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AAA8 004378A8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AAAC 004378AC*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x198, context->r30));
/*8043AAB0 004378B0*/ PPC::Runtime::ASM::mr(context->r5, context->r28);
/*8043AAB4 004378B4*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xa1c);
/*8043AAB8 004378B8*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AABC 004378BC*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AAC0 004378C0*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r27, 0, 6, 6);
/*8043AAC4 004378C4*/ PPC::Runtime::ASM::beq(.L_8043AAD8);
/*8043AAC8 004378C8*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xa7c);
/*8043AACC 004378CC*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AAD0 004378D0*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AAD4 004378D4*/ PPC::Runtime::ASM::b(.L_8043AAE4);
RUNTIME_PPC_JUMP_LABEL(.L_8043AAD8, 0x8043AAD8) //this is a jump label
/*8043AAD8 004378D8*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xa90);
/*8043AADC 004378DC*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AAE0 004378E0*/ PPC::Runtime::ASM::bl(OSReport);
RUNTIME_PPC_JUMP_LABEL(.L_8043AAE4, 0x8043AAE4) //this is a jump label
/*8043AAE4 004378E4*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r27, 0, 1, 1);
/*8043AAE8 004378E8*/ PPC::Runtime::ASM::beq(.L_8043AAF8);
/*8043AAEC 004378EC*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xaa4);
/*8043AAF0 004378F0*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AAF4 004378F4*/ PPC::Runtime::ASM::bl(OSReport);
RUNTIME_PPC_JUMP_LABEL(.L_8043AAF8, 0x8043AAF8) //this is a jump label
/*8043AAF8 004378F8*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r27, 0, 4, 4);
/*8043AAFC 004378FC*/ PPC::Runtime::ASM::beq(.L_8043AB0C);
/*8043AB00 00437900*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xad0);
/*8043AB04 00437904*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB08 00437908*/ PPC::Runtime::ASM::bl(OSReport);
RUNTIME_PPC_JUMP_LABEL(.L_8043AB0C, 0x8043AB0C) //this is a jump label
/*8043AB0C 0043790C*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r27, 0, 9, 9);
/*8043AB10 00437910*/ PPC::Runtime::ASM::beq(.L_8043AD90);
/*8043AB14 00437914*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xb08);
/*8043AB18 00437918*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB1C 0043791C*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AB20 00437920*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AB24 00437924*/ PPC::Runtime::ASM::li(context->r3, MemoryOffset_396 @ Get_MemoryOffset_SDA21);
/*8043AB28 00437928*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB2C 0043792C*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AB30 00437930*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x198, context->r30));
/*8043AB34 00437934*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xb1c);
/*8043AB38 00437938*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB3C 0043793C*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AB40 00437940*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x19c, context->r30));
/*8043AB44 00437944*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 1, 1);
/*8043AB48 00437948*/ PPC::Runtime::ASM::beq(.L_8043AB58);
/*8043AB4C 0043794C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xb68);
/*8043AB50 00437950*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB54 00437954*/ PPC::Runtime::ASM::bl(OSReport);
RUNTIME_PPC_JUMP_LABEL(.L_8043AB58, 0x8043AB58) //this is a jump label
/*8043AB58 00437958*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x19c, context->r30));
/*8043AB5C 0043795C*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 3, 3);
/*8043AB60 00437960*/ PPC::Runtime::ASM::beq(.L_8043AB70);
/*8043AB64 00437964*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xb94);
/*8043AB68 00437968*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB6C 0043796C*/ PPC::Runtime::ASM::bl(OSReport);
RUNTIME_PPC_JUMP_LABEL(.L_8043AB70, 0x8043AB70) //this is a jump label
/*8043AB70 00437970*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x19c, context->r30));
/*8043AB74 00437974*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 4, 4);
/*8043AB78 00437978*/ PPC::Runtime::ASM::beq(.L_8043AD90);
/*8043AB7C 0043797C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xba8);
/*8043AB80 00437980*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB84 00437984*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AB88 00437988*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AB8C 0043798C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xbe0);
/*8043AB90 00437990*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AB94 00437994*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AB98 00437998*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AB9C 0043799C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xbf8);
/*8043ABA0 004379A0*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ABA4 004379A4*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ABA8 004379A8*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x198, context->r30));
/*8043ABAC 004379AC*/ PPC::Runtime::ASM::mr(context->r5, context->r28);
/*8043ABB0 004379B0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xc08);
/*8043ABB4 004379B4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ABB8 004379B8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ABBC 004379BC*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043ABC0 004379C0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xc6c);
/*8043ABC4 004379C4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ABC8 004379C8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ABCC 004379CC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x19c, context->r30));
/*8043ABD0 004379D0*/ PPC::Runtime::ASM::li(context->r5, MemoryOffset_394 @ Get_MemoryOffset_SDA21);
/*8043ABD4 004379D4*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r3, 0, 15, 15);
/*8043ABD8 004379D8*/ PPC::Runtime::ASM::beq(.L_8043ABE0);
/*8043ABDC 004379DC*/ PPC::Runtime::ASM::li(context->r5, MemoryOffset_395 @ Get_MemoryOffset_SDA21);
RUNTIME_PPC_JUMP_LABEL(.L_8043ABE0, 0x8043ABE0) //this is a jump label
/*8043ABE0 004379E0*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r3, 0, 11, 11);
/*8043ABE4 004379E4*/ PPC::Runtime::ASM::beq(.L_8043ABF0);
/*8043ABE8 004379E8*/ PPC::Runtime::ASM::addi(context->r4, context->r31, 0xc78);
/*8043ABEC 004379EC*/ PPC::Runtime::ASM::b(.L_8043AC24);
RUNTIME_PPC_JUMP_LABEL(.L_8043ABF0, 0x8043ABF0) //this is a jump label
/*8043ABF0 004379F0*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r3, 0, 12, 12);
/*8043ABF4 004379F4*/ PPC::Runtime::ASM::beq(.L_8043AC00);
/*8043ABF8 004379F8*/ PPC::Runtime::ASM::addi(context->r4, context->r31, 0xca8);
/*8043ABFC 004379FC*/ PPC::Runtime::ASM::b(.L_8043AC24);
RUNTIME_PPC_JUMP_LABEL(.L_8043AC00, 0x8043AC00) //this is a jump label
/*8043AC00 00437A00*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r3, 0, 13, 13);
/*8043AC04 00437A04*/ PPC::Runtime::ASM::beq(.L_8043AC10);
/*8043AC08 00437A08*/ PPC::Runtime::ASM::addi(context->r4, context->r31, 0xcbc);
/*8043AC0C 00437A0C*/ PPC::Runtime::ASM::b(.L_8043AC24);
RUNTIME_PPC_JUMP_LABEL(.L_8043AC10, 0x8043AC10) //this is a jump label
/*8043AC10 00437A10*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r3, 0, 14, 14);
/*8043AC14 00437A14*/ PPC::Runtime::ASM::beq(.L_8043AC20);
/*8043AC18 00437A18*/ PPC::Runtime::ASM::addi(context->r4, context->r31, 0xcd4);
/*8043AC1C 00437A1C*/ PPC::Runtime::ASM::b(.L_8043AC24);
RUNTIME_PPC_JUMP_LABEL(.L_8043AC20, 0x8043AC20) //this is a jump label
/*8043AC20 00437A20*/ PPC::Runtime::ASM::addi(context->r4, context->r31, 0xcec);
RUNTIME_PPC_JUMP_LABEL(.L_8043AC24, 0x8043AC24) //this is a jump label
/*8043AC24 00437A24*/ PPC::Runtime::ASM::lwz(context->r6, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x198, context->r30));
/*8043AC28 00437A28*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd10);
/*8043AC2C 00437A2C*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AC30 00437A30*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AC34 00437A34*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x19c, context->r30));
/*8043AC38 00437A38*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 11, 11);
/*8043AC3C 00437A3C*/ PPC::Runtime::ASM::beq(.L_8043AD90);
/*8043AC40 00437A40*/ PPC::Runtime::ASM::bl(PPCMfmsr);
/*8043AC44 00437A44*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*8043AC48 00437A48*/ PPC::Runtime::ASM::beq(.L_8043AC54);
/*8043AC4C 00437A4C*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*8043AC50 00437A50*/ PPC::Runtime::ASM::bl(fn_803D4BBC);
RUNTIME_PPC_JUMP_LABEL(.L_8043AC54, 0x8043AC54) //this is a jump label
/*8043AC54 00437A54*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*8043AC58 00437A58*/ PPC::Runtime::ASM::bl(fn_8043A850);
/*8043AC5C 00437A5C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AC60 00437A60*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd30);
/*8043AC64 00437A64*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AC68 00437A68*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AC6C 00437A6C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AC70 00437A70*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd44);
/*8043AC74 00437A74*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AC78 00437A78*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AC7C 00437A7C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AC80 00437A80*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd54);
/*8043AC84 00437A84*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AC88 00437A88*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AC8C 00437A8C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AC90 00437A90*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd64);
/*8043AC94 00437A94*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AC98 00437A98*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AC9C 00437A9C*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043ACA0 00437AA0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd70);
/*8043ACA4 00437AA4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ACA8 00437AA8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ACAC 00437AAC*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043ACB0 00437AB0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd88);
/*8043ACB4 00437AB4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ACB8 00437AB8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ACBC 00437ABC*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043ACC0 00437AC0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xd98);
/*8043ACC4 00437AC4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ACC8 00437AC8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ACCC 00437ACC*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043ACD0 00437AD0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xdac);
/*8043ACD4 00437AD4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ACD8 00437AD8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ACDC 00437ADC*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043ACE0 00437AE0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xdc4);
/*8043ACE4 00437AE4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ACE8 00437AE8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ACEC 00437AEC*/ PPC::Runtime::ASM::mr(context->r4, context->r28);
/*8043ACF0 00437AF0*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xdd4);
/*8043ACF4 00437AF4*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043ACF8 00437AF8*/ PPC::Runtime::ASM::bl(OSReport);
/*8043ACFC 00437AFC*/ PPC::Runtime::ASM::cmplwi(context->r27, 0x10);
/*8043AD00 00437B00*/ PPC::Runtime::ASM::bgt(.L_8043AD90);
/*8043AD04 00437B04*/ PPC::Runtime::ASM::lis(context->r3, jumptable_805081C0 @ Get_MemoryOffset_HighBit);
/*8043AD08 00437B08*/ PPC::Runtime::ASM::slwi(context->r0, context->r27, 2);
/*8043AD0C 00437B0C*/ PPC::Runtime::ASM::addi(context->r3, context->r3, jumptable_805081C0 @ Get_MemoryOffset_LowBit);
/*8043AD10 00437B10*/ PPC::Runtime::ASM::lwzx(context->r0, context->r3, context->r0);
/*8043AD14 00437B14*/ PPC::Runtime::ASM::mtctr(context->r0);
/*8043AD18 00437B18*/ PPC::Runtime::ASM::bctr();
/*8043AD1C 00437B1C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xe00);
/*8043AD20 00437B20*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD24 00437B24*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AD28 00437B28*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AD2C 00437B2C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xe20);
/*8043AD30 00437B30*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD34 00437B34*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AD38 00437B38*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AD3C 00437B3C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xe40);
/*8043AD40 00437B40*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD44 00437B44*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AD48 00437B48*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AD4C 00437B4C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xe60);
/*8043AD50 00437B50*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD54 00437B54*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AD58 00437B58*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AD5C 00437B5C*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xe80);
/*8043AD60 00437B60*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD64 00437B64*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AD68 00437B68*/ PPC::Runtime::ASM::b(.L_8043AD90);
/*8043AD6C 00437B6C*/ PPC::Runtime::ASM::li(context->r3, MemoryOffset_393 @ Get_MemoryOffset_SDA21);
/*8043AD70 00437B70*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD74 00437B74*/ PPC::Runtime::ASM::bl(OSReport);
/*8043AD78 00437B78*/ PPC::Runtime::ASM::mr(context->r3, context->r30);
/*8043AD7C 00437B7C*/ PPC::Runtime::ASM::bl(fn_8043A850);
/*8043AD80 00437B80*/ PPC::Runtime::ASM::b(.L_8043AD90);
RUNTIME_PPC_JUMP_LABEL(.L_8043AD84, 0x8043AD84) //this is a jump label
/*8043AD84 00437B84*/ PPC::Runtime::ASM::addi(context->r3, context->r31, 0xeac);
/*8043AD88 00437B88*/ PPC::Runtime::ASM::crclr(context->cr1eq);
/*8043AD8C 00437B8C*/ PPC::Runtime::ASM::bl(OSReport);
RUNTIME_PPC_JUMP_LABEL(.L_8043AD90, 0x8043AD90) //this is a jump label
/*8043AD90 00437B90*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x20);
/*8043AD94 00437B94*/ PPC::Runtime::ASM::bl(_restgpr_27);
/*8043AD98 00437B98*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x24, context->r1));
/*8043AD9C 00437B9C*/ PPC::Runtime::ASM::mtlr(context->r0);
/*8043ADA0 00437BA0*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x20);
/*8043ADA4 00437BA4*/ PPC::Runtime::ASM::blr();
}