//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_800D3870.hpp"
#include "fn_800D39A0.hpp"
#include "fn_801E4CF4.hpp"
#include "fn_800D3A88.hpp"
#include "fn_800D3870.hpp"
#include "fn_800D3B8C.hpp"
#include "fn_801E4CF4.hpp"
#include "fn_800D3C74.hpp"
#include "fn_800D3870.hpp"



void fn_801E4960(PPC::Runtime::GCContext* context)
{
/*801E4960 001E1760*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x40, context->r1));
/*801E4964 001E1764*/ PPC::Runtime::ASM::mflr(context->r0);
/*801E4968 001E1768*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*801E496C 001E176C*/ PPC::Runtime::ASM::stfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r1));
/*801E4970 001E1770*/ PPC::Runtime::ASM::psq_st(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1)0, context->qr0);
/*801E4974 001E1774*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*801E4978 001E1778*/ PPC::Runtime::ASM::bl(_savegpr_27);
/*801E497C 001E177C*/ PPC::Runtime::ASM::mr(context->r28, context->r4);
/*801E4980 001E1780*/ PPC::Runtime::ASM::fmr(context->f31, context->f1);
/*801E4984 001E1784*/ PPC::Runtime::ASM::mr(context->r27, context->r3);
/*801E4988 001E1788*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*801E498C 001E178C*/ PPC::Runtime::ASM::mr(context->r29, context->r5);
/*801E4990 001E1790*/ PPC::Runtime::ASM::mr(context->r30, context->r6);
/*801E4994 001E1794*/ PPC::Runtime::ASM::bl(fn_800D3870);
/*801E4998 001E1798*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*801E499C 001E179C*/ PPC::Runtime::ASM::fmadds(context->f31, context->f0, context->f1, context->f31);
RUNTIME_PPC_JUMP_LABEL(.L_801E49A0, 0x801E49A0) //this is a jump label
/*801E49A0 001E17A0*/ PPC::Runtime::ASM::fcmpo(cr0, context->f31, context->f1);
/*801E49A4 001E17A4*/ PPC::Runtime::ASM::ble(.L_801E4A48);
/*801E49A8 001E17A8*/ PPC::Runtime::ASM::fsubs(context->f31, context->f31, context->f1);
/*801E49AC 001E17AC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E49B0 001E17B0*/ PPC::Runtime::ASM::bl(fn_800D39A0);
/*801E49B4 001E17B4*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*801E49B8 001E17B8*/ PPC::Runtime::ASM::cmpwi(context->r31, -0x1);
/*801E49BC 001E17BC*/ PPC::Runtime::ASM::bne(.L_801E49DC);
/*801E49C0 001E17C0*/ PPC::Runtime::ASM::cmpwi(context->r30, 0x0);
/*801E49C4 001E17C4*/ PPC::Runtime::ASM::beq(.L_801E49D4);
/*801E49C8 001E17C8*/ PPC::Runtime::ASM::fmr(context->f1, context->f31);
/*801E49CC 001E17CC*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*801E49D0 001E17D0*/ PPC::Runtime::ASM::bl(fn_801E4CF4);
RUNTIME_PPC_JUMP_LABEL(.L_801E49D4, 0x801E49D4) //this is a jump label
/*801E49D4 001E17D4*/ PPC::Runtime::ASM::li(context->r3, 0x1);
/*801E49D8 001E17D8*/ PPC::Runtime::ASM::b(.L_801E4AE0);
RUNTIME_PPC_JUMP_LABEL(.L_801E49DC, 0x801E49DC) //this is a jump label
/*801E49DC 001E17DC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E49E0 001E17E0*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x8);
/*801E49E4 001E17E4*/ PPC::Runtime::ASM::bl(fn_800D3A88);
/*801E49E8 001E17E8*/ PPC::Runtime::ASM::lwz(context->r3, STRUCT_BYTE4_COUNT_1805DD848 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801E49EC 001E17EC*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x668, context->r27));
/*801E49F0 001E17F0*/ PPC::Runtime::ASM::lfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r3));
/*801E49F4 001E17F4*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*801E49F8 001E17F8*/ PPC::Runtime::ASM::cror(eq, gt, eq);
/*801E49FC 001E17FC*/ PPC::Runtime::ASM::bne(.L_801E4A08);
/*801E4A00 001E1800*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*801E4A04 001E1804*/ PPC::Runtime::ASM::b(.L_801E4A24);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A08, 0x801E4A08) //this is a jump label
/*801E4A08 001E1808*/ PPC::Runtime::ASM::fneg(context->f0, context->f0);
/*801E4A0C 001E180C*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*801E4A10 001E1810*/ PPC::Runtime::ASM::cror(eq, lt, eq);
/*801E4A14 001E1814*/ PPC::Runtime::ASM::bne(.L_801E4A20);
/*801E4A18 001E1818*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*801E4A1C 001E181C*/ PPC::Runtime::ASM::b(.L_801E4A24);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A20, 0x801E4A20) //this is a jump label
/*801E4A20 001E1820*/ PPC::Runtime::ASM::li(context->r0, -0x1);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A24, 0x801E4A24) //this is a jump label
/*801E4A24 001E1824*/ PPC::Runtime::ASM::cmpwi(context->r0, -0x1);
/*801E4A28 001E1828*/ PPC::Runtime::ASM::bne(.L_801E4A38);
/*801E4A2C 001E182C*/ PPC::Runtime::ASM::slwi(context->r0, context->r31, 2);
/*801E4A30 001E1830*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x8);
/*801E4A34 001E1834*/ PPC::Runtime::ASM::lwzx(context->r0, context->r3, context->r0);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A38, 0x801E4A38) //this is a jump label
/*801E4A38 001E1838*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E4A3C 001E183C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E4A40 001E1840*/ PPC::Runtime::ASM::bl(fn_800D3870);
/*801E4A44 001E1844*/ PPC::Runtime::ASM::b(.L_801E49A0);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A48, 0x801E4A48) //this is a jump label
/*801E4A48 001E1848*/ PPC::Runtime::ASM::lfs(context->f2, STRUCT_FLOAT_COUNT_1805E1DD0 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801E4A4C 001E184C*/ PPC::Runtime::ASM::fcmpo(cr0, context->f31, context->f2);
/*801E4A50 001E1850*/ PPC::Runtime::ASM::bge(.L_801E4AB0);
/*801E4A54 001E1854*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E4A58 001E1858*/ PPC::Runtime::ASM::bl(fn_800D3B8C);
/*801E4A5C 001E185C*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*801E4A60 001E1860*/ PPC::Runtime::ASM::cmpwi(context->r31, -0x1);
/*801E4A64 001E1864*/ PPC::Runtime::ASM::bne(.L_801E4A84);
/*801E4A68 001E1868*/ PPC::Runtime::ASM::cmpwi(context->r30, 0x0);
/*801E4A6C 001E186C*/ PPC::Runtime::ASM::beq(.L_801E4A7C);
/*801E4A70 001E1870*/ PPC::Runtime::ASM::fmr(context->f1, context->f31);
/*801E4A74 001E1874*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*801E4A78 001E1878*/ PPC::Runtime::ASM::bl(fn_801E4CF4);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A7C, 0x801E4A7C) //this is a jump label
/*801E4A7C 001E187C*/ PPC::Runtime::ASM::li(context->r3, 0x1);
/*801E4A80 001E1880*/ PPC::Runtime::ASM::b(.L_801E4AE0);
RUNTIME_PPC_JUMP_LABEL(.L_801E4A84, 0x801E4A84) //this is a jump label
/*801E4A84 001E1884*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E4A88 001E1888*/ PPC::Runtime::ASM::addi(context->r4, context->r1, 0x8);
/*801E4A8C 001E188C*/ PPC::Runtime::ASM::bl(fn_800D3C74);
/*801E4A90 001E1890*/ PPC::Runtime::ASM::slwi(context->r0, context->r31, 2);
/*801E4A94 001E1894*/ PPC::Runtime::ASM::addi(context->r3, context->r1, 0x8);
/*801E4A98 001E1898*/ PPC::Runtime::ASM::lwzx(context->r0, context->r3, context->r0);
/*801E4A9C 001E189C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E4AA0 001E18A0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r28));
/*801E4AA4 001E18A4*/ PPC::Runtime::ASM::bl(fn_800D3870);
/*801E4AA8 001E18A8*/ PPC::Runtime::ASM::fadds(context->f31, context->f31, context->f1);
/*801E4AAC 001E18AC*/ PPC::Runtime::ASM::b(.L_801E49A0);
RUNTIME_PPC_JUMP_LABEL(.L_801E4AB0, 0x801E4AB0) //this is a jump label
/*801E4AB0 001E18B0*/ PPC::Runtime::ASM::fdivs(context->f0, context->f31, context->f1);
/*801E4AB4 001E18B4*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*801E4AB8 001E18B8*/ PPC::Runtime::ASM::lfs(context->f1, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*801E4ABC 001E18BC*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f2);
/*801E4AC0 001E18C0*/ PPC::Runtime::ASM::bge(.L_801E4ACC);
/*801E4AC4 001E18C4*/ PPC::Runtime::ASM::stfs(context->f2, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
/*801E4AC8 001E18C8*/ PPC::Runtime::ASM::b(.L_801E4ADC);
RUNTIME_PPC_JUMP_LABEL(.L_801E4ACC, 0x801E4ACC) //this is a jump label
/*801E4ACC 001E18CC*/ PPC::Runtime::ASM::lfs(context->f0, STRUCT_FLOAT_COUNT_1805E1DD8 @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*801E4AD0 001E18D0*/ PPC::Runtime::ASM::fcmpo(cr0, context->f1, context->f0);
/*801E4AD4 001E18D4*/ PPC::Runtime::ASM::ble(.L_801E4ADC);
/*801E4AD8 001E18D8*/ PPC::Runtime::ASM::stfs(context->f0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r29));
RUNTIME_PPC_JUMP_LABEL(.L_801E4ADC, 0x801E4ADC) //this is a jump label
/*801E4ADC 001E18DC*/ PPC::Runtime::ASM::li(context->r3, 0x0);
RUNTIME_PPC_JUMP_LABEL(.L_801E4AE0, 0x801E4AE0) //this is a jump label
/*801E4AE0 001E18E0*/ PPC::Runtime::ASM::psq_l(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x38, context->r1)0, context->qr0);
/*801E4AE4 001E18E4*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x30);
/*801E4AE8 001E18E8*/ PPC::Runtime::ASM::lfd(context->f31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x30, context->r1));
/*801E4AEC 001E18EC*/ PPC::Runtime::ASM::bl(_restgpr_27);
/*801E4AF0 001E18F0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*801E4AF4 001E18F4*/ PPC::Runtime::ASM::mtlr(context->r0);
/*801E4AF8 001E18F8*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x40);
/*801E4AFC 001E18FC*/ PPC::Runtime::ASM::blr();
}