//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_80015400.hpp"



void fn_EnableMetroTRKInterrupts(PPC::Runtime::GCContext* context)
{
/*800095A0 000063A0*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x10, context->r1));
/*800095A4 000063A4*/ PPC::Runtime::ASM::mflr(context->r0);
/*800095A8 000063A8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*800095AC 000063AC*/ PPC::Runtime::ASM::bl(fn_80015400);
/*800095B0 000063B0*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*800095B4 000063B4*/ PPC::Runtime::ASM::mtlr(context->r0);
/*800095B8 000063B8*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x10);
/*800095BC 000063BC*/ PPC::Runtime::ASM::blr();
}