//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



void fn_GXSetChanMatColor(PPC::Runtime::GCContext* context)
{
/*803CD3AC 003CA1AC*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x3);
/*803CD3B0 003CA1B0*/ PPC::Runtime::ASM::beq(.L_803CD438);
/*803CD3B4 003CA1B4*/ PPC::Runtime::ASM::bge(.L_803CD3D0);
/*803CD3B8 003CA1B8*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x1);
/*803CD3BC 003CA1BC*/ PPC::Runtime::ASM::beq(.L_803CD400);
/*803CD3C0 003CA1C0*/ PPC::Runtime::ASM::bge(.L_803CD420);
/*803CD3C4 003CA1C4*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x0);
/*803CD3C8 003CA1C8*/ PPC::Runtime::ASM::bge(.L_803CD3E0);
/*803CD3CC 003CA1CC*/ PPC::Runtime::ASM::blr();
RUNTIME_PPC_JUMP_LABEL(.L_803CD3D0, 0x803CD3D0) //this is a jump label
/*803CD3D0 003CA1D0*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x5);
/*803CD3D4 003CA1D4*/ PPC::Runtime::ASM::beq(.L_803CD45C);
/*803CD3D8 003CA1D8*/ PPC::Runtime::ASM::bgelr();
/*803CD3DC 003CA1DC*/ PPC::Runtime::ASM::b(.L_803CD450);
RUNTIME_PPC_JUMP_LABEL(.L_803CD3E0, 0x803CD3E0) //this is a jump label
/*803CD3E0 003CA1E0*/ PPC::Runtime::ASM::lwz(context->r3, gx @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803CD3E4 003CA1E4*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803CD3E8 003CA1E8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803CD3EC 003CA1EC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb0, context->r3));
/*803CD3F0 003CA1F0*/ PPC::Runtime::ASM::clrrwi(context->r0, context->r0, 8);
/*803CD3F4 003CA1F4*/ PPC::Runtime::ASM::mr(context->r7, context->r0);
/*803CD3F8 003CA1F8*/ PPC::Runtime::ASM::rlwimi(context->r7, context->r3, 0, 24, 31);
/*803CD3FC 003CA1FC*/ PPC::Runtime::ASM::b(.L_803CD46C);
RUNTIME_PPC_JUMP_LABEL(.L_803CD400, 0x803CD400) //this is a jump label
/*803CD400 003CA200*/ PPC::Runtime::ASM::lwz(context->r3, gx @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803CD404 003CA204*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*803CD408 003CA208*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803CD40C 003CA20C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb4, context->r3));
/*803CD410 003CA210*/ PPC::Runtime::ASM::clrrwi(context->r0, context->r0, 8);
/*803CD414 003CA214*/ PPC::Runtime::ASM::mr(context->r7, context->r0);
/*803CD418 003CA218*/ PPC::Runtime::ASM::rlwimi(context->r7, context->r3, 0, 24, 31);
/*803CD41C 003CA21C*/ PPC::Runtime::ASM::b(.L_803CD46C);
RUNTIME_PPC_JUMP_LABEL(.L_803CD420, 0x803CD420) //this is a jump label
/*803CD420 003CA220*/ PPC::Runtime::ASM::lwz(context->r3, gx @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803CD424 003CA224*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803CD428 003CA228*/ PPC::Runtime::ASM::lbz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3, context->r4));
/*803CD42C 003CA22C*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb0, context->r3));
/*803CD430 003CA230*/ PPC::Runtime::ASM::rlwimi(context->r7, context->r3, 0, 0, 23);
/*803CD434 003CA234*/ PPC::Runtime::ASM::b(.L_803CD46C);
RUNTIME_PPC_JUMP_LABEL(.L_803CD438, 0x803CD438) //this is a jump label
/*803CD438 003CA238*/ PPC::Runtime::ASM::lwz(context->r3, gx @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803CD43C 003CA23C*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*803CD440 003CA240*/ PPC::Runtime::ASM::lbz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x3, context->r4));
/*803CD444 003CA244*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb4, context->r3));
/*803CD448 003CA248*/ PPC::Runtime::ASM::rlwimi(context->r7, context->r3, 0, 0, 23);
/*803CD44C 003CA24C*/ PPC::Runtime::ASM::b(.L_803CD46C);
RUNTIME_PPC_JUMP_LABEL(.L_803CD450, 0x803CD450) //this is a jump label
/*803CD450 003CA250*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803CD454 003CA254*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803CD458 003CA258*/ PPC::Runtime::ASM::b(.L_803CD46C);
RUNTIME_PPC_JUMP_LABEL(.L_803CD45C, 0x803CD45C) //this is a jump label
/*803CD45C 003CA25C*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r4));
/*803CD460 003CA260*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*803CD464 003CA264*/ PPC::Runtime::ASM::b(.L_803CD46C);
/*803CD468 003CA268*/ PPC::Runtime::ASM::blr();
RUNTIME_PPC_JUMP_LABEL(.L_803CD46C, 0x803CD46C) //this is a jump label
/*803CD46C 003CA26C*/ PPC::Runtime::ASM::li(context->r0, 0x10);
/*803CD470 003CA270*/ PPC::Runtime::ASM::lwz(context->r4, gx @ Get_MemoryOffset_SDA21 ( context->r0 ));
/*803CD474 003CA274*/ PPC::Runtime::ASM::lis(context->r6, 0xcc01);
/*803CD478 003CA278*/ PPC::Runtime::ASM::stb(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x8000, context->r6));
/*803CD47C 003CA27C*/ PPC::Runtime::ASM::addi(context->r3, context->r5, 0x100c);
/*803CD480 003CA280*/ PPC::Runtime::ASM::slwi(context->r0, context->r5, 2);
/*803CD484 003CA284*/ PPC::Runtime::ASM::stw(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x8000, context->r6));
/*803CD488 003CA288*/ PPC::Runtime::ASM::li(context->r5, 0x1);
/*803CD48C 003CA28C*/ PPC::Runtime::ASM::add(context->r3, context->r4, context->r0);
/*803CD490 003CA290*/ PPC::Runtime::ASM::stw(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x8000, context->r6));
/*803CD494 003CA294*/ PPC::Runtime::ASM::sth(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x2, context->r4));
/*803CD498 003CA298*/ PPC::Runtime::ASM::stw(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xb0, context->r3));
/*803CD49C 003CA29C*/ PPC::Runtime::ASM::blr();
}