//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn___assert.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"
#include "fn_HSD_TExpCnst.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpOrder.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpGetType.hpp"
#include "fn_HSD_TExpGetType.hpp"
#include "fn_HSD_TExpTev.hpp"
#include "fn_HSD_TExpColorOp.hpp"
#include "fn_HSD_TExpColorIn.hpp"
#include "fn_HSD_TExpAlphaOp.hpp"
#include "fn_HSD_TExpAlphaIn.hpp"



void fn_MObjMakeTExp(PPC::Runtime::GCContext* context)
{
/*803FA0B4 003F6EB4*/ PPC::Runtime::ASM::stwu(context->r1, PPC_RUNTIME_GET_MEMORY_OFFSET_NEG_HEX_LITERAL_OF_SINGLE_REGISTER(-0x40, context->r1));
/*803FA0B8 003F6EB8*/ PPC::Runtime::ASM::mflr(context->r0);
/*803FA0BC 003F6EBC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*803FA0C0 003F6EC0*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x40);
/*803FA0C4 003F6EC4*/ PPC::Runtime::ASM::bl(_savegpr_24);
/* 803FA0C8 003F6EC8  7C BB 2B 79 */ mr. context->r27 , context->r5
/*803FA0CC 003F6ECC*/ PPC::Runtime::ASM::mr(context->r25, context->r3);
/*803FA0D0 003F6ED0*/ PPC::Runtime::ASM::mr(context->r26, context->r4);
/*803FA0D4 003F6ED4*/ PPC::Runtime::ASM::li(context->r30, 0x0);
/*803FA0D8 003F6ED8*/ PPC::Runtime::ASM::li(context->r29, 0x0);
/*803FA0DC 003F6EDC*/ PPC::Runtime::ASM::bne(.L_803FA0F0);
/*803FA0E0 003F6EE0*/ PPC::Runtime::ASM::li(context->r3, MemoryOffset_598 @ Get_MemoryOffset_SDA21);
/*803FA0E4 003F6EE4*/ PPC::Runtime::ASM::li(context->r4, 0x18b);
/*803FA0E8 003F6EE8*/ PPC::Runtime::ASM::li(context->r5, MemoryOffset_597 @ Get_MemoryOffset_SDA21);
/*803FA0EC 003F6EEC*/ PPC::Runtime::ASM::bl(fn___assert);
RUNTIME_PPC_JUMP_LABEL(.L_803FA0F0, 0x803FA0F0) //this is a jump label
/*803FA0F0 003F6EF0*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA0F4 003F6EF4*/ PPC::Runtime::ASM::mr(context->r3, context->r26);
/*803FA0F8 003F6EF8*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r27));
/*803FA0FC 003F6EFC*/ PPC::Runtime::ASM::b(.L_803FA118);
RUNTIME_PPC_JUMP_LABEL(.L_803FA100, 0x803FA100) //this is a jump label
/*803FA100 003F6F00*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r3));
/*803FA104 003F6F04*/ PPC::Runtime::ASM::clrlwi(context->r0, context->r0, 28);
/*803FA108 003F6F08*/ PPC::Runtime::ASM::cmplwi(context->r0, 0x4);
/*803FA10C 003F6F0C*/ PPC::Runtime::ASM::bne(.L_803FA114);
/*803FA110 003F6F10*/ PPC::Runtime::ASM::mr(context->r30, context->r3);
RUNTIME_PPC_JUMP_LABEL(.L_803FA114, 0x803FA114) //this is a jump label
/*803FA114 003F6F14*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r3));
RUNTIME_PPC_JUMP_LABEL(.L_803FA118, 0x803FA118) //this is a jump label
/*803FA118 003F6F18*/ PPC::Runtime::ASM::cmplwi(context->r3, 0x0);
/*803FA11C 003F6F1C*/ PPC::Runtime::ASM::bne(.L_803FA100);
/*803FA120 003F6F20*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r25));
/* 803FA124 003F6F24  54 18 07 BF */ clrlwi. context->r24 , context->r0 , 30
/*803FA128 003F6F28*/ PPC::Runtime::ASM::bne(.L_803FA130);
/*803FA12C 003F6F2C*/ PPC::Runtime::ASM::li(context->r24, 0x1);
RUNTIME_PPC_JUMP_LABEL(.L_803FA130, 0x803FA130) //this is a jump label
/*803FA130 003F6F30*/ PPC::Runtime::ASM::rlwinm.(context->r28, context->r0, 0, 17, 18);
/*803FA134 003F6F34*/ PPC::Runtime::ASM::bne(.L_803FA13C);
/*803FA138 003F6F38*/ PPC::Runtime::ASM::slwi(context->r28, context->r24, 13);
RUNTIME_PPC_JUMP_LABEL(.L_803FA13C, 0x803FA13C) //this is a jump label
/*803FA13C 003F6F3C*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA140 003F6F40*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA144 003F6F44*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r25));
/*803FA148 003F6F48*/ PPC::Runtime::ASM::mr(context->r31, context->r3);
/*803FA14C 003F6F4C*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 29, 29);
/*803FA150 003F6F50*/ PPC::Runtime::ASM::beq(.L_803FA2C8);
/*803FA154 003F6F54*/ PPC::Runtime::ASM::cmpwi(context->r24, 0x2);
/*803FA158 003F6F58*/ PPC::Runtime::ASM::beq(.L_803FA160);
/*803FA15C 003F6F5C*/ PPC::Runtime::ASM::b(.L_803FA1A4);
RUNTIME_PPC_JUMP_LABEL(.L_803FA160, 0x803FA160) //this is a jump label
/*803FA160 003F6F60*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA164 003F6F64*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA168 003F6F68*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA16C 003F6F6C*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA170 003F6F70*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA174 003F6F74*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA178 003F6F78*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA17C 003F6F7C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA180 003F6F80*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA184 003F6F84*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA188 003F6F88*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA18C 003F6F8C*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA190 003F6F90*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA194 003F6F94*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA198 003F6F98*/ PPC::Runtime::ASM::li(context->r10, 0x8);
/*803FA19C 003F6F9C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA1A0 003F6FA0*/ PPC::Runtime::ASM::b(.L_803FA200);
RUNTIME_PPC_JUMP_LABEL(.L_803FA1A4, 0x803FA1A4) //this is a jump label
/*803FA1A4 003F6FA4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA1A8 003F6FA8*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA1AC 003F6FAC*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*803FA1B0 003F6FB0*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA1B4 003F6FB4*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0x4);
/*803FA1B8 003F6FB8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA1BC 003F6FBC*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA1C0 003F6FC0*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA1C4 003F6FC4*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA1C8 003F6FC8*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA1CC 003F6FCC*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA1D0 003F6FD0*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA1D4 003F6FD4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA1D8 003F6FD8*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA1DC 003F6FDC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA1E0 003F6FE0*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA1E4 003F6FE4*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA1E8 003F6FE8*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA1EC 003F6FEC*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA1F0 003F6FF0*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA1F4 003F6FF4*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA1F8 003F6FF8*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA1FC 003F6FFC*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
RUNTIME_PPC_JUMP_LABEL(.L_803FA200, 0x803FA200) //this is a jump label
/*803FA200 003F7000*/ PPC::Runtime::ASM::cmpwi(context->r28, 0x4000);
/*803FA204 003F7004*/ PPC::Runtime::ASM::beq(.L_803FA20C);
/*803FA208 003F7008*/ PPC::Runtime::ASM::b(.L_803FA268);
RUNTIME_PPC_JUMP_LABEL(.L_803FA20C, 0x803FA20C) //this is a jump label
/*803FA20C 003F700C*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA210 003F7010*/ PPC::Runtime::ASM::li(context->r3, ByteArray_12 @ Get_MemoryOffset_SDA21);
/*803FA214 003F7014*/ PPC::Runtime::ASM::li(context->r4, 0x6);
/*803FA218 003F7018*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA21C 003F701C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA220 003F7020*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA224 003F7024*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA228 003F7028*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA22C 003F702C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA230 003F7030*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA234 003F7034*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA238 003F7038*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA23C 003F703C*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA240 003F7040*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA244 003F7044*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA248 003F7048*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA24C 003F704C*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA250 003F7050*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA254 003F7054*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA258 003F7058*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA25C 003F705C*/ PPC::Runtime::ASM::li(context->r10, 0x6);
/*803FA260 003F7060*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FA264 003F7064*/ PPC::Runtime::ASM::b(.L_803FA558);
RUNTIME_PPC_JUMP_LABEL(.L_803FA268, 0x803FA268) //this is a jump label
/*803FA268 003F7068*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA26C 003F706C*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA270 003F7070*/ PPC::Runtime::ASM::li(context->r4, 0x6);
/*803FA274 003F7074*/ PPC::Runtime::ASM::li(context->r5, 0x3);
/*803FA278 003F7078*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0xc);
/*803FA27C 003F707C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA280 003F7080*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA284 003F7084*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA288 003F7088*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA28C 003F708C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA290 003F7090*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA294 003F7094*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA298 003F7098*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA29C 003F709C*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA2A0 003F70A0*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA2A4 003F70A4*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA2A8 003F70A8*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA2AC 003F70AC*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA2B0 003F70B0*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA2B4 003F70B4*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA2B8 003F70B8*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA2BC 003F70BC*/ PPC::Runtime::ASM::li(context->r10, 0x6);
/*803FA2C0 003F70C0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FA2C4 003F70C4*/ PPC::Runtime::ASM::b(.L_803FA558);
RUNTIME_PPC_JUMP_LABEL(.L_803FA2C8, 0x803FA2C8) //this is a jump label
/*803FA2C8 003F70C8*/ PPC::Runtime::ASM::cmpwi(context->r24, 0x2);
/*803FA2CC 003F70CC*/ PPC::Runtime::ASM::beq(.L_803FA340);
/*803FA2D0 003F70D0*/ PPC::Runtime::ASM::bge(.L_803FA3A0);
/*803FA2D4 003F70D4*/ PPC::Runtime::ASM::cmpwi(context->r24, 0x1);
/*803FA2D8 003F70D8*/ PPC::Runtime::ASM::bge(.L_803FA2E0);
/*803FA2DC 003F70DC*/ PPC::Runtime::ASM::b(.L_803FA3A0);
RUNTIME_PPC_JUMP_LABEL(.L_803FA2E0, 0x803FA2E0) //this is a jump label
/*803FA2E0 003F70E0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA2E4 003F70E4*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA2E8 003F70E8*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*803FA2EC 003F70EC*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA2F0 003F70F0*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0x4);
/*803FA2F4 003F70F4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA2F8 003F70F8*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA2FC 003F70FC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA300 003F7100*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA304 003F7104*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA308 003F7108*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA30C 003F710C*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA310 003F7110*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA314 003F7114*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA318 003F7118*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA31C 003F711C*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA320 003F7120*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA324 003F7124*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA328 003F7128*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA32C 003F712C*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA330 003F7130*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA334 003F7134*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA338 003F7138*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA33C 003F713C*/ PPC::Runtime::ASM::b(.L_803FA418);
RUNTIME_PPC_JUMP_LABEL(.L_803FA340, 0x803FA340) //this is a jump label
/*803FA340 003F7140*/ PPC::Runtime::ASM::mr(context->r4, context->r30);
/*803FA344 003F7144*/ PPC::Runtime::ASM::li(context->r5, 0x4);
/*803FA348 003F7148*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA34C 003F714C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA350 003F7150*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA354 003F7154*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA358 003F7158*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA35C 003F715C*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA360 003F7160*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA364 003F7164*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*803FA368 003F7168*/ PPC::Runtime::ASM::li(context->r0, -0x2);
/*803FA36C 003F716C*/ PPC::Runtime::ASM::beq(.L_803FA374);
/*803FA370 003F7170*/ PPC::Runtime::ASM::li(context->r0, -0x1);
RUNTIME_PPC_JUMP_LABEL(.L_803FA374, 0x803FA374) //this is a jump label
/*803FA374 003F7174*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA378 003F7178*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA37C 003F717C*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA380 003F7180*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA384 003F7184*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA388 003F7188*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA38C 003F718C*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA390 003F7190*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA394 003F7194*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA398 003F7198*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA39C 003F719C*/ PPC::Runtime::ASM::b(.L_803FA418);
RUNTIME_PPC_JUMP_LABEL(.L_803FA3A0, 0x803FA3A0) //this is a jump label
/*803FA3A0 003F71A0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA3A4 003F71A4*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA3A8 003F71A8*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*803FA3AC 003F71AC*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA3B0 003F71B0*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0x4);
/*803FA3B4 003F71B4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA3B8 003F71B8*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA3BC 003F71BC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA3C0 003F71C0*/ PPC::Runtime::ASM::mr(context->r4, context->r30);
/*803FA3C4 003F71C4*/ PPC::Runtime::ASM::li(context->r5, 0x4);
/*803FA3C8 003F71C8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA3CC 003F71CC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA3D0 003F71D0*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA3D4 003F71D4*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA3D8 003F71D8*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA3DC 003F71DC*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA3E0 003F71E0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA3E4 003F71E4*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*803FA3E8 003F71E8*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA3EC 003F71EC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA3F0 003F71F0*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*803FA3F4 003F71F4*/ PPC::Runtime::ASM::li(context->r5, -0x2);
/*803FA3F8 003F71F8*/ PPC::Runtime::ASM::beq(.L_803FA400);
/*803FA3FC 003F71FC*/ PPC::Runtime::ASM::li(context->r5, -0x1);
RUNTIME_PPC_JUMP_LABEL(.L_803FA400, 0x803FA400) //this is a jump label
/*803FA400 003F7200*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA404 003F7204*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA408 003F7208*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA40C 003F720C*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA410 003F7210*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA414 003F7214*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
RUNTIME_PPC_JUMP_LABEL(.L_803FA418, 0x803FA418) //this is a jump label
/*803FA418 003F7218*/ PPC::Runtime::ASM::cmpwi(context->r28, 0x4000);
/*803FA41C 003F721C*/ PPC::Runtime::ASM::beq(.L_803FA490);
/*803FA420 003F7220*/ PPC::Runtime::ASM::bge(.L_803FA4E8);
/*803FA424 003F7224*/ PPC::Runtime::ASM::cmpwi(context->r28, 0x2000);
/*803FA428 003F7228*/ PPC::Runtime::ASM::beq(.L_803FA430);
/*803FA42C 003F722C*/ PPC::Runtime::ASM::b(.L_803FA4E8);
RUNTIME_PPC_JUMP_LABEL(.L_803FA430, 0x803FA430) //this is a jump label
/*803FA430 003F7230*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA434 003F7234*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA438 003F7238*/ PPC::Runtime::ASM::li(context->r4, 0x6);
/*803FA43C 003F723C*/ PPC::Runtime::ASM::li(context->r5, 0x3);
/*803FA440 003F7240*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0xc);
/*803FA444 003F7244*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA448 003F7248*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA44C 003F724C*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA450 003F7250*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA454 003F7254*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA458 003F7258*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA45C 003F725C*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA460 003F7260*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA464 003F7264*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA468 003F7268*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA46C 003F726C*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA470 003F7270*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA474 003F7274*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA478 003F7278*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA47C 003F727C*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA480 003F7280*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA484 003F7284*/ PPC::Runtime::ASM::li(context->r10, 0x6);
/*803FA488 003F7288*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FA48C 003F728C*/ PPC::Runtime::ASM::b(.L_803FA558);
RUNTIME_PPC_JUMP_LABEL(.L_803FA490, 0x803FA490) //this is a jump label
/*803FA490 003F7290*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA494 003F7294*/ PPC::Runtime::ASM::mr(context->r4, context->r30);
/*803FA498 003F7298*/ PPC::Runtime::ASM::li(context->r5, 0x4);
/*803FA49C 003F729C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA4A0 003F72A0*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA4A4 003F72A4*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA4A8 003F72A8*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA4AC 003F72AC*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA4B0 003F72B0*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA4B4 003F72B4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA4B8 003F72B8*/ PPC::Runtime::ASM::li(context->r0, -0x2);
/*803FA4BC 003F72BC*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA4C0 003F72C0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA4C4 003F72C4*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA4C8 003F72C8*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA4CC 003F72CC*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA4D0 003F72D0*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA4D4 003F72D4*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA4D8 003F72D8*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA4DC 003F72DC*/ PPC::Runtime::ASM::li(context->r10, 0x5);
/*803FA4E0 003F72E0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FA4E4 003F72E4*/ PPC::Runtime::ASM::b(.L_803FA558);
RUNTIME_PPC_JUMP_LABEL(.L_803FA4E8, 0x803FA4E8) //this is a jump label
/*803FA4E8 003F72E8*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA4EC 003F72EC*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA4F0 003F72F0*/ PPC::Runtime::ASM::li(context->r4, 0x6);
/*803FA4F4 003F72F4*/ PPC::Runtime::ASM::li(context->r5, 0x3);
/*803FA4F8 003F72F8*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0xc);
/*803FA4FC 003F72FC*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA500 003F7300*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA504 003F7304*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA508 003F7308*/ PPC::Runtime::ASM::mr(context->r4, context->r30);
/*803FA50C 003F730C*/ PPC::Runtime::ASM::li(context->r5, 0x4);
/*803FA510 003F7310*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA514 003F7314*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA518 003F7318*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA51C 003F731C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA520 003F7320*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA524 003F7324*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA528 003F7328*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA52C 003F732C*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA530 003F7330*/ PPC::Runtime::ASM::mr(context->r3, context->r31);
/*803FA534 003F7334*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA538 003F7338*/ PPC::Runtime::ASM::mr(context->r9, context->r24);
/*803FA53C 003F733C*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA540 003F7340*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA544 003F7344*/ PPC::Runtime::ASM::li(context->r6, 0x5);
/*803FA548 003F7348*/ PPC::Runtime::ASM::li(context->r7, -0x2);
/*803FA54C 003F734C*/ PPC::Runtime::ASM::li(context->r8, 0x6);
/*803FA550 003F7350*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA554 003F7354*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
RUNTIME_PPC_JUMP_LABEL(.L_803FA558, 0x803FA558) //this is a jump label
/*803FA558 003F7358*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA55C 003F735C*/ PPC::Runtime::ASM::mr(context->r24, context->r26);
/*803FA560 003F7360*/ PPC::Runtime::ASM::stw(context->r31, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FA564 003F7364*/ PPC::Runtime::ASM::b(.L_803FA5AC);
RUNTIME_PPC_JUMP_LABEL(.L_803FA568, 0x803FA568) //this is a jump label
/*803FA568 003F7368*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r24));
/*803FA56C 003F736C*/ PPC::Runtime::ASM::andi.(context->r0, context->r0, 0x50);
/*803FA570 003F7370*/ PPC::Runtime::ASM::beq(.L_803FA5A8);
/*803FA574 003F7374*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r24));
/*803FA578 003F7378*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xff);
/*803FA57C 003F737C*/ PPC::Runtime::ASM::beq(.L_803FA5A8);
/*803FA580 003F7380*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r24));
/*803FA584 003F7384*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA588 003F7388*/ PPC::Runtime::ASM::mr(context->r8, context->r27);
/*803FA58C 003F738C*/ PPC::Runtime::ASM::addi(context->r6, context->r1, 0x1c);
/*803FA590 003F7390*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r4));
/*803FA594 003F7394*/ PPC::Runtime::ASM::addi(context->r7, context->r1, 0x10);
/*803FA598 003F7398*/ PPC::Runtime::ASM::li(context->r4, 0x50);
/*803FA59C 003F739C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA5A0 003F73A0*/ PPC::Runtime::ASM::mtctr(context->r12);
/*803FA5A4 003F73A4*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_803FA5A8, 0x803FA5A8) //this is a jump label
/*803FA5A8 003F73A8*/ PPC::Runtime::ASM::lwz(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r24));
RUNTIME_PPC_JUMP_LABEL(.L_803FA5AC, 0x803FA5AC) //this is a jump label
/*803FA5AC 003F73AC*/ PPC::Runtime::ASM::cmplwi(context->r24, 0x0);
/*803FA5B0 003F73B0*/ PPC::Runtime::ASM::bne(.L_803FA568);
/*803FA5B4 003F73B4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r25));
/*803FA5B8 003F73B8*/ PPC::Runtime::ASM::ori(context->r29, context->r29, 0x50);
/*803FA5BC 003F73BC*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 29, 29);
/*803FA5C0 003F73C0*/ PPC::Runtime::ASM::beq(.L_803FA7C8);
/*803FA5C4 003F73C4*/ PPC::Runtime::ASM::rlwinm.(context->r24, context->r28, 0, 17, 17);
/*803FA5C8 003F73C8*/ PPC::Runtime::ASM::beq(.L_803FA674);
/*803FA5CC 003F73CC*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA5D0 003F73D0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA5D4 003F73D4*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA5D8 003F73D8*/ PPC::Runtime::ASM::mr(context->r28, context->r3);
/*803FA5DC 003F73DC*/ PPC::Runtime::ASM::li(context->r5, 0x5);
/*803FA5E0 003F73E0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA5E4 003F73E4*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA5E8 003F73E8*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA5EC 003F73EC*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA5F0 003F73F0*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA5F4 003F73F4*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA5F8 003F73F8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA5FC 003F73FC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA600 003F7400*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA604 003F7404*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA608 003F7408*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA60C 003F740C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA610 003F7410*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA614 003F7414*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA618 003F7418*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA61C 003F741C*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA620 003F7420*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA624 003F7424*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA628 003F7428*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA62C 003F742C*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA630 003F7430*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA634 003F7434*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA638 003F7438*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA63C 003F743C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA640 003F7440*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA644 003F7444*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA648 003F7448*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA64C 003F744C*/ PPC::Runtime::ASM::li(context->r4, 0x5);
/*803FA650 003F7450*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA654 003F7454*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA658 003F7458*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FA65C 003F745C*/ PPC::Runtime::ASM::li(context->r8, 0x5);
/*803FA660 003F7460*/ PPC::Runtime::ASM::li(context->r9, -0x2);
/*803FA664 003F7464*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA668 003F7468*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FA66C 003F746C*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA670 003F7470*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_803FA674, 0x803FA674) //this is a jump label
/*803FA674 003F7474*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA678 003F7478*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA67C 003F747C*/ PPC::Runtime::ASM::cmplwi(context->r30, 0x0);
/*803FA680 003F7480*/ PPC::Runtime::ASM::mr(context->r28, context->r3);
/*803FA684 003F7484*/ PPC::Runtime::ASM::beq(.L_803FA6DC);
/*803FA688 003F7488*/ PPC::Runtime::ASM::mr(context->r4, context->r30);
/*803FA68C 003F748C*/ PPC::Runtime::ASM::li(context->r5, 0x4);
/*803FA690 003F7490*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA694 003F7494*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA698 003F7498*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA69C 003F749C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA6A0 003F74A0*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA6A4 003F74A4*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA6A8 003F74A8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA6AC 003F74AC*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA6B0 003F74B0*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA6B4 003F74B4*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA6B8 003F74B8*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA6BC 003F74BC*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA6C0 003F74C0*/ PPC::Runtime::ASM::li(context->r6, 0x1);
/*803FA6C4 003F74C4*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA6C8 003F74C8*/ PPC::Runtime::ASM::li(context->r8, 0x1);
/*803FA6CC 003F74CC*/ PPC::Runtime::ASM::li(context->r9, -0x1);
/*803FA6D0 003F74D0*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA6D4 003F74D4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA6D8 003F74D8*/ PPC::Runtime::ASM::b(.L_803FA72C);
RUNTIME_PPC_JUMP_LABEL(.L_803FA6DC, 0x803FA6DC) //this is a jump label
/*803FA6DC 003F74DC*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA6E0 003F74E0*/ PPC::Runtime::ASM::li(context->r5, 0x4);
/*803FA6E4 003F74E4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA6E8 003F74E8*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA6EC 003F74EC*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA6F0 003F74F0*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA6F4 003F74F4*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA6F8 003F74F8*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA6FC 003F74FC*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA700 003F7500*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA704 003F7504*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA708 003F7508*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA70C 003F750C*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA710 003F7510*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA714 003F7514*/ PPC::Runtime::ASM::li(context->r6, 0x1);
/*803FA718 003F7518*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA71C 003F751C*/ PPC::Runtime::ASM::li(context->r8, 0x1);
/*803FA720 003F7520*/ PPC::Runtime::ASM::li(context->r9, -0x2);
/*803FA724 003F7524*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA728 003F7528*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
RUNTIME_PPC_JUMP_LABEL(.L_803FA72C, 0x803FA72C) //this is a jump label
/*803FA72C 003F752C*/ PPC::Runtime::ASM::cmplwi(context->r24, 0x0);
/*803FA730 003F7530*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA734 003F7534*/ PPC::Runtime::ASM::beq(.L_803FA780);
/*803FA738 003F7538*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA73C 003F753C*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA740 003F7540*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA744 003F7544*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA748 003F7548*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA74C 003F754C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA750 003F7550*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA754 003F7554*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA758 003F7558*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA75C 003F755C*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA760 003F7560*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA764 003F7564*/ PPC::Runtime::ASM::li(context->r6, 0x5);
/*803FA768 003F7568*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FA76C 003F756C*/ PPC::Runtime::ASM::li(context->r8, 0x5);
/*803FA770 003F7570*/ PPC::Runtime::ASM::li(context->r9, -0x2);
/*803FA774 003F7574*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA778 003F7578*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FA77C 003F757C*/ PPC::Runtime::ASM::b(.L_803FA7C4);
RUNTIME_PPC_JUMP_LABEL(.L_803FA780, 0x803FA780) //this is a jump label
/*803FA780 003F7580*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA784 003F7584*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA788 003F7588*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA78C 003F758C*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA790 003F7590*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA794 003F7594*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FA798 003F7598*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA79C 003F759C*/ PPC::Runtime::ASM::mr(context->r3, context->r28);
/*803FA7A0 003F75A0*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA7A4 003F75A4*/ PPC::Runtime::ASM::li(context->r4, 0x5);
/*803FA7A8 003F75A8*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA7AC 003F75AC*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA7B0 003F75B0*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FA7B4 003F75B4*/ PPC::Runtime::ASM::li(context->r8, 0x5);
/*803FA7B8 003F75B8*/ PPC::Runtime::ASM::li(context->r9, -0x2);
/*803FA7BC 003F75BC*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA7C0 003F75C0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
RUNTIME_PPC_JUMP_LABEL(.L_803FA7C4, 0x803FA7C4) //this is a jump label
/*803FA7C4 003F75C4*/ PPC::Runtime::ASM::stw(context->r28, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_803FA7C8, 0x803FA7C8) //this is a jump label
/*803FA7C8 003F75C8*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4, context->r25));
/*803FA7CC 003F75CC*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 28, 28);
/*803FA7D0 003F75D0*/ PPC::Runtime::ASM::beq(.L_803FA944);
/*803FA7D4 003F75D4*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r25));
/*803FA7D8 003F75D8*/ PPC::Runtime::ASM::mr(context->r6, context->r27);
/*803FA7DC 003F75DC*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*803FA7E0 003F75E0*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA7E4 003F75E4*/ PPC::Runtime::ASM::addi(context->r3, context->r3, 0x8);
/*803FA7E8 003F75E8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpCnst);
/*803FA7EC 003F75EC*/ PPC::Runtime::ASM::mr(context->r25, context->r3);
/*803FA7F0 003F75F0*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA7F4 003F75F4*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA7F8 003F75F8*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA7FC 003F75FC*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA800 003F7600*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA804 003F7604*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA808 003F7608*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA80C 003F760C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA810 003F7610*/ PPC::Runtime::ASM::stw(context->r25, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA814 003F7614*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA818 003F7618*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA81C 003F761C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA820 003F7620*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA824 003F7624*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA828 003F7628*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA82C 003F762C*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA830 003F7630*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA834 003F7634*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA838 003F7638*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803FA83C 003F763C*/ PPC::Runtime::ASM::mr(context->r24, context->r26);
/*803FA840 003F7640*/ PPC::Runtime::ASM::b(.L_803FA888);
RUNTIME_PPC_JUMP_LABEL(.L_803FA844, 0x803FA844) //this is a jump label
/*803FA844 003F7644*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r24));
/*803FA848 003F7648*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 26, 26);
/*803FA84C 003F764C*/ PPC::Runtime::ASM::beq(.L_803FA884);
/*803FA850 003F7650*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r24));
/*803FA854 003F7654*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xff);
/*803FA858 003F7658*/ PPC::Runtime::ASM::beq(.L_803FA884);
/*803FA85C 003F765C*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r24));
/*803FA860 003F7660*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA864 003F7664*/ PPC::Runtime::ASM::mr(context->r5, context->r29);
/*803FA868 003F7668*/ PPC::Runtime::ASM::mr(context->r8, context->r27);
/*803FA86C 003F766C*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r4));
/*803FA870 003F7670*/ PPC::Runtime::ASM::addi(context->r6, context->r1, 0x18);
/*803FA874 003F7674*/ PPC::Runtime::ASM::addi(context->r7, context->r1, 0x10);
/*803FA878 003F7678*/ PPC::Runtime::ASM::li(context->r4, 0x20);
/*803FA87C 003F767C*/ PPC::Runtime::ASM::mtctr(context->r12);
/*803FA880 003F7680*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_803FA884, 0x803FA884) //this is a jump label
/*803FA884 003F7684*/ PPC::Runtime::ASM::lwz(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r24));
RUNTIME_PPC_JUMP_LABEL(.L_803FA888, 0x803FA888) //this is a jump label
/*803FA888 003F7688*/ PPC::Runtime::ASM::cmplwi(context->r24, 0x0);
/*803FA88C 003F768C*/ PPC::Runtime::ASM::bne(.L_803FA844);
/*803FA890 003F7690*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA894 003F7694*/ PPC::Runtime::ASM::ori(context->r29, context->r29, 0x20);
/*803FA898 003F7698*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA89C 003F769C*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA8A0 003F76A0*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA8A4 003F76A4*/ PPC::Runtime::ASM::li(context->r5, 0x5);
/*803FA8A8 003F76A8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpOrder);
/*803FA8AC 003F76AC*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA8B0 003F76B0*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA8B4 003F76B4*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA8B8 003F76B8*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA8BC 003F76BC*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA8C0 003F76C0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA8C4 003F76C4*/ PPC::Runtime::ASM::li(context->r0, 0x0);
/*803FA8C8 003F76C8*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA8CC 003F76CC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA8D0 003F76D0*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA8D4 003F76D4*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA8D8 003F76D8*/ PPC::Runtime::ASM::li(context->r6, 0x1);
/*803FA8DC 003F76DC*/ PPC::Runtime::ASM::lwz(context->r7, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803FA8E0 003F76E0*/ PPC::Runtime::ASM::li(context->r8, 0x1);
/*803FA8E4 003F76E4*/ PPC::Runtime::ASM::li(context->r9, -0x2);
/*803FA8E8 003F76E8*/ PPC::Runtime::ASM::li(context->r10, 0x7);
/*803FA8EC 003F76EC*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA8F0 003F76F0*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803FA8F4 003F76F4*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA8F8 003F76F8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA8FC 003F76FC*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA900 003F7700*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA904 003F7704*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA908 003F7708*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA90C 003F770C*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA910 003F7710*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA914 003F7714*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA918 003F7718*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA91C 003F771C*/ PPC::Runtime::ASM::li(context->r4, 0x1);
/*803FA920 003F7720*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FA924 003F7724*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FA928 003F7728*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FA92C 003F772C*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FA930 003F7730*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FA934 003F7734*/ PPC::Runtime::ASM::lwz(context->r5, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x18, context->r1));
/*803FA938 003F7738*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FA93C 003F773C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FA940 003F7740*/ PPC::Runtime::ASM::stw(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_803FA944, 0x803FA944) //this is a jump label
/*803FA944 003F7744*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x1c, context->r1));
/*803FA948 003F7748*/ PPC::Runtime::ASM::mr(context->r24, context->r26);
/*803FA94C 003F774C*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*803FA950 003F7750*/ PPC::Runtime::ASM::b(.L_803FA998);
RUNTIME_PPC_JUMP_LABEL(.L_803FA954, 0x803FA954) //this is a jump label
/*803FA954 003F7754*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x4c, context->r24));
/*803FA958 003F7758*/ PPC::Runtime::ASM::rlwinm.(context->r0, context->r0, 0, 24, 24);
/*803FA95C 003F775C*/ PPC::Runtime::ASM::beq(.L_803FA994);
/*803FA960 003F7760*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0xc, context->r24));
/*803FA964 003F7764*/ PPC::Runtime::ASM::cmpwi(context->r0, 0xff);
/*803FA968 003F7768*/ PPC::Runtime::ASM::beq(.L_803FA994);
/*803FA96C 003F776C*/ PPC::Runtime::ASM::lwz(context->r4, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x0, context->r24));
/*803FA970 003F7770*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA974 003F7774*/ PPC::Runtime::ASM::mr(context->r5, context->r29);
/*803FA978 003F7778*/ PPC::Runtime::ASM::mr(context->r8, context->r27);
/*803FA97C 003F777C*/ PPC::Runtime::ASM::lwz(context->r12, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r4));
/*803FA980 003F7780*/ PPC::Runtime::ASM::addi(context->r6, context->r1, 0x14);
/*803FA984 003F7784*/ PPC::Runtime::ASM::addi(context->r7, context->r1, 0x10);
/*803FA988 003F7788*/ PPC::Runtime::ASM::li(context->r4, 0x80);
/*803FA98C 003F778C*/ PPC::Runtime::ASM::mtctr(context->r12);
/*803FA990 003F7790*/ PPC::Runtime::ASM::bctrl();
RUNTIME_PPC_JUMP_LABEL(.L_803FA994, 0x803FA994) //this is a jump label
/*803FA994 003F7794*/ PPC::Runtime::ASM::lwz(context->r24, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r24));
RUNTIME_PPC_JUMP_LABEL(.L_803FA998, 0x803FA998) //this is a jump label
/*803FA998 003F7798*/ PPC::Runtime::ASM::cmplwi(context->r24, 0x0);
/*803FA99C 003F779C*/ PPC::Runtime::ASM::bne(.L_803FA954);
/*803FA9A0 003F77A0*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*803FA9A4 003F77A4*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FA9A8 003F77A8*/ PPC::Runtime::ASM::cmplw(context->r3, context->r0);
/*803FA9AC 003F77AC*/ PPC::Runtime::ASM::bne(.L_803FA9CC);
/*803FA9B0 003F77B0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpGetType);
/*803FA9B4 003F77B4*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x1);
/*803FA9B8 003F77B8*/ PPC::Runtime::ASM::bne(.L_803FA9CC);
/*803FA9BC 003F77BC*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FA9C0 003F77C0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpGetType);
/*803FA9C4 003F77C4*/ PPC::Runtime::ASM::cmpwi(context->r3, 0x1);
/*803FA9C8 003F77C8*/ PPC::Runtime::ASM::beq(.L_803FAA64);
RUNTIME_PPC_JUMP_LABEL(.L_803FA9CC, 0x803FA9CC) //this is a jump label
/*803FA9CC 003F77CC*/ PPC::Runtime::ASM::mr(context->r3, context->r27);
/*803FA9D0 003F77D0*/ PPC::Runtime::ASM::bl(fn_HSD_TExpTev);
/*803FA9D4 003F77D4*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FA9D8 003F77D8*/ PPC::Runtime::ASM::mr(context->r24, context->r3);
/*803FA9DC 003F77DC*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA9E0 003F77E0*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FA9E4 003F77E4*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FA9E8 003F77E8*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorOp);
/*803FA9EC 003F77EC*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
/*803FA9F0 003F77F0*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FA9F4 003F77F4*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FA9F8 003F77F8*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FA9FC 003F77FC*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FAA00 003F7800*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FAA04 003F7804*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FAA08 003F7808*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FAA0C 003F780C*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FAA10 003F7810*/ PPC::Runtime::ASM::li(context->r10, 0x1);
/*803FAA14 003F7814*/ PPC::Runtime::ASM::bl(fn_HSD_TExpColorIn);
/*803FAA18 003F7818*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FAA1C 003F781C*/ PPC::Runtime::ASM::li(context->r4, 0x0);
/*803FAA20 003F7820*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FAA24 003F7824*/ PPC::Runtime::ASM::li(context->r6, 0x0);
/*803FAA28 003F7828*/ PPC::Runtime::ASM::li(context->r7, 0x1);
/*803FAA2C 003F782C*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaOp);
/*803FAA30 003F7830*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x10, context->r1));
/*803FAA34 003F7834*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FAA38 003F7838*/ PPC::Runtime::ASM::li(context->r4, 0x7);
/*803FAA3C 003F783C*/ PPC::Runtime::ASM::li(context->r5, 0x0);
/*803FAA40 003F7840*/ PPC::Runtime::ASM::stw(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x8, context->r1));
/*803FAA44 003F7844*/ PPC::Runtime::ASM::li(context->r6, 0x7);
/*803FAA48 003F7848*/ PPC::Runtime::ASM::li(context->r7, 0x0);
/*803FAA4C 003F784C*/ PPC::Runtime::ASM::li(context->r8, 0x7);
/*803FAA50 003F7850*/ PPC::Runtime::ASM::li(context->r9, 0x0);
/*803FAA54 003F7854*/ PPC::Runtime::ASM::li(context->r10, 0x5);
/*803FAA58 003F7858*/ PPC::Runtime::ASM::bl(fn_HSD_TExpAlphaIn);
/*803FAA5C 003F785C*/ PPC::Runtime::ASM::mr(context->r3, context->r24);
/*803FAA60 003F7860*/ PPC::Runtime::ASM::b(.L_803FAA68);
RUNTIME_PPC_JUMP_LABEL(.L_803FAA64, 0x803FAA64) //this is a jump label
/*803FAA64 003F7864*/ PPC::Runtime::ASM::lwz(context->r3, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x14, context->r1));
RUNTIME_PPC_JUMP_LABEL(.L_803FAA68, 0x803FAA68) //this is a jump label
/*803FAA68 003F7868*/ PPC::Runtime::ASM::addi(context->r11, context->r1, 0x40);
/*803FAA6C 003F786C*/ PPC::Runtime::ASM::bl(_restgpr_24);
/*803FAA70 003F7870*/ PPC::Runtime::ASM::lwz(context->r0, PPC_RUNTIME_GET_MEMORY_OFFSET_POS_HEX_LITERAL_OF_SINGLE_REGISTER(0x44, context->r1));
/*803FAA74 003F7874*/ PPC::Runtime::ASM::mtlr(context->r0);
/*803FAA78 003F7878*/ PPC::Runtime::ASM::addi(context->r1, context->r1, 0x40);
/*803FAA7C 003F787C*/ PPC::Runtime::ASM::blr();
}