#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



struct lbl_804F2010
{
uint32_t 0x8372838A
uint32_t 0x8372838A
uint32_t 0x00000000
};