#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "lbl_804E6DFC.hpp"
#include "lbl_804E6E0C.hpp"



struct lbl_805DAE48
{
uint32_t lbl_804E6DFC
uint32_t lbl_804E6E0C
};