#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



struct lbl_804E1268
{
uint32_t lbl_805DA330
uint32_t 0x00000000
uint32_t lbl_805DA340
uint32_t 0x00000000
uint32_t lbl_805DA348
uint32_t 0x00000000
uint32_t 0x00000000
uint32_t lbl_805DA330
uint32_t 0x00000000
uint32_t lbl_805DA340
uint32_t 0x00000000
uint32_t lbl_805DA348
uint32_t 0x00000000
uint32_t lbl_805DA350
uint32_t 0x00000000
uint32_t 0x00000000
uint32_t 0x53656374
uint32_t 0x6F72454D
uint32_t 0x00000000
uint32_t lbl_805DA360
uint32_t 0x00000000
uint32_t 0x00000000
};