#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "String_.hpp"
#include "lbl_804E0BBC.hpp"



struct lbl_805DA1C0
{
uint32_t String_ "SheetTexMg" 18
uint32_t lbl_804E0BBC
};