#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



struct lbl_804C56A0
{
uint32_t 0x82B782D7
uint32_t 0x82C482CC
uint32_t 0x8352815B
uint32_t 0x835882F0
uint32_t 0x83768362
uint32_t 0x83568385
uint32_t 0x82B582C8
uint32_t 0x82A282C5
uint32_t 0x825088CA
uint32_t 0x82F082C6
uint32_t 0x82E90000
};