#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_802905F8.hpp"
#include "fn_80371AA0.hpp"
#include "fn_8029D72C.hpp"
#include "fn_glEndFrame_TakeNoParam.hpp"
#include "fn_803749FC.hpp"



struct lbl_804F1010
{
uint32_t lbl_805DB9F0
uint32_t 0x00000000
uint32_t fn_802905F8
uint32_t fn_80371AA0
uint32_t fn_8029D72C
uint32_t fn_glEndFrame_TakeNoParam
uint32_t lbl_805DB9F0
uint32_t 0xFFFFFFF4
uint32_t fn_803749FC
};