#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "lbl_804B7660.hpp"
#include "fn_80260804.hpp"
#include "fn_80260828.hpp"
#include "fn_80260844.hpp"
#include "fn_80260860.hpp"
#include "fn_80260880.hpp"



struct lbl_804B769C
{
uint32_t lbl_804B7660
uint32_t 0x00000000
uint32_t fn_80260804
uint32_t fn_80260828
uint32_t fn_80260844
uint32_t fn_80260860
uint32_t fn_80260880
};