#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



struct lbl_804BF218
{
uint32_t 0x28256620
uint32_t 0x25662025
uint32_t 0x66292025
uint32_t 0x66202D20
uint32_t 0x28256620
uint32_t 0x25662025
uint32_t 0x66292025
uint32_t 0x660A0000
};