#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following
#include "fn_802D7D4C.hpp"



struct lbl_804D22E4
{
uint32_t lbl_805D912C
uint32_t 0x00000000
uint32_t fn_802D7D4C
};