#pragma once
//this code was generated by PPC || "https://github.com/SeanMott/PPC"


//auto-include
#include <PPCRuntime/GCContext.hpp>
#include <PPCRuntime/MacroJumps.hpp>


//this file depends on the following



struct MemoryOffset_773
{
uint32_t 0x3C205379
uint32_t 0x6E632054
uint32_t 0x65737420
uint32_t 0x3E000000
};